### ISSUE TITLE
configparser.NoSectionError: No section: 'CDS' when I doing troposphere correction 

### ISSUE THREAD

**Issue by ClementGold** [insarlab/MintPy#1008]
I get the error : configparser.NoSectionError: No section: 'CDS' when I doing the  step - correct_troposphere with the line script : !smallbaselineApp.py --dir {work_dir} {mintpy_config}

I have followed all the requirements to install PyAps but also it not working when I run the test from the terminal : " site-packages/pyaps3/autoget.py", line 102, in ECMWFdload
    key = config.get('CDS', 'key')
AttributeError: 'NoneType' object has no attribute 'get' 

When I install on the computer it's working with the .cdsapirc in my home directory on MacOS

Here are my script to deal with the insar 
**Full script that generated the error**

```
Download global atmospheric model files...
update mode: ON
output file: /home/ec2-user/SageMaker/efs/underwriters/CLEMENT/DockerMINTPY/TESTJACKARTA/inputs/ERA5.h5
1) output file either do NOT exist or is NOT newer than all GRIB files.
run or skip: run
--------------------------------------------------
downloading weather model data using PyAPS ...
number of grib files to download: 4
--------------------------------------------------
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/efs/.persisted_conda/axa_juliette/bin/smallbaselineApp.py", line 10, in <module>
    sys.exit(main())
  File "/home/ec2-user/SageMaker/efs/.persisted_conda/axa_juliette/lib/python3.9/site-packages/mintpy/cli/smallbaselineApp.py", line 208, in main
    run_smallbaselineApp(inps)
  File "/home/ec2-user/SageMaker/efs/.persisted_conda/axa_juliette/lib/python3.9/site-packages/mintpy/smallbaselineApp.py", line 1117, in run_smallbaselineApp
    app.run(steps=inps.runSteps)
  File "/home/ec2-user/SageMaker/efs/.persisted_conda/axa_juliette/lib/python3.9/site-packages/mintpy/smallbaselineApp.py", line 898, in run
    self.run_tropospheric_delay_correction(sname)
  File "/home/ec2-user/SageMaker/efs/.persisted_conda/axa_juliette/lib/python3.9/site-packages/mintpy/smallbaselineApp.py", line 648, in run_tropospheric_delay_correction
    mintpy.cli.tropo_pyaps3.main(iargs)
  File "/home/ec2-user/SageMaker/efs/.persisted_conda/axa_juliette/lib/python3.9/site-packages/mintpy/cli/tropo_pyaps3.py", line 166, in main
    run_tropo_pyaps3(inps)
  File "/home/ec2-user/SageMaker/efs/.persisted_conda/axa_juliette/lib/python3.9/site-packages/mintpy/tropo_pyaps3.py", line 702, in run_tropo_pyaps3
    inps.grib_files = dload_grib_files(
  File "/home/ec2-user/SageMaker/efs/.persisted_conda/axa_juliette/lib/python3.9/site-packages/mintpy/tropo_pyaps3.py", line 425, in dload_grib_files
    check_pyaps_account_config(tropo_model)
  File "/home/ec2-user/SageMaker/efs/.persisted_conda/axa_juliette/lib/python3.9/site-packages/mintpy/tropo_pyaps3.py", line 394, in check_pyaps_account_config
    val = cfg.get(section, opt)
  File "/home/ec2-user/SageMaker/efs/.persisted_conda/axa_juliette/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/home/ec2-user/SageMaker/efs/.persisted_conda/axa_juliette/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'CDS'
```

**Full error message**

```
configparser.NoSectionError: No section: 'CDS' when I doing the  step - correct_troposphere 
```

**System information**

* Operating system: LINUX AWS S3 

MintPy run perfectly with the example (Ridge Crest and Galapagos) so it's only this part which made some problem. 

I put my .cdsapirc file not directly in the basic home but here : "efs/underwriters/CLEMENT/DockerMINTPY/.cdsapirc"  because I work on virtual machine with amazon which I think doesn't allow to put a config file directly in the home

**Comment by yunjunz** [comment]
The error occurs because `pyaps3` expects two locations of the account information for ERA5: `~/.cdsapirc` file or `model.cfg` file under the package directory (`site-packages/pyaps3/model.cfg` when installed via conda). 

I am not sure about the home directory on virtual machine with AWS. An easy fix is to use the second expected location, by copying the [`model.cfg` file](https://github.com/insarlab/PyAPS/blob/main/src/pyaps3/model.cfg) to your package directory in AWS, and filling in the ERA5 account info in it.

I notice that the conda installed pyaps3 does not have the `model.cfg` file in the package directory, probably due to the typo in its [pyproject.toml](https://github.com/insarlab/PyAPS/blob/244552cdfcf4e1a55de5f1439be4f08eb45872ec/pyproject.toml#L48) file, will fix it later.

**Comment by ClementGold** [comment]
Dear Yunjunz, 

Issue is closed, Pyaps expected that you need the configuration file in your home directory, I find the one on AWS. 

I maybe have supplementary question when I run the small baseline.py for my data I don't have all the figure in png like in example like Galapagos or Ridgecrest example. That a bit strange because the config file doing normally all the same step

**Comment by yunjunz** [comment]
I am glad to hear you fixed the issue!

For the png figures, more descriptions are needed for a meaningful diagnosis, please don't hesitate to open another issue for it.
