### ISSUE TITLE
Problems loading data in the latest version of MintPy

### ISSUE THREAD

**Issue by Jichao96** [insarlab/MintPy#1070]
**Description of the problem**

It seems that when defining the meta, there is no 'UTM_ZONE'

**Full script that generated the error**

```
PASTE CODE HERE
```

**Full error message**

```
PASTE ERROR MESSAGE HERE
```
Traceback (most recent call last):
  File "/root/tools/miniconda3/envs/insarenv/bin/smallbaselineApp.py", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/tools/MintPy/src/mintpy/cli/smallbaselineApp.py", line 208, in main
    run_smallbaselineApp(inps)
  File "/root/tools/MintPy/src/mintpy/smallbaselineApp.py", line 1117, in run_smallbaselineApp
    app.run(steps=inps.runSteps)
  File "/root/tools/MintPy/src/mintpy/smallbaselineApp.py", line 874, in run
    self.run_load_data(sname)
  File "/root/tools/MintPy/src/mintpy/smallbaselineApp.py", line 176, in run_load_data
    mintpy.cli.load_data.main(iargs)
  File "/root/tools/MintPy/src/mintpy/cli/load_data.py", line 123, in main
    load_data(inps)
  File "/root/tools/MintPy/src/mintpy/load_data.py", line 784, in load_data
    prepare_metadata(iDict)
  File "/root/tools/MintPy/src/mintpy/load_data.py", line 633, in prepare_metadata
    prep_module.main(iargs)
  File "/root/tools/MintPy/src/mintpy/cli/prep_hyp3.py", line 94, in main
    prep_hyp3(inps)
  File "/root/tools/MintPy/src/mintpy/prep_hyp3.py", line 121, in prep_hyp3
    meta = add_hyp3_metadata(fname, meta, is_ifg=is_ifg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/tools/MintPy/src/mintpy/prep_hyp3.py", line 61, in add_hyp3_metadata
    N, W = ut.utm2latlon(meta, W, N)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/tools/MintPy/src/mintpy/utils/utils0.py", line 319, in utm2latlon
    zone_num = int(meta['UTM_ZONE'][:-1])
                   ~~~~^^^^^^^^^^^^
KeyError: 'UTM_ZONE'

**System information**

* Operating system: <!-- macOS, Linux, Windows, etc. -->
* Python environment: <!-- conda, macports, pip, path setup, etc. -->
* MintPy version: <!-- output of `smallbaselineApp.py -v` -->
* Your custom / default template file (if the bug is related to a specific dataset): <!-- It helps the diagnose a lot if you could post the configurations you used. You can drag-and-drop them here directly. -->

**Comment by yunjunz** [comment]
This metadata has been introduced for a while now for hyp3. I would recommend deleting all existing *.rsc files next to your tif files and run mintpy again.

**Comment by surendarmrs** [comment]
@saeid-aminjafari do you have any idea for the same problem in mintpy processing using Jupiter notebook? @yunjunz I am using gamma interferograms from ASF. I didn't see any .rsc files in that.
