### ISSUE TITLE
TypeError: Object dtype dtype('O')

### ISSUE THREAD

**Issue by marcontk** [insarlab/MintPy#1112]
I get the following error when starting the script to load the data, what could be the problem?

```bash
(mintpy152) marcont@MateMacPro mintpy_ERA5 % smallbaselineApp.py LiquineSenDT83.txt --dostep load_data
MintPy version 1.5.2, date 2023-08-09
--RUN-at-2023-11-01 23:49:44.279707--
Current directory: /Volumes/LaCie_d2/Insar/Processing/descending/LIQUINE/mintpy_ERA5
Run routine processing with smallbaselineApp.py on steps: ['load_data']
Remaining steps: ['modify_network', 'reference_point', 'quick_overview', 'correct_unwrap_error', 'invert_network', 'correct_LOD', 'correct_SET', 'correct_troposphere', 'deramp', 'correct_topography', 'residual_RMS', 'reference_date', 'velocity', 'geocode', 'google_earth', 'hdfeos5']
--------------------------------------------------
Project name: LiquineSenDT83
Go to work directory: /Volumes/LaCie_d2/Insar/Processing/descending/LIQUINE/mintpy_ERA5
copy default template file /Users/marcont/opt/miniconda3/envs/mintpy152/lib/python3.8/site-packages/mintpy/defaults/smallbaselineApp.cfg to work directory
read custom template file: /Volumes/LaCie_d2/Insar/Processing/descending/LIQUINE/mintpy_ERA5/LiquineSenDT83.txt
update default template based on input custom template
    mintpy.load.processor: auto --> gmtsar
    mintpy.load.unwFile: auto --> /Volumes/LaCie_d2/Insar/Processing/descending/LIQUINE/F2/intf_all/20*/unwrap_ll.grd
    mintpy.load.corFile: auto --> /Volumes/LaCie_d2/Insar/Processing/descending/LIQUINE/F2/intf_all/20*/corr_ll.grd
    mintpy.load.demFile: auto --> /Volumes/LaCie_d2/Insar/Processing/descending/LIQUINE/topo/dem_resamp_ll.grd
copy LiquineSenDT83.txt   to inputs   directory for backup.
copy smallbaselineApp.cfg to inputs   directory for backup.
copy LiquineSenDT83.txt   to pic      directory for backup.
copy smallbaselineApp.cfg to pic      directory for backup.
read default template file: /Volumes/LaCie_d2/Insar/Processing/descending/LIQUINE/mintpy_ERA5/smallbaselineApp.cfg


******************** step - load_data ********************

load_data.py --template /Volumes/LaCie_d2/Insar/Processing/descending/LIQUINE/mintpy_ERA5/smallbaselineApp.cfg /Volumes/LaCie_d2/Insar/Processing/descending/LIQUINE/mintpy_ERA5/LiquineSenDT83.txt --project LiquineSenDT83
processor : gmtsar
SAR platform/sensor : Sen
--------------------------------------------------
prepare metadata files for gmtsar products
prep_gmtsar.py /Volumes/LaCie_d2/Insar/Processing/descending/LIQUINE/mintpy_ERA5/LiquineSenDT83.txt
/Users/marcont/opt/miniconda3/envs/mintpy152/lib/python3.8/site-packages/mintpy/load_data.py:750: UserWarning: prep_gmtsar.py failed. Assuming its result exists and continue...
  warnings.warn('prep_gmtsar.py failed. Assuming its result exists and continue...')
--------------------------------------------------
updateMode : True
compression: None
multilook x/ystep: 1/1
multilook method : nearest
/Users/marcont/opt/miniconda3/envs/mintpy152/lib/python3.8/site-packages/osgeo/gdal.py:287: FutureWarning: Neither gdal.UseExceptions() nor gdal.DontUseExceptions() has been explicitly called. In GDAL 4.0, exceptions will be enabled by default.
  warnings.warn(
--------------------------------------------------
searching geometry files info
input data files:
height          : /Volumes/LaCie_d2/Insar/Processing/descending/LIQUINE/topo/dem_resamp_ll.grd
--------------------------------------------------
create HDF5 file /Volumes/LaCie_d2/Insar/Processing/descending/LIQUINE/mintpy_ERA5/inputs/geometryGeo.h5 with w mode
create dataset /height             of <class 'numpy.float32'>   in size of (2571, 2381) with compression = lzf
geocoded input, use contant value from metadata INCIDENCE_ANGLE
prepare slantRangeDistance ...
Traceback (most recent call last):
  File "/Users/marcont/opt/miniconda3/envs/mintpy152/bin/smallbaselineApp.py", line 10, in <module>
    sys.exit(main())
  File "/Users/marcont/opt/miniconda3/envs/mintpy152/lib/python3.8/site-packages/mintpy/cli/smallbaselineApp.py", line 208, in main
    run_smallbaselineApp(inps)
  File "/Users/marcont/opt/miniconda3/envs/mintpy152/lib/python3.8/site-packages/mintpy/smallbaselineApp.py", line 1117, in run_smallbaselineApp
    app.run(steps=inps.runSteps)
  File "/Users/marcont/opt/miniconda3/envs/mintpy152/lib/python3.8/site-packages/mintpy/smallbaselineApp.py", line 874, in run
    self.run_load_data(sname)
  File "/Users/marcont/opt/miniconda3/envs/mintpy152/lib/python3.8/site-packages/mintpy/smallbaselineApp.py", line 176, in run_load_data
    mintpy.cli.load_data.main(iargs)
  File "/Users/marcont/opt/miniconda3/envs/mintpy152/lib/python3.8/site-packages/mintpy/cli/load_data.py", line 123, in main
    load_data(inps)
  File "/Users/marcont/opt/miniconda3/envs/mintpy152/lib/python3.8/site-packages/mintpy/load_data.py", line 813, in load_data
    geom_geo_obj.write2hdf5(
  File "/Users/marcont/opt/miniconda3/envs/mintpy152/lib/python3.8/site-packages/mintpy/objects/stackDict.py", line 794, in write2hdf5
    f.attrs[key] = value
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/marcont/opt/miniconda3/envs/mintpy152/lib/python3.8/site-packages/h5py/_hl/attrs.py", line 104, in __setitem__
    self.create(name, data=value)
  File "/Users/marcont/opt/miniconda3/envs/mintpy152/lib/python3.8/site-packages/h5py/_hl/attrs.py", line 182, in create
    htype = h5t.py_create(original_dtype, logical=True)
  File "h5py/h5t.pyx", line 1664, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1688, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1748, in h5py.h5t.py_create
TypeError: Object dtype dtype('O') has no native HDF5 equivalent
```

**System information**

* Operating system: macOS 12.7.1
* Python environment: conda
* MintPy version:  1.5.2, date 2023-08-09
* InSAR processor/product: GMTSAR

**Comment by marcontk** [comment]
.

**Comment by stan-dot** [comment]
@marcontk what happened?
