### ISSUE TITLE
An error occurred using GACOS data in mintpy

### ISSUE THREAD

**Issue by mqd-lufei** [insarlab/MintPy#1124]
**mintpy has an error using the "ztd" file downloaded from the GACOS website.**

**Full script that generated the error**

```
smallbaselineApp.py MintpySenGamma.txt
```

**Full error message**

```
Traceback (most recent call last):
  File "/home/my_user/software/miniconda3/bin/smallbaselineApp.py", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/my_user/software/miniconda3/lib/python3.11/site-packages/mintpy/cli/smallbaselineApp.py", line 208, in main
    run_smallbaselineApp(inps)
  File "/home/my_user/software/miniconda3/lib/python3.11/site-packages/mintpy/smallbaselineApp.py", line 1117, in run_smallbaselineApp
    app.run(steps=inps.runSteps)
  File "/home/my_user/software/miniconda3/lib/python3.11/site-packages/mintpy/smallbaselineApp.py", line 898, in run
    self.run_tropospheric_delay_correction(sname)
  File "/home/my_user/software/miniconda3/lib/python3.11/site-packages/mintpy/smallbaselineApp.py", line 626, in run_tropospheric_delay_correction
    mintpy.cli.tropo_gacos.main(iargs)
  File "/home/my_user/software/miniconda3/lib/python3.11/site-packages/mintpy/cli/tropo_gacos.py", line 108, in main
    inps = cmd_line_parse(iargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/software/miniconda3/lib/python3.11/site-packages/mintpy/cli/tropo_gacos.py", line 87, in cmd_line_parse
    raise ValueError(msg)
ValueError: Radar-coded file from gamma is NOT supported!
    Try to geocode the time-series and geometry files and re-run with them instead.
```

**System information**

* Operating system: 
* Python environment: 
* MintPy version: 
* InSAR processor/product: 
* Your custom / default template file (if the bug is related to a specific dataset):

**Comment by yunjunz** [comment]
As the printout msg said, mintpy does not support Gamma products for operations involving geo-to-radar conversion, which requires a specific lookup table format, that Gamma does not have.
