### ISSUE TITLE
Template RidgecrestSenDT71 timeseries.h5 issue.

### ISSUE THREAD

**Issue by Hchmn** [insarlab/MintPy#1206]
**Description of the problem**

WARNING: ./inputs/ERA5.h5 does not contain all dates in C:\Users\Nash\Desktop\Jupyter\MintPy-main\timeseries.h5
Continue and enforce the differencing for their shared dates only.
        with following dates are ignored for differencing:
['20190809', '20190716', '20190622', '20190728', '20190610', '20190704', '20190815']

**Full script that generated the error**
smallbaselineApp.py C:\Users\{MY_PATH_DIR}\RidgecrestSenDT71.txt
```
```

**Full error message**

```
WARNING: ./inputs/ERA5.h5 does not contain all dates in C:\Users\Nash\Desktop\Jupyter\MintPy-main\timeseries.h5
Continue and enforce the differencing for their shared dates only.
        with following dates are ignored for differencing:
['20190809', '20190716', '20190622', '20190728', '20190610', '20190704', '20190815']
Traceback (most recent call last):
  File "C:\Users\Nash\miniforge3\Scripts\smallbaselineApp.py-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\Nash\miniforge3\lib\site-packages\mintpy\cli\smallbaselineApp.py", line 209, in main
    run_smallbaselineApp(inps)
  File "C:\Users\Nash\miniforge3\lib\site-packages\mintpy\smallbaselineApp.py", line 1155, in run_smallbaselineApp
    app.run(steps=inps.runSteps)
  File "C:\Users\Nash\miniforge3\lib\site-packages\mintpy\smallbaselineApp.py", line 935, in run
    self.run_tropospheric_delay_correction(sname)
  File "C:\Users\Nash\miniforge3\lib\site-packages\mintpy\smallbaselineApp.py", line 676, in run_tropospheric_delay_correction
    mintpy.cli.diff.main(iargs)
  File "C:\Users\Nash\miniforge3\lib\site-packages\mintpy\cli\diff.py", line 86, in main
    diff_file(
  File "C:\Users\Nash\miniforge3\lib\site-packages\mintpy\diff.py", line 390, in diff_file
    diff_timeseries(file1, file2[0], out_file, force_diff, max_num_pixel)
  File "C:\Users\Nash\miniforge3\lib\site-packages\mintpy\diff.py", line 100, in diff_timeseries
    ref_val = readfile.read(file2, datasetName=date_list_shared, box=ref_box)[0] * unit_fac
  File "C:\Users\Nash\miniforge3\lib\site-packages\mintpy\utils\readfile.py", line 331, in read
    dsname4atr = datasetName[0].split('-')[0]
IndexError: list index out of range
```

**System information**

* Operating system: 
* Python environment: 
* MintPy version: 
* InSAR processor/product: 
* Your custom / default template file (if the bug is related to a specific dataset):

**Comment by yunjunz** [comment]
Those dates are all the dates there is within the time-series, thus, it means your ERA5.h5 file is empty (probably due to a failed downloading). I would recommend checking your pyaps3 installation and account setup as described in its GitHub repo.
