### ISSUE TITLE
Missing cumtrapz attribute from scipy.integrate

### ISSUE THREAD

**Issue by totaibi** [insarlab/MintPy#1242]
Dear Yunjun, I hope you well

I got the following error within the tropospheric delay correction step:

calculating absolute delay for each date using PyAPS (Jolivet et al., 2011; 2014) ...
number of grib files used: 161
Traceback (most recent call last):
  File "/home/thamer/miniconda3/envs/gdal/bin/smallbaselineApp.py", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/thamer/miniconda3/envs/gdal/lib/python3.12/site-packages/mintpy/cli/smallbaselineApp.py", line 209, in main
    run_smallbaselineApp(inps)
  File "/home/thamer/miniconda3/envs/gdal/lib/python3.12/site-packages/mintpy/smallbaselineApp.py", line 1155, in run_smallbaselineApp
    app.run(steps=inps.runSteps)
  File "/home/thamer/miniconda3/envs/gdal/lib/python3.12/site-packages/mintpy/smallbaselineApp.py", line 935, in run
    self.run_tropospheric_delay_correction(sname)
  File "/home/thamer/miniconda3/envs/gdal/lib/python3.12/site-packages/mintpy/smallbaselineApp.py", line 682, in run_tropospheric_delay_correction
    mintpy.cli.tropo_pyaps3.main(iargs)
  File "/home/thamer/miniconda3/envs/gdal/lib/python3.12/site-packages/mintpy/cli/tropo_pyaps3.py", line 166, in main
    run_tropo_pyaps3(inps)
  File "/home/thamer/miniconda3/envs/gdal/lib/python3.12/site-packages/mintpy/tropo_pyaps3.py", line 741, in run_tropo_pyaps3
    calc_delay_timeseries(inps)
  File "/home/thamer/miniconda3/envs/gdal/lib/python3.12/site-packages/mintpy/tropo_pyaps3.py", line 676, in calc_delay_timeseries
    tropo_data = get_delay(
                 ^^^^^^^^^^
  File "/home/thamer/miniconda3/envs/gdal/lib/python3.12/site-packages/mintpy/tropo_pyaps3.py", line 545, in get_delay
    aps_obj = pa.PyAPS(
              ^^^^^^^^^
  File "/home/thamer/PyAPS/pyaps3/objects.py", line 174, in __init__
    [DDry,DWet] = processor.PTV2del(Pi,Ti,Vi,hgt,self.dict,verbose=verb)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thamer/PyAPS/pyaps3/processor.py", line 193, in PTV2del
    S1 = intg.cumtrapz(WonT,x=hgt,axis=-1)
         ^^^^^^^^^^^^^
AttributeError: module 'scipy.integrate' has no attribute 'cumtrapz'

The Scipy version (1.14.0), the mintpy version is the latest, and my PYAPS account is active.

Thank you in advance for your assistance

**Comment by yunjunz** [comment]
This is a PyAPS issue, which has been fixed on PyAPS (https://github.com/insarlab/PyAPS/pull/35) and included in its latest conda version 0.3.4. Please update your pyaps3.
