### ISSUE TITLE
Plotting error

### ISSUE THREAD

**Issue by srcgps** [insarlab/MintPy#1250]
Hi,

Can you please assist with the below error I encountered while running smallbaselineapp.py?

Go to work directory: /media/srcgps/Elements/SVGstack_Kiran/MINTPY
read default template file: /media/srcgps/Elements/SVGstack_Kiran/MINTPY/smallbaselineApp.cfg

******************** plot & save to pic ********************
view.py --dpi 150 --noverbose --nodisplay --update --memory 4.0 velocity.h5 --dem inputs/geometryRadar.h5 --mask maskTempCoh.h5
view.py --dpi 150 --noverbose --nodisplay --update --memory 4.0 temporalCoherence.h5 -c gray -v 0 1
view.py --dpi 150 --noverbose --nodisplay --update --memory 4.0 maskTempCoh.h5 -c gray -v 0 1
view.py --dpi 150 --noverbose --nodisplay --update --memory 4.0 inputs/geometryRadar.h5
Traceback (most recent call last):
  File "/home/srcgps/tools/MintPy/src/mintpy/cli/smallbaselineApp.py", line 213, in <module>
    main(sys.argv[1:])
  File "/home/srcgps/tools/MintPy/src/mintpy/cli/smallbaselineApp.py", line 208, in main
    run_smallbaselineApp(inps)
  File "/home/srcgps/tools/MintPy/src/mintpy/smallbaselineApp.py", line 1123, in run_smallbaselineApp
    app.plot_result()
  File "/home/srcgps/tools/MintPy/src/mintpy/smallbaselineApp.py", line 1061, in plot_result
    mintpy.cli.view.main(iargs)
  File "/home/srcgps/tools/MintPy/src/mintpy/cli/view.py", line 175, in main
    obj.plot()
  File "/home/srcgps/tools/MintPy/src/mintpy/view.py", line 1616, in plot
    plot_figure(j, self, metadata=self.atr)
  File "/home/srcgps/tools/MintPy/src/mintpy/view.py", line 1290, in plot_figure
    data = read_data4figure(i_start, i_end, inps, metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/srcgps/tools/MintPy/src/mintpy/view.py", line 1087, in read_data4figure
    data[i - i_start, :, :] = d
    ~~~~^^^^^^^^^^^^^^^^^^^
ValueError: could not broadcast input array from shape (1395,1585) into shape (1396,1585)

thank you.

**Comment by yunjunz** [comment]
Please follow the [bug report template](https://github.com/insarlab/MintPy/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) and fill in all the info there for better diagnosis.

**Comment by yunjunz** [comment]
1. Your mintpy version is very old, please update to the latest version
2. The reported inconsistent size in the geometryRadar.h5 file is likely due to the water mask file you specified, please follow [this notebook](https://github.com/insarlab/MintPy-tutorial/blob/main/applications/water_mask.ipynb) to prepare one.
