### ISSUE TITLE
Encountered the following error when importing GAMMA data：ValueError: required dataset "height" is missing in file geometryGeo.h5

### ISSUE THREAD

**Issue by songzwgithub** [insarlab/MintPy#1271]
Hello everyone,

It seems that I cannot generate the geometry H5 file correctly when importing GAMMA data.

**Full error message：**

```smallbaselineApp.py smallbaselineApp.cfg 

___________________________________________________________

  /##      /## /##             /##     /#######
 | ###    /###|__/            | ##    | ##__  ##
 | ####  /#### /## /#######  /######  | ##  \ ## /##   /##
 | ## ##/## ##| ##| ##__  ##|_  ##_/  | #######/| ##  | ##
 | ##  ###| ##| ##| ##  \ ##  | ##    | ##____/ | ##  | ##
 | ##\  # | ##| ##| ##  | ##  | ## /##| ##      | ##  | ##
 | ## \/  | ##| ##| ##  | ##  |  ####/| ##      |  #######
 |__/     |__/|__/|__/  |__/   \___/  |__/       \____  ##
                                                 /##  | ##
                                                |  ######/
   Miami InSAR Time-series software in Python    \______/
          MintPy 1.6.1, 2024-07-31
___________________________________________________________

--RUN-at-2024-09-27 23:37:32.966171--
Current directory: /media/s/新加卷/DATA_process/cangzhou/asc/P142F116/SLC/mintpy
Run routine processing with smallbaselineApp.py on steps: ['load_data', 'modify_network', 'reference_point', 'quick_overview', 'correct_unwrap_error', 'invert_network', 'correct_LOD', 'correct_SET', 'correct_ionosphere', 'correct_troposphere', 'deramp', 'correct_topography', 'residual_RMS', 'reference_date', 'velocity', 'geocode', 'google_earth', 'hdfeos5']
Remaining steps: ['modify_network', 'reference_point', 'quick_overview', 'correct_unwrap_error', 'invert_network', 'correct_LOD', 'correct_SET', 'correct_ionosphere', 'correct_troposphere', 'deramp', 'correct_topography', 'residual_RMS', 'reference_date', 'velocity', 'geocode', 'google_earth', 'hdfeos5']
--------------------------------------------------
Go to work directory: /media/s/新加卷/DATA_process/cangzhou/asc/P142F116/SLC/mintpy
read default template file: /media/s/新加卷/DATA_process/cangzhou/asc/P142F116/SLC/mintpy/smallbaselineApp.cfg


******************** step - load_data ********************

load_data.py --template /media/s/新加卷/DATA_process/cangzhou/asc/P142F116/SLC/mintpy/smallbaselineApp.cfg
processor : gamma
SAR platform/sensor : unknown from project name "None"
--------------------------------------------------
prepare metadata files for gamma products
prep_gamma.py "interferograms/*/diff_*rlks.unw" --dem "geometry/sim_*rlks.rdc.dem"
prep_gamma.py "interferograms/*/filt_*rlks.cor" --dem "geometry/sim_*rlks.rdc.dem"
prep_gamma.py "geometry/sim_*rlks.rdc.dem" --dem "geometry/sim_*rlks.rdc.dem"
grab LAT/LON_REF1/2/3/4 from par file: /media/s/新加卷/DATA_process/cangzhou/asc/P142F116/SLC/mintpy/geometry/20201112_10rlks.amp.par
prep_gamma.py "geometry/sim_*rlks.UTM_TO_RDC" --dem "geometry/sim_*rlks.rdc.dem"
writing >>> sim_20201112_10rlks.UTM_TO_RDC.rsc
prep_gamma.py "geometry/sim_*rlks.UTM_TO_RDC" --dem "geometry/sim_*rlks.rdc.dem"
writing >>> sim_20201112_10rlks.UTM_TO_RDC.rsc
--------------------------------------------------
updateMode : True
compression: None
multilook x/ystep: 1/1
multilook method : nearest
--------------------------------------------------
searching geometry files info
input data files:
height          : geometry/sim_20201112_10rlks.rdc.dem
rangeCoord      : geometry/sim_20201112_10rlks.UTM_TO_RDC
azimuthCoord    : geometry/sim_20201112_10rlks.UTM_TO_RDC
--------------------------------------------------
create HDF5 file /media/s/新加卷/DATA_process/cangzhou/asc/P142F116/SLC/mintpy/inputs/geometryGeo.h5 with w mode
create dataset /rangeCoord         of <class 'numpy.float32'>   in size of (2397, 3919) with compression = lzf
create dataset /azimuthCoord       of <class 'numpy.float32'>   in size of (2397, 3919) with compression = lzf
geocoded input, use constant value from metadata INCIDENCE_ANGLE
prepare slantRangeDistance ...
Finished writing to /media/s/新加卷/DATA_process/cangzhou/asc/P142F116/SLC/mintpy/inputs/geometryGeo.h5
--------------------------------------------------
create HDF5 file /media/s/新加卷/DATA_process/cangzhou/asc/P142F116/SLC/mintpy/inputs/geometryRadar.h5 with w mode
create dataset /height             of <class 'numpy.float32'>   in size of (1060, 1200) with compression = lzf
Finished writing to /media/s/新加卷/DATA_process/cangzhou/asc/P142F116/SLC/mintpy/inputs/geometryRadar.h5
--------------------------------------------------
searching interferogram pairs info
input data files:
unwrapPhase     : interferograms/*/diff_*rlks.unw
coherence       : interferograms/*/filt_*rlks.cor
number of unwrapPhase     : 945
number of coherence       : 945
All date12   exists in file ifgramStack.h5 with same size as required, no need to re-load.
--------------------------------------------------
searching ionosphere pairs info
input data files:
WARNING: No data files found for the required dataset: ['unwrapPhase']! Skip loading for ionosphere stack.
--------------------------------------------------
searching offset pairs info
input data files:
WARNING: No data files found for the required dataset: ['rangeOffset', 'azimuthOffset']! Skip loading for offset stack.
time used: 00 mins 4.4 secs.

Traceback (most recent call last):
  File "/home/s/anaconda3/envs/sentinel/bin/smallbaselineApp.py", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/s/anaconda3/envs/sentinel/lib/python3.12/site-packages/mintpy/cli/smallbaselineApp.py", line 209, in main
    run_smallbaselineApp(inps)
  File "/home/s/anaconda3/envs/sentinel/lib/python3.12/site-packages/mintpy/smallbaselineApp.py", line 1155, in run_smallbaselineApp
    app.run(steps=inps.runSteps)
  File "/home/s/anaconda3/envs/sentinel/lib/python3.12/site-packages/mintpy/smallbaselineApp.py", line 908, in run
    self.run_load_data(sname)
  File "/home/s/anaconda3/envs/sentinel/lib/python3.12/site-packages/mintpy/smallbaselineApp.py", line 182, in run_load_data
    stack_file, geom_file, _, ion_file = ut.check_loaded_dataset(self.workDir, print_msg=True)[:4]
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s/anaconda3/envs/sentinel/lib/python3.12/site-packages/mintpy/utils/utils.py", line 89, in check_loaded_dataset
    raise ValueError(f'required dataset "{dname}" is missing in file {geom_file}')
ValueError: required dataset "height" is missing in file /media/s/新加卷/DATA_process/cangzhou/asc/P142F116/SLC/mintpy/inputs/geometryGeo.h5
```

The template used is as follows：
```
mintpy.load.processor       = gamma  #[isce, aria, hyp3, gmtsar, snap, gamma, roipac, nisar], auto for isce
mintpy.load.autoPath        = auto  #[yes / no], auto for no, use pre-defined auto path
mintpy.load.updateMode      = auto  #[yes / no], auto for yes, skip re-loading if HDF5 files are complete
mintpy.load.compression     = auto  #[gzip / lzf / no], auto for no.
##---------interferogram stack:
mintpy.load.unwFile         = interferograms/*/diff_*rlks.unw  #[path pattern of unwrapped interferogram files]
mintpy.load.corFile         = interferograms/*/filt_*rlks.cor  #[path pattern of spatial coherence       files]
mintpy.load.connCompFile    = auto  #[path pattern of connected components    files], optional but recommended
mintpy.load.intFile         = auto  #[path pattern of wrapped interferogram   files], optional
mintpy.load.magFile         = auto  #[path pattern of interferogram magnitude files], optional
##---------geometry:
mintpy.load.demFile         = geometry/sim_*rlks.rdc.dem  #[path of DEM file]
mintpy.load.lookupYFile     = geometry/sim_*rlks.UTM_TO_RDC  #[path of latitude /row   /y coordinate file], not required for geocoded data
mintpy.load.lookupXFile     = geometry/sim_*rlks.UTM_TO_RDC  #[path of longitude/column/x coordinate file], not required for geocoded data
mintpy.load.incAngleFile    = auto  #[path of incidence angle file], optional but recommended
mintpy.load.azAngleFile     = auto  #[path of azimuth   angle file], optional
mintpy.load.shadowMaskFile  = auto  #[path of shadow mask file], optional but recommended
mintpy.load.waterMaskFile   = auto  #[path of water  mask file], optional but recommended
mintpy.load.bperpFile       = auto  #[path pattern of 2D perpendicular baseline file], optional
```

**System information**

    Operating system: Linux
    Python environment: conda
    MintPy version: 1.6.1
    InSAR processor/product: gamma 

I would greatly appreciate it if anyone could provide some advice.

**Comment by yunjunz** [comment]
It seems that the DEM `height` has been successfully loaded into the `geometryRadar.h5` file, but the `ut.check_loaded_dataset()` is looking for `geometryGeo.h5` instead, based on the coordinates information from `ifgramStack.h5` file. Are your interferograms geocoded already? If so, you should specify a DEM file in the geo-coordinate to `mintpy.load.demFile`, to be consistent with your interferograms.

**Comment by songzwgithub** [comment]
> It seems that the DEM `height` has been successfully loaded into the `geometryRadar.h5` file, but the `ut.check_loaded_dataset()` is looking for `geometryGeo.h5` instead, based on the coordinates information from `ifgramStack.h5` file. Are your interferograms geocoded already? If so, you should specify a DEM file in the geo-coordinate to `mintpy.load.demFile`, to be consistent with your interferograms.

Thank you for your reply. The interferograms have not been geocoded. It seems that there was a problem with the prepared files, but when I deleted them all and reprocessed them, there were no issues.

**Comment by zhangtheoutlaw** [comment]
> > 看起来DEM已经成功加载到文件中，但他们根据文件中的坐标信息寻找。你的干涉图已经做过地理编码了吗？如果是这样，你应该在地理坐标中指定一个DEM文件到 ，以与干涉图保持一致。`height``geometryRadar.h5``ut.check_loaded_dataset()``geometryGeo.h5``ifgramStack.h5``mintpy.load.demFile`
> 
> 谢谢你的回复。干涉图尚未进行地理编码。看起来是预备文件出了问题，但我删除并重新处理后，没有出现任何问题。

Hello, I'm currently experiencing the same issue. Could you please tell me which prepared files you deleted and which steps you repeated? Thank you very much.
