### ISSUE TITLE
Exporting a shapefile using save_qgis.py error 

### ISSUE THREAD

**Issue by keepfighting666** [insarlab/MintPy#1300]
!save_qgis.py timeseries.h5 -g inputs/geometryGeo.h5 -o ts.shp

gather auxliary data files
TimeSeries: timeseries.h5
Velocity  : velocity.h5
Coherence : temporalCoherence.h5
Mask      : maskTempCoh.h5
Geometry  : inputs/geometryGeo.h5
output shape file: ts.shp
output shape file: ts.shp exists, will be overwritten ....
number of points with time-series: 1945177
Traceback (most recent call last):
  File "/home/anaconda3/envs/opensarlab_mintpy_recipe_book/bin/save_qgis.py", line 8, in <module>
    sys.exit(main())
  File "/home/anaconda3/envs/opensarlab_mintpy_recipe_book/lib/python3.9/site-packages/mintpy/cli/save_qgis.py", line 69, in main
    save_qgis(inps)
  File "/home/anaconda3/envs/opensarlab_mintpy_recipe_book/lib/python3.9/site-packages/mintpy/save_qgis.py", line 245, in save_qgis
    write_shape_file(fDict, inps.shp_file, box=box, zero_first=inps.zero_first)
  File "/home/anaconda3/envs/opensarlab_mintpy_recipe_book/lib/python3.9/site-packages/mintpy/save_qgis.py", line 169, in write_shape_file
    lats, lons = ut.get_lat_lon(ts_obj.metadata, geom_file=fDict['Geometry'], box=box)
  File "/home/anaconda3/envs/opensarlab_mintpy_recipe_book/lib/python3.9/site-packages/mintpy/utils/utils0.py", line 471, in get_lat_lon
    raise ValueError(msg)
ValueError: Can not get pixel-wise lat/lon!
meta dict is not geocoded and/or geometry file does not contains latitude/longitude dataset.

**Comment by yunjunz** [comment]
@keepfighting666 could you provide more information as shown in the [bug report template](https://github.com/insarlab/MintPy/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)?

**Comment by ditafaith** [comment]
Hi @yunjunz 
I updated the tool using pip, however, I still can't use save_gdal.py -m, for example save_gdal.py timeseries_ERA5_ramp_demErr.h5 -m maskTempCoh.h5 -o output.tif
Do you any insight?

**Comment by yunjunz** [comment]
> Hi [@yunjunz](https://github.com/yunjunz) I updated the tool using pip, however, I still can't use save_gdal.py -m, for example save_gdal.py timeseries_ERA5_ramp_demErr.h5 -m maskTempCoh.h5 -o output.tif Do you any insight?

Follow the instructions here: https://github.com/insarlab/MintPy/blob/main/docs/installation.md#2-install-the-development-version.

And comment on the related issue next time please.
