### ISSUE TITLE
No default reference_date

### ISSUE THREAD

**Issue by EJFielding** [insarlab/MintPy#202]
**Description of the problem**

Running the the full `smallbaselineApp.py` with the tropospheric correction and topographic residual correction turned off fails when it reaches the "reference_date" step. I thought it would automatically set the reference date to the first date.

**Full script that generated the error**

Contents of my configuration file.

```
mintpy.reference.yx           = auto
#mintpy.reference.lalo        = -35.5,-117.7
#mintpy.topographicResidual.stepFuncDate  = 20170910,20180613  #eruption dates
#mintpy.deramp                = linear

mintpy.troposphericDelay.method         = no  #[pyaps / height_correlation / no], auto for pyaps
mintpy.troposphericDelay.weatherModel   = ERA5  #[ECMWF / MERRA / NARR], auto for ECMWF, for pyaps method
mintpy.troposphericDelay.weatherDir     = ./  #[path2directory], auto for WEATHER_DIR or "./"
mintpy.troposphericDelay.polyOrder      = auto  #[1 / 2 / 3], auto for 1, for height_correlation method
mintpy.troposphericDelay.looks          = auto  #[1-inf], auto for 8, for height_correlation, number of looks
mintpy.troposphericDelay.minCorrelation = auto  #[0.0-1.0], auto for 0, for height_correlation

mintpy.topographicResidual  = no
mintpy.residualRMS.maskFile = auto  #[file name / no], auto for maskTempCoh.h5, mask for ramp estimation
mintpy.residualRMS.deramp   = auto  #[quadratic / linear / no], auto for quadratic
mintpy.residualRMS.cutoff   = auto  #[0.0-inf], auto for 3
```

**Full error message**

```
...
generate_mask.py temporalCoherence.h5 -m 0.7 -o maskTempCoh.h5 --base /u/pez-z2/fielding/Calif/Ridgecrest/S1AB/D071/postseismic/MintPy_v1/inputs/geometryRadar.h5 --base-dataset shadowMask --base-value 1
update mode: ON
run or skip: run
input temporalCoherence file: temporalCoherence.h5
read temporalCoherence.h5
create initial mask with the same size as the input file and all = 1
all pixels with nan value = 0
exclude pixels with value < 0.7
exclude pixels in base file geometryRadar.h5 dataset shadowMask with value == 1.0
create HDF5 file: maskTempCoh.h5 with w mode
create dataset /mask of bool       in size of (3343, 9747)         with compression=None
finished writing to maskTempCoh.h5
time used: 00 mins 0.7 secs.
number of reliable pixels: 29101856


******************** step - correct_LOD ********************
No local oscillator drift correction is needed for Sen.


******************** step - correct_troposphere ********************
No tropospheric delay correction.


******************** step - deramp ********************
No phase ramp removal.


******************** step - correct_topography ********************
No topographic residual correction.


******************** step - residual_RMS ********************
No residual phase file found! Skip residual RMS analysis.


******************** step - reference_date ********************
reference_date.py -t /u/pez-z2/fielding/Calif/Ridgecrest/S1AB/D071/postseismic/MintPy_v1/smallbaselineApp.cfg  timeseries.h5
input reference date: reference_date.txt
Traceback (most recent call last):
  File "/home/fielding/tools/MintPy/mintpy/smallbaselineApp.py", line 1077, in <module>
    main()
  File "/home/fielding/tools/MintPy/mintpy/smallbaselineApp.py", line 1067, in main
    app.run(steps=inps.runSteps, plot=inps.plot)
  File "/home/fielding/tools/MintPy/mintpy/smallbaselineApp.py", line 1029, in run
    self.run_reference_date(sname)
  File "/home/fielding/tools/MintPy/mintpy/smallbaselineApp.py", line 824, in run_reference_date
    mintpy.reference_date.main(scp_args.split())
  File "/home/fielding/tools/MintPy/mintpy/reference_date.py", line 142, in main
    inps.refDate = read_ref_date(inps)
  File "/home/fielding/tools/MintPy/mintpy/reference_date.py", line 90, in read_ref_date
    raise Exception(msg)
Exception: input reference date: reference_date.txt is not found.
All available dates:
['20190716', '20190728', '20190809', '20190815', '20190821', '20190827']

```

**System information**

* Operating system:MacOS
* Version of Python and relevant dependencies if applicable 3.7
* Version of MintPy (output of `smallbaselineApp.py -v`): MintPy release version v1.2beta-23, release date 2019-08-28

**Comment by yunjunz** [comment]
Hi @EJFielding, you are right: the reference date is set to the first date by default in the `invert_network` step. The `reference_date` step is to re-set it to another date, which by default is assigned by the reference_date.txt file. And this file does not exist since the topographic residual correction is turned off, which I never did. It's a minor bug, I just committed the fix. Thank you for pointing it out!

**Comment by EJFielding** [comment]
Thanks for the quick fix.

**Comment by EJFielding** [comment]
I figured that there is not much reason to estimate the topographic residual because of the small baseline variation of the Sentinel-1 data, especially when I have only 6 dates.
![Network](https://user-images.githubusercontent.com/7253576/64136708-828d2a00-cda8-11e9-8374-579d7569c39f.png)

**Comment by yunjunz** [comment]
I agree.
