### ISSUE TITLE
MemoryError for geocoding with GAMMA lookup table

### ISSUE THREAD

**Issue by Giannisadtkb** [insarlab/MintPy#258]
When processing, I have divided the data into 12 blocks, but the memory error is still prompted. Divide the data into more blocks or report the same error:“MemoryError: Unable to allocate array with shape (112, 3591, 4528) and data type float32”

```
******************** step - geocode ********************
geocode.py -l /media/wu/文档/kunlun/dinsar/gamma_minpy/burst2/mintpy/inputs/geometryGeo.h5 -t /media/wu/文档/kunlun/dinsar/gamma_minpy/burst2/mintpy/smallbaselineApp.cfg --outdir /media/wu/文档/kunlun/dinsar/gamma_minpy/burst2/mintpy/geo --update  /media/wu/文档/kunlun/dinsar/gamma_minpy/burst2/mintpy/inputs/geometryRadar.h5 temporalCoherence.h5 timeseries_tropHgt_demErr.h5 velocity.h5
geocode.py -l /media/wu/文档/kunlun/dinsar/gamma_minpy/burst2/mintpy/inputs/geometryGeo.h5 -t /media/wu/文档/kunlun/dinsar/gamma_minpy/burst2/mintpy/smallbaselineApp.cfg --outdir /media/wu/文档/kunlun/dinsar/gamma_minpy/burst2/mintpy/geo --update /media/wu/文档/kunlun/dinsar/gamma_minpy/burst2/mintpy/inputs/geometryRadar.h5 temporalCoherence.h5 timeseries_tropHgt_demErr.h5 velocity.h5
read input option from template file: /media/wu/文档/kunlun/dinsar/gamma_minpy/burst2/mintpy/smallbaselineApp.cfg
number of processor to be used: 1
--------------------------------------------------
resampling file: /media/wu/文档/kunlun/dinsar/gamma_minpy/burst2/mintpy/inputs/geometryRadar.h5
['/media/wu/文档/kunlun/dinsar/gamma_minpy/burst2/mintpy/geo/geo_geometryRadar.h5'] exists and is newer than ['/media/wu/文档/kunlun/dinsar/gamma_minpy/burst2/mintpy/inputs/geometryRadar.h5', '/media/wu/文档/kunlun/dinsar/gamma_minpy/burst2/mintpy/inputs/geometryGeo.h5'] --> skip.
update mode is ON, skip geocoding.
--------------------------------------------------
resampling file: temporalCoherence.h5
['/media/wu/文档/kunlun/dinsar/gamma_minpy/burst2/mintpy/geo/geo_temporalCoherence.h5'] exists and is newer than ['temporalCoherence.h5', '/media/wu/文档/kunlun/dinsar/gamma_minpy/burst2/mintpy/inputs/geometryGeo.h5'] --> skip.
update mode is ON, skip geocoding.
--------------------------------------------------
resampling file: timeseries_tropHgt_demErr.h5
reading timeseries from timeseries_tropHgt_demErr.h5 ...
resampling using scipy.interpolate.RegularGridInterpolator ...
[==================================================]  101s /     2s
update REF_LAT/LON/Y/X
Traceback (most recent call last):
  File "/home/wu/python/MintPy/mintpy/smallbaselineApp.py", line 1090, in <module>
    main()
  File "/home/wu/python/MintPy/mintpy/smallbaselineApp.py", line 1080, in main
    app.run(steps=inps.runSteps, plot=inps.plot)
  File "/home/wu/python/MintPy/mintpy/smallbaselineApp.py", line 1048, in run
    self.run_geocode(sname)
  File "/home/wu/python/MintPy/mintpy/smallbaselineApp.py", line 887, in run_geocode
    mintpy.geocode.main(scp_args.split())
  File "/home/wu/python/MintPy/mintpy/geocode.py", line 335, in main
    run_geocode(inps)
  File "/home/wu/python/MintPy/mintpy/geocode.py", line 324, in run_geocode
    writefile.write(dsResDict, out_file=outfile, metadata=atr, ref_file=infile)
  File "/home/wu/python/MintPy/mintpy/utils/writefile.py", line 61, in write
    compression=compression)
  File "/home/wu/python/MintPy/mintpy/objects/stack.py", line 367, in write2hdf5
    data = np.array(data, dtype=np.float32)
```

**Comment by yunjunz** [comment]
Hi @Giannisadtkb, the geocoding using GAMMA lookup table is simply calling the `scipy.interpolate.RegularGridInterpolator` module. From the info you show, I don't see any obvious problem.

If you would like us to take a look at the issue you have, please follow the [bug report template](https://github.com/insarlab/MintPy/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) and fill as much information as possible, so that we can better diagnose.

**Comment by Giannisadtkb** [comment]
The problem is now resolved quietly, it should be the memory problem, when I shut down and restart to free the memory, now no error
