### ISSUE TITLE
Error loading stackSentinel output processed twice

### ISSUE THREAD

**Issue by EJFielding** [insarlab/MintPy#269]
**Description of the problem**

I used the stackSentinel processing system in ISCE to process a stack twice. The first time, I had the first date in December 2019. Then I went back and reprocessed the stack starting in July 2019. When I tried to load the data from the stack into MintPy, it seems that it got confused because there were baselines with two different reference dates in the baselines directory.

**Full script that generated the error**

Here is the listing of the baselines directory
```
(mintpy) [fielding@sar baselines]$ ls
20190718_20190730  20190718_20190916  20190718_20191115  20190718_20200114  20191221_20200126
20190718_20190811  20190718_20190928  20190718_20191127  20190718_20200126
20190718_20190823  20190718_20191010  20190718_20191209  20190718_20200207
20190718_20190829  20190718_20191022  20190718_20191221  20191221_20200102
20190718_20190904  20190718_20191103  20190718_20200102  20191221_20200114
```

**Full error message**

```
******************** step - load_data ********************
load_data.py --template /u/sar-r2/fielding/Puerto_Rico/S1AB/D098/seismic/MintPy_v1/smallbaselineApp.cfg /u/sar-r2/fielding/Puerto_Rico/S1AB/D098/seismic/MintPy_v1/PuertoRicoSenD098.txt --project PuertoRicoSenD098
SAR platform/sensor : Sen
processor: isce
--------------------------------------------------
prepare metadata files for isce products
prep_isce.py -m ../master/IW1.xml -g ../merged/geom_master -b ../baselines  -i ../merged/interferograms -f filt_*.unw
['../master/data.rsc'] exists and is newer than ['../master/IW1.xml'] --> skip.
prepare .rsc file for geometry files
read perp baseline time-series from ../baselines
prepare .rsc file for  filt_*.unw
Traceback (most recent call last):
  File "/home/fielding/tools/MintPy/mintpy/prep_isce.py", line 493, in <module>
    main()
  File "/home/fielding/tools/MintPy/mintpy/prep_isce.py", line 485, in main
    update_mode=inps.update_mode)
  File "/home/fielding/tools/MintPy/mintpy/prep_isce.py", line 444, in prepare_stack
    ifg_metadata = add_ifgram_metadata(ifg_metadata, dates, baseline_dict)
  File "/home/fielding/tools/MintPy/mintpy/prep_isce.py", line 346, in add_ifgram_metadata
    bperp_top = baseline_dict[dates[1]][0] - baseline_dict[dates[0]][0]
KeyError: '20190718'
```

**System information**

* Operating system: Linux
* Version of Python and relevant dependencies if applicable: Python 3.7.6
* Version of MintPy (output of `smallbaselineApp.py -v`):          MintPy v1.2.0-9, 2020-02-05

**Comment by EJFielding** [comment]
The workaround was to move the baseline files with the December reference to an "old" directory.

**Comment by yunjunz** [comment]
Hi @EJFielding, now only the baseline files with the most common reference date are used, all the other files with other reference files are ignored.

**Comment by EJFielding** [comment]
Thanks for the quick fix @yunjunz .
