### ISSUE TITLE
Simple TS inversion for roi_pac like case

### ISSUE THREAD

**Issue by prlundgren** [insarlab/MintPy#278]
I am a new mintpy user (have it working for ARIA S1 standard products) and I have some ALOS-2 processed, and dumped in a single directory of gocoded unwrapped interferograms and coherence files, each with a roi_pac like *.rsc file. The file names include the dates. So I have used GIAnT to process these but I want to switch to mintpy. When I try running with a simple input *.txt file:
smallbaselineApp.py DOMUYO_ALOS2_A34.txt

I get the following error (its doesn't know the sensor):
```
--RUN-at-2020-02-11 14:20:37.315811--
Run routine processing with smallbaselineApp.py on steps: ['load_data', 'modify_network', 'reference_point', 'correct_unwrap_error', 'stack_interferograms', 'invert_network', 'correct_LOD', 'correct_troposphere', 'deramp', 'correct_topography', 'residual_RMS', 'reference_date', 'velocity', 'geocode', 'google_earth', 'hdfeos5']
--------------------------------------------------
Project name: DOMUYO_ALOS2_A34
Go to work directory: /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/mintpy_1
read custom template file: /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/mintpy_1/DOMUYO_ALOS2_A34.txt
update default template based on input custom template
read default template file: /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/mintpy_1/smallbaselineApp.cfg


******************** step - load_data ********************
load_data.py --template /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/mintpy_1/smallbaselineApp.cfg /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/mintpy_1/DOMUYO_ALOS2_A34.txt --project DOMUYO_ALOS2_A34
Traceback (most recent call last):
  File "/u/pez-z1/paul/python/MintPy/mintpy/smallbaselineApp.py", line 1090, in <module>
    main()
  File "/u/pez-z1/paul/python/MintPy/mintpy/smallbaselineApp.py", line 1080, in main
    app.run(steps=inps.runSteps, plot=inps.plot)
  File "/u/pez-z1/paul/python/MintPy/mintpy/smallbaselineApp.py", line 1009, in run
    self.run_load_data(sname)
  File "/u/pez-z1/paul/python/MintPy/mintpy/smallbaselineApp.py", line 368, in run_load_data
    mintpy.load_data.main(scp_args.split())
  File "/u/pez-z1/paul/python/MintPy/mintpy/load_data.py", line 624, in main
    inpsDict = read_inps2dict(inps)
  File "/u/pez-z1/paul/python/MintPy/mintpy/load_data.py", line 190, in read_inps2dict
    inpsDict['PLATFORM'] = str(sensor.project_name2sensor_name(str(inpsDict['PROJECT_NAME']))[0])
  File "/u/pez-z1/paul/python/MintPy/mintpy/objects/sensor.py", line 162, in project_name2sensor_name
    sensor = [s for s in sensor if s in proj_name][0]
IndexError: list index out of range
```

Here is the input file:
```
> more DOMUYO_ALOS2_A34.txt
# vim: set filetype=cfg:
##-------------------------------- MintPy -----------------------------##
mintpy.reference.lalo        = auto #14.100,120.938  #PTGY station

mintpy.deramp                = no  #[no / linear / quadratic], auto for no - no ramp will be removed
mintpy.topographicResidual   = no  #[yes / no], auto for yesmintpy.troposphericDelay.method = no

mintpy.troposphericDelay.method = no  #[pyaps / height_correlation / no], auto for pyaps

mintpy.network.coherenceBased            = yes

mintpy.network.minCoherence    = 0.7

mintpy.network.aoiLALO         = -36.659:-36.560,-70.490:-70.370  #[lat0:lat1,lon0:lon1 / no], auto for no - use the whole area

mintpy.load.processor      = roipac  #[isce,roipac,gamma,], auto for isce
mintpy.load.updateMode     = auto  #[yes / no], auto for yes, skip re-loading if HDF5 files are complete
mintpy.load.compression    = auto  #[gzip / lzf / no], auto for no [recommended].
##---------interferogram datasets:
mintpy.load.unwFile        = /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/DATA/geo*_msk_cut.unw
mintpy.load.corFile        = /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/DATA/geo*_cut.cor
```

**Comment by yunjunz** [comment]
Hi @prlundgren, thank you for pointing out this bug. It should be fixed now.
