### ISSUE TITLE
Problem generating baseline plot with pseudo-roi_pac mintpy run

### ISSUE THREAD

**Issue by prlundgren** [insarlab/MintPy#281]
I don't know if it is because all the baselines are 0 or the Btemp are negative (i'm not sure how robust is the code - if all Bperp are zero the code should just alternate their "Bperp" locations by date in order to produce a visible plot. 

```
(MintPy) tiger mintpy_1) smallbaselineApp.py DOMUYO_ALOS2_A34.txt

_________________________________________________
 ____    ____   _            _   _______          
|_   \  /   _| (_)          / |_|_   __ \         
  |   \/   |   __   _ .--. `| |-' | |__) |_   __  
  | |\  /| |  [  | [ `.-. | | |   |  ___/[ \ [  ] 
 _| |_\/_| |_  | |  | | | | | |, _| |_    \ '/ /  
|_____||_____|[___][___||__]\__/|_____| [\_:  /   
                                         \__.'    

   Miami InSAR Time-series software in Python  
          MintPy v1.2.0-19, 2020-02-12
_________________________________________________

--RUN-at-2020-02-14 10:29:50.720435--
Run routine processing with smallbaselineApp.py on steps: ['load_data', 'modify_network', 'reference_point', 'correct_unwrap_error', 'stack_interferograms', 'invert_network', 'correct_LOD', 'correct_troposphere', 'deramp', 'correct_topography', 'residual_RMS', 'reference_date', 'velocity', 'geocode', 'google_earth', 'hdfeos5']
--------------------------------------------------
Project name: DOMUYO_ALOS2_A34
Go to work directory: /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/mintpy_1
copy default template file /u/pez-z1/paul/python/MintPy/mintpy/defaults/smallbaselineApp.cfg to work directory
read custom template file: /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/mintpy_1/DOMUYO_ALOS2_A34.txt
update default template based on input custom template
    mintpy.load.processor: auto --> roipac
    mintpy.load.unwFile: auto --> /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/DATA/geo*_msk-ramp_cut.unw
    mintpy.load.corFile: auto --> /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/DATA/geo*_cut.cor
    mintpy.load.demFile: auto --> /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/DATA/geo_190331-180401_4rlks_4alks_cut.hgt
    mintpy.network.coherenceBased: auto --> yes
    mintpy.network.minCoherence: auto --> 0.1
    mintpy.network.aoiLALO: auto --> no
    mintpy.troposphericDelay.method: auto --> no
    mintpy.deramp: auto --> no
    mintpy.topographicResidual: auto --> no
create directory: /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/mintpy_1/inputs
copy DOMUYO_ALOS2_A34.txt to inputs directory for backup.
copy smallbaselineApp.cfg to inputs directory for backup.
create directory: /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/mintpy_1/pic
copy DOMUYO_ALOS2_A34.txt to pic directory for backup.
copy smallbaselineApp.cfg to pic directory for backup.
read default template file: /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/mintpy_1/smallbaselineApp.cfg


******************** step - load_data ********************
load_data.py --template /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/mintpy_1/smallbaselineApp.cfg /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/mintpy_1/DOMUYO_ALOS2_A34.txt --project DOMUYO_ALOS2_A34
SAR platform/sensor : Alos2
processor: roipac
--------------------------------------------------
prepare metadata files for roipac products
prep_roipac.py /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/DATA/geo*_msk-ramp_cut.unw
prep_roipac.py /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/DATA/geo*_cut.cor
prep_roipac.py /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/DATA/geo_190331-180401_4rlks_4alks_cut.hgt
--------------------------------------------------
searching interferometric pairs info
input data files:
unwrapPhase     : /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/DATA/geo*_msk-ramp_cut.unw
coherence       : /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/DATA/geo*_cut.cor
number of unwrapPhase     : 17
number of coherence       : 17
--------------------------------------------------
searching geometry files info
input data files:
height          : /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/DATA/geo_190331-180401_4rlks_4alks_cut.hgt
--------------------------------------------------
updateMode : True
compression: None
--------------------------------------------------
create HDF5 file /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/mintpy_1/inputs/ifgramStack.h5 with w mode
create dataset /unwrapPhase of <class 'numpy.float32'>   in size of (17, 1439, 1620) with compression = None
[==================================================] 20200119_20190331    0s /     0s
create dataset /coherence   of <class 'numpy.float32'>   in size of (17, 1439, 1620) with compression = None
[==================================================] 20200119_20190331    0s /     0s
create dataset /date        of <class 'numpy.bytes_'>    in size of (17, 2)
create dataset /bperp       of <class 'numpy.float32'>   in size of (17,)
create dataset /dropIfgram  of <class 'numpy.bool_'>     in size of (17,)
add extra metadata: {'PROJECT_NAME': 'DOMUYO_ALOS2_A34', 'PLATFORM': 'Alos2'}
Finished writing to /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/mintpy_1/inputs/ifgramStack.h5
--------------------------------------------------
create HDF5 file /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/mintpy_1/inputs/geometryGeo.h5 with w mode
create dataset /height             of <class 'numpy.float32'>   in size of (1439, 1620) with compression = lzf
Finished writing to /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/mintpy_1/inputs/geometryGeo.h5
No lookup table info range/lat found in files.
Input data seems to be geocoded. Lookup file not needed.
Loaded dataset are processed by InSAR software: roipac
Loaded dataset is in GEO coordinates
Interferograms Stack: /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/mintpy_1/inputs/ifgramStack.h5
Geometry File       : /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/mintpy_1/inputs/geometryGeo.h5
Lookup Table File   : None
--------------------------------------------------
All data needed found/loaded/copied. Processed 2-pass InSAR data can be removed.
--------------------------------------------------
updating ifgramStack.h5, geometryGeo.h5 metadata based on custom template file: DOMUYO_ALOS2_A34.txt


******************** step - modify_network ********************
Input data seems to be geocoded. Lookup file not needed.
modify_network.py /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/mintpy_1/inputs/ifgramStack.h5 -t /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/mintpy_1/smallbaselineApp.cfg
No lookup table info range/lat found in files.
read options from template file: smallbaselineApp.cfg
open ifgramStack file: ifgramStack.h5
number of interferograms: 17
--------------------------------------------------
use coherence-based network modification
calculating spatial average of coherence in file /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/mintpy_1/inputs/ifgramStack.h5 ...
reading interferogram 17/17 ...
write average value in space into text file: ifgramStack_coherence_spatialAvg.txt
Get minimum spanning tree (MST) of interferograms with inverse of coherence.
Drop ifgrams with 1) average coherence < 0.1 AND 2) not in MST network: (0)
[]
--------------------------------------------------
number of interferograms to remove: 0
number of interferograms to keep  : 17
Calculated date12 to drop is the same as exsiting marked input file, skip updating file.

plot_network.py /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/mintpy_1/inputs/ifgramStack.h5 -t /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/mintpy_1/smallbaselineApp.cfg --nodisplay
read options from template file: smallbaselineApp.cfg
read temporal/spatial baseline info from file: /u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/mintpy_1/inputs/ifgramStack.h5
['ifgramStack_coherence_spatialAvg.txt'] exists and is newer than ['/u/puma-r0/paul/CHILLAN/ALOS2/A034/TS/mintpy_1/inputs/ifgramStack.h5'] --> skip.
ifgramStack_coherence_spatialAvg.txt already exists, read it directly
number of acquisitions: 11
number of interferograms: 17
--------------------------------------------------
number of interferograms marked as drop: 0
number of interferograms marked as keep: 17
number of acquisitions marked as drop: 0
Traceback (most recent call last):
  File "/u/pez-z1/paul/python/MintPy/mintpy/smallbaselineApp.py", line 1090, in <module>
    main()
  File "/u/pez-z1/paul/python/MintPy/mintpy/smallbaselineApp.py", line 1080, in main
    app.run(steps=inps.runSteps, plot=inps.plot)
  File "/u/pez-z1/paul/python/MintPy/mintpy/smallbaselineApp.py", line 1012, in run
    self.run_network_modification(sname)
  File "/u/pez-z1/paul/python/MintPy/mintpy/smallbaselineApp.py", line 457, in run_network_modification
    mintpy.plot_network.main(scp_args.split())
  File "/u/pez-z1/paul/python/MintPy/mintpy/plot_network.py", line 218, in main
    inps = cmd_line_parse(iargs)
  File "/u/pez-z1/paul/python/MintPy/mintpy/plot_network.py", line 142, in cmd_line_parse
    inps.colormap = pp.ColormapExt(inps.cmap_name, vlist=inps.cmap_vlist).colormap
  File "/u/pez-z1/paul/python/MintPy/mintpy/objects/colors.py", line 101, in __init__
    self.get_colormap()
  File "/u/pez-z1/paul/python/MintPy/mintpy/objects/colors.py", line 163, in get_colormap
    colors1 = self.colormap(np.linspace(0.0, 0.3, n1))
  File "<__array_function__ internals>", line 6, in linspace
  File "/u/pez-z1/paul/python/miniconda3/envs/MintPy/lib/python3.6/site-packages/numpy/core/function_base.py", line 124, in linspace
    raise ValueError("Number of samples, %s, must be non-negative." % num)
ValueError: Number of samples, -320, must be non-negative.


(MintPy) tiger mintpy_1) more ifgramStack_coherence_spatialAvg.txt
# Data file: ifgramStack.h5
# Mask file: None
# AOI box: (0, 0, 1620, 1439)
#	DATE12		Mean	Btemp/days	Bperp/m		Num
20161127_20160207	0.5190	    -294	     0.0	0
20170205_20160207	0.4960	    -364	     0.0	1
20171112_20150208	0.3000	   -1008	     0.0	2
20171112_20160207	0.3782	    -644	     0.0	3
20171112_20170205	0.3429	    -280	     0.0	4
20180121_20150208	0.3307	   -1078	     0.0	5
20180121_20170205	0.4570	    -350	     0.0	6
20180401_20150208	0.4026	   -1148	     0.0	7
20180401_20160207	0.4100	    -784	     0.0	8
20180401_20170205	0.4793	    -420	     0.0	9
20190217_20150208	0.3736	   -1470	     0.0	10
20190217_20160207	0.4007	   -1106	     0.0	11
20190217_20180401	0.4734	    -322	     0.0	12
20190331_20190217	0.5160	     -42	     0.0	13
20200105_20190217	0.4968	    -322	     0.0	14
20200105_20190331	0.4731	    -280	     0.0	15
20200119_20190331	0.5310	    -294	     0.0	16
(MintPy) tiger mintpy_1) 
```

**Comment by yunjunz** [comment]
Hi @prlundgren, now you could use `smallbaselineApp.py --noplot` or `mintpy.plot = no` to skip plotting the network. However, this will also skip plotting all the other files.

Perpendicular files (*_baseline.rsc) are required for topographic residual correction, which is not trivia in my limited experience with ALOS-2, thus, I recommend you to have it imported if it's possible. you could take a look at the Kuju example dataset for reference.

**Comment by prlundgren** [comment]
Thanks Yunjun. I did create pseudo _baseline.rsc files for each pair based on actual roi_pac files.

I’ll give the new version a try.

Thanks, Paul

Sent from my iPhone

On Feb 17, 2020, at 4:32 PM, Zhang Yunjun <notifications@github.com> wrote:

﻿

Hi @prlundgren<https://github.com/prlundgren>, now you could use smallbaselineApp.py --noplot or mintpy.plot = no to skip plotting the network. However, this will also skip plotting all the other files.

Perpendicular files (*_baseline.rsc) are required for topographic residual correction, which is not trivia in my limited experience with ALOS-2, thus, I recommend you to have it imported if it's possible. you could take a look at the Kuju example dataset for reference.
