### ISSUE TITLE
404 when downloading GPS for certain study area

### ISSUE THREAD

**Issue by sssangha** [insarlab/MintPy#285]
**Description of the problem**
When trying to validate the InSAR velocity over a Californian track with GPS (SNWE bounding box = 34.9855018, 41.9953313, -124.8713548,- 120.4743248), the "view.py" script errors out with a 404 error. Generation of the "GPSSitesVel.csv" ends after appending the velocity for the same station "CASR", so it is my impression that there is a problem associated with the next station in the network "CASS". 

**Full script that generated the error**

```
view.py velocity.h5 velocity --show-gps --gps-comp enu2los --gps-label
```

**Full error message**

```
calculating GPS velocity with respect to None in enu2los direction ...
start date: 20150524
end   date: 20191111
use incidenceAngle/azimuthAngle from file: geometryGeo.h5
[===>                     9%                       ] CASR    4s /    48sTraceback (most recent call last):
  File "/u/leffe0/ssangha/tools/conda_installation/stable_feb9_2020/MintPy/mintpy/view.py", line 1412, in <module>
    main(sys.argv[1:])
  File "/u/leffe0/ssangha/tools/conda_installation/stable_feb9_2020/MintPy/mintpy/view.py", line 1406, in main
    obj.plot()
  File "/u/leffe0/ssangha/tools/conda_installation/stable_feb9_2020/MintPy/mintpy/view.py", line 1368, in plot
    ax, self, im, cbar = plot_slice(ax, data, self.atr, self)
  File "/u/leffe0/ssangha/tools/conda_installation/stable_feb9_2020/MintPy/mintpy/view.py", line 498, in plot_slice
    ax = pp.plot_gps(ax, SNWE, inps, metadata, print_msg=inps.print_msg)
  File "/u/leffe0/ssangha/tools/conda_installation/stable_feb9_2020/MintPy/mintpy/utils/plot.py", line 1268, in plot_gps
    gps_comp=inps.gps_component) * unit_fac
  File "/u/leffe0/ssangha/tools/conda_installation/stable_feb9_2020/MintPy/mintpy/objects/gps.py", line 392, in get_gps_los_velocity
    gps_comp=gps_comp)[0:2]
  File "/u/leffe0/ssangha/tools/conda_installation/stable_feb9_2020/MintPy/mintpy/objects/gps.py", line 359, in read_gps_los_displacement
    inc_angle, head_angle = self.get_los_geometry(geom_obj)
  File "/u/leffe0/ssangha/tools/conda_installation/stable_feb9_2020/MintPy/mintpy/objects/gps.py", line 320, in get_los_geometry
    lat, lon = self.get_stat_lat_lon(print_msg=print_msg)
  File "/u/leffe0/ssangha/tools/conda_installation/stable_feb9_2020/MintPy/mintpy/objects/gps.py", line 213, in get_stat_lat_lon
    self.dload_site(print_msg=print_msg)
  File "/u/leffe0/ssangha/tools/conda_installation/stable_feb9_2020/MintPy/mintpy/objects/gps.py", line 196, in dload_site
    urlretrieve(url, self.file)
  File "/u/leffe0/ssangha/tools/conda_installation/stable_feb9_2020/envs/mintpy/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/u/leffe0/ssangha/tools/conda_installation/stable_feb9_2020/envs/mintpy/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/u/leffe0/ssangha/tools/conda_installation/stable_feb9_2020/envs/mintpy/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/u/leffe0/ssangha/tools/conda_installation/stable_feb9_2020/envs/mintpy/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/u/leffe0/ssangha/tools/conda_installation/stable_feb9_2020/envs/mintpy/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/u/leffe0/ssangha/tools/conda_installation/stable_feb9_2020/envs/mintpy/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/u/leffe0/ssangha/tools/conda_installation/stable_feb9_2020/envs/mintpy/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs
```

**System information**

* Operating system:
* Version of Python and relevant dependencies if applicable
* Version of MintPy (output of `smallbaselineApp.py -v`):

**Comment by yunjunz** [comment]
Hi @sssangha, I would agree with you. It should be a simple fix to ignore this type of station. Could you send me your velocity.h5 file for me to test it? My email is yunjunzgeo@gmail.com.

**Comment by yunjunz** [comment]
Hi @sssangha, UNR has changed the default GPS solution reference from IGS08 to IGS14. The latter now has more data than IGS08, which caused the error you have. I have updated the code to use IGS14 solution by default.

Here is the result with the command below using the velocity file you sent me: everything looks normal now. Although I would recommend you add `--ref-gps` option to make the GPS velocity more consistent with InSAR.

```
view.py velocity.h5 velocity --show-gps --gps-comp enu2los
```

<img width="711" alt="Screen Shot 2020-02-27 at 5 24 31 PM" src="https://user-images.githubusercontent.com/13143710/75502159-de66f300-5986-11ea-93a3-b7c635ae1201.png">
