### ISSUE TITLE
dask LocalCluster fails using more than 17 workers

### ISSUE THREAD

**Issue by falkamelung** [insarlab/MintPy#375]
Hi Josh, I hope you have some ideas on this one. Let me know If I can do some more quick debugging.

On Stampede dask LocalCluster fails  for `--num-worker all`. To be more precise, it works for `--num-worker 17` but fails for --num-worker 18` . The commands I ran and error messages are below.

This is a relatively big data sets (ifgramStack is 25 GB). I thought this would be a memory issue but it does not use much memory (for --num-worker 17):
```
//c506-044/scratch/05861/tg851601/KermanshahSenAT72/mintpy[1003] free -g
              total        used        free      shared  buff/cache   available
Mem:            187           4         174           0           7         175
Swap:             0           0           0
```
The dataset is available (later today) using:
```
wget -r -nH --cut-dirs=2 --no-parent --reject="index.html*" --no-check-certificate https://129.114.104.223/data/HDF5EOS/KermanshahSenAT72/mintpy
```

This command works fine:
```
ifgram_inversion.py /scratch/05861/tg851601/KermanshahSenAT72/mintpy/inputs/ifgramStack.h5  --cluster local --num-worker 16 
```

Using more workers give the error:
```
 ifgram_inversion.py /scratch/05861/tg851601/KermanshahSenAT72/mintpy/inputs/ifgramStack.h5  --cluster local --num-worker 18

use dataset "unwrapPhase" by default
reference pixel in y/x: (966, 1364) from dataset: unwrapPhase
-------------------------------------------------------------------------------
least-squares solution with L2 min-norm on: deformation velocity
minimum redundancy: 1.0
weight function: var
mask: no
-------------------------------------------------------------------------------
number of interferograms: 63
number of acquisitions  : 23
number of lines   : 2899
number of columns : 2291
--------------------------------------------------
create HDF5 file timeseries.h5 with w mode
create dataset: date                      of |S8                       in size of (23,)
create dataset: bperp                     of <class 'numpy.float32'>   in size of (23,)
create dataset: timeseries                of <class 'numpy.float32'>   in size of (23, 2899, 2291)
close HDF5 file timeseries.h5
--------------------------------------------------
open  HDF5 file timeseries.h5 in a mode
writing dataset /date                      block: [0, 23]
close HDF5 file timeseries.h5.
--------------------------------------------------
open  HDF5 file timeseries.h5 in a mode
writing dataset /bperp                     block: [0, 23]
close HDF5 file timeseries.h5.
--------------------------------------------------
create HDF5 file temporalCoherence.h5 with w mode
create dataset: temporalCoherence         of <class 'numpy.float32'>   in size of (2899, 2291)
close  HDF5 file temporalCoherence.h5
--------------------------------------------------
create HDF5 file numInvIfgram.h5 with w mode
create dataset: mask                      of <class 'numpy.float32'>   in size of (2899, 2291)
close  HDF5 file numInvIfgram.h5
maximum memory size: 2.0E+00 GB
split 2899 lines into 29 patches for processing
    with each patch up to 100 lines

------- processing patch 1 out of 29 --------------
box width:  2291
box length: 100


------- start parallel processing using Dask -------
input Dask cluster type: local
initiate Dask cluster
scale the cluster to 18 workers
initiate Dask client
split patch into 18 sub boxes in x direction for workers to process
submit a job to the worker for sub box 0: [0, 0, 127, 100]
submit a job to the worker for sub box 1: [127, 0, 254, 100]
submit a job to the worker for sub box 2: [254, 0, 381, 100]
submit a job to the worker for sub box 3: [381, 0, 509, 100]
submit a job to the worker for sub box 4: [509, 0, 636, 100]
submit a job to the worker for sub box 5: [636, 0, 763, 100]
submit a job to the worker for sub box 6: [763, 0, 890, 100]
submit a job to the worker for sub box 7: [890, 0, 1018, 100]
submit a job to the worker for sub box 8: [1018, 0, 1145, 100]
submit a job to the worker for sub box 9: [1145, 0, 1272, 100]
submit a job to the worker for sub box 10: [1272, 0, 1400, 100]
submit a job to the worker for sub box 11: [1400, 0, 1527, 100]
submit a job to the worker for sub box 12: [1527, 0, 1654, 100]
submit a job to the worker for sub box 13: [1654, 0, 1781, 100]
submit a job to the worker for sub box 14: [1781, 0, 1909, 100]
submit a job to the worker for sub box 15: [1909, 0, 2036, 100]
submit a job to the worker for sub box 16: [2036, 0, 2163, 100]
submit a job to the worker for sub box 17: [2163, 0, 2291, 100]
reading coherence in [0, 0, 127, 100] * 63 ...
reading coherence in [636, 0, 763, 100] * 63 ...
reading coherence in [1145, 0, 1272, 100] * 63 ...
reading coherence in [509, 0, 636, 100] * 63 ...
reading coherence in [1018, 0, 1145, 100] * 63 ...
reading coherence in [381, 0, 509, 100] * 63 ...
reading coherence in [127, 0, 254, 100] * 63 ...
reading coherence in [1272, 0, 1400, 100] * 63 ...
reading coherence in [254, 0, 381, 100] * 63 ...
reading coherence in [890, 0, 1018, 100] * 63 ...
reading coherence in [1400, 0, 1527, 100] * 63 ...
reading coherence in [1781, 0, 1909, 100] * 63 ...
reading coherence in [2163, 0, 2291, 100] * 63 ...
reading coherence in [1909, 0, 2036, 100] * 63 ...
reading coherence in [1654, 0, 1781, 100] * 63 ...
reading coherence in [1527, 0, 1654, 100] * 63 ...
reading coherence in [2036, 0, 2163, 100] * 63 ...
reading coherence in [763, 0, 890, 100] * 63 ...
convert coherence to weight in chunks of 100000 pixels: 1 chunks in total ...
convert coherence to weight using inverse of phase variance
    with phase PDF for distributed scatterers from Tough et al. (1995)
    number of looks L=147, use L=80 to avoid dividing by 0 in calculation with negligible effect
convert coherence to weight in chunks of 100000 pixels: 1 chunks in total ...
convert coherence to weight in chunks of 100000 pixels: 1 chunks in total ...
convert coherence to weight in chunks of 100000 pixels: 1 chunks in total ...
convert coherence to weight in chunks of 100000 pixels: 1 chunks in total ...
convert coherence to weight in chunks of 100000 pixels: 1 chunks in total ...
convert coherence to weight in chunks of 100000 pixels: 1 chunks in total ...
convert coherence to weight in chunks of 100000 pixels: 1 chunks in total ...
convert coherence to weight using inverse of phase variance
    with phase PDF for distributed scatterers from Tough et al. (1995)
    number of looks L=147, use L=80 to avoid dividing by 0 in calculation with negligible effect
convert coherence to weight using inverse of phase variance
    with phase PDF for distributed scatterers from Tough et al. (1995)
    number of looks L=147, use L=80 to avoid dividing by 0 in calculation with negligible effect
convert coherence to weight using inverse of phase variance
convert coherence to weight using inverse of phase variance
convert coherence to weight using inverse of phase variance
    with phase PDF for distributed scatterers from Tough et al. (1995)
    with phase PDF for distributed scatterers from Tough et al. (1995)
    with phase PDF for distributed scatterers from Tough et al. (1995)
    number of looks L=147, use L=80 to avoid dividing by 0 in calculation with negligible effect
    number of looks L=147, use L=80 to avoid dividing by 0 in calculation with negligible effect
    number of looks L=147, use L=80 to avoid dividing by 0 in calculation with negligible effect
convert coherence to weight using inverse of phase variance
    with phase PDF for distributed scatterers from Tough et al. (1995)
convert coherence to weight in chunks of 100000 pixels: 1 chunks in total ...
    number of looks L=147, use L=80 to avoid dividing by 0 in calculation with negligible effect
convert coherence to weight in chunks of 100000 pixels: 1 chunks in total ...
convert coherence to weight using inverse of phase variance
    with phase PDF for distributed scatterers from Tough et al. (1995)
    number of looks L=147, use L=80 to avoid dividing by 0 in calculation with negligible effect
convert coherence to weight using inverse of phase variance
    with phase PDF for distributed scatterers from Tough et al. (1995)
    number of looks L=147, use L=80 to avoid dividing by 0 in calculation with negligible effect
convert coherence to weight in chunks of 100000 pixels: 1 chunks in total ...
convert coherence to weight using inverse of phase variance
    with phase PDF for distributed scatterers from Tough et al. (1995)
    number of looks L=147, use L=80 to avoid dividing by 0 in calculation with negligible effect
convert coherence to weight in chunks of 100000 pixels: 1 chunks in total ...
convert coherence to weight in chunks of 100000 pixels: 1 chunks in total ...
convert coherence to weight using inverse of phase variance
    with phase PDF for distributed scatterers from Tough et al. (1995)
    number of looks L=147, use L=80 to avoid dividing by 0 in calculation with negligible effect
convert coherence to weight using inverse of phase variance
    with phase PDF for distributed scatterers from Tough et al. (1995)
    number of looks L=147, use L=80 to avoid dividing by 0 in calculation with negligible effect
convert coherence to weight in chunks of 100000 pixels: 1 chunks in total ...
convert coherence to weight in chunks of 100000 pixels: 1 chunks in total ...
convert coherence to weight using inverse of phase variance
    with phase PDF for distributed scatterers from Tough et al. (1995)
    number of looks L=147, use L=80 to avoid dividing by 0 in calculation with negligible effect
convert coherence to weight in chunks of 100000 pixels: 1 chunks in total ...
convert coherence to weight using inverse of phase variance
    with phase PDF for distributed scatterers from Tough et al. (1995)
    number of looks L=147, use L=80 to avoid dividing by 0 in calculation with negligible effect
convert coherence to weight using inverse of phase variance
    with phase PDF for distributed scatterers from Tough et al. (1995)
    number of looks L=147, use L=80 to avoid dividing by 0 in calculation with negligible effect
convert coherence to weight using inverse of phase variance
    with phase PDF for distributed scatterers from Tough et al. (1995)
    number of looks L=147, use L=80 to avoid dividing by 0 in calculation with negligible effect
convert coherence to weight in chunks of 100000 pixels: 1 chunks in total ...
convert coherence to weight using inverse of phase variance
    with phase PDF for distributed scatterers from Tough et al. (1995)
    number of looks L=147, use L=80 to avoid dividing by 0 in calculation with negligible effect
convert coherence to weight in chunks of 100000 pixels: 1 chunks in total ...
convert coherence to weight using inverse of phase variance
    with phase PDF for distributed scatterers from Tough et al. (1995)
    number of looks L=147, use L=80 to avoid dividing by 0 in calculation with negligible effect
chunk 1 / 1
reading unwrapPhase in [1272, 0, 1400, 100] * 63 ...
chunk 1 / 1
reading unwrapPhase in [1781, 0, 1909, 100] * 63 ...
chunk 1 / 1
reading unwrapPhase in [1400, 0, 1527, 100] * 63 ...
chunk 1 / 1
reading unwrapPhase in [254, 0, 381, 100] * 63 ...
use input reference phase
skip pixels with zero/nan value in all interferograms
number of pixels to invert: 12800 out of 12800 (100.0%)
inverting network of interferograms into time-series ...
chunk 1 / 1
reading unwrapPhase in [2036, 0, 2163, 100] * 63 ...
use input reference phase
skip pixels with zero/nan value in all interferograms
number of pixels to invert: 12800 out of 12800 (100.0%)
inverting network of interferograms into time-series ...
use input reference phase
skip pixels with zero/nan value in all interferograms
number of pixels to invert: 12700 out of 12700 (100.0%)
inverting network of interferograms into time-series ...
chunk 1 / 1
reading unwrapPhase in [0, 0, 127, 100] * 63 ...
chunk 1 / 1
reading unwrapPhase in [1909, 0, 2036, 100] * 63 ...
use input reference phase
skip pixels with zero/nan value in all interferograms
number of pixels to invert: 12700 out of 12700 (100.0%)
inverting network of interferograms into time-series ...
use input reference phase
skip pixels with zero/nan value in all interferograms
number of pixels to invert: 12700 out of 12700 (100.0%)
inverting network of interferograms into time-series ...
[=======>                16%                       ] 2000/12700 pixels    0s /     0suse input reference phase
skip pixels with zero/nan value in all interferograms
use input reference phase
chunk 1 / 1
number of pixels to invert: 0 out of 12700 (0.0%)
reading unwrapPhase in [636, 0, 763, 100] * 63 ...
skip pixels with zero/nan value in all interferograms
number of pixels to invert: 12700 out of 12700 (100.0%)
inverting network of interferograms into time-series ...
FUTURE #1 complete. Time used: 6 seconds
Traceback (most recent call last):
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/sources/MintPy/mintpy/ifgram_inversion.py", line 1143, in <module>
    main()
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/sources/MintPy/mintpy/ifgram_inversion.py", line 1132, in main
    ifgram_inversion(inps)
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/sources/MintPy/mintpy/ifgram_inversion.py", line 1068, in ifgram_inversion
    results=[ts, temp_coh, num_inv_ifg])
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/sources/MintPy/mintpy/objects/cluster.py", line 147, in run
    return self.collect_result(futures, results, box, submission_time)
  File "/work/05861/tg851601/stampede2/test/dev2/rsmas_insar/sources/MintPy/mintpy/objects/cluster.py", line 205, in collect_result
    x0, y0, x1, y1 = sub_box
ValueError: too many values to unpack (expected 4)


```

**Comment by Ovec8hkin** [comment]
You say this works on 17 workers? Based on the trace it shouldn’t work for any number of workers. I can take a look at this, maybe tomorrow night, but more likely this weekend.

**Comment by yunjunz** [comment]
Close this issue since it has not been properly identified and followed.

**Comment by falkamelung** [comment]
But closing an issue does not remove the bug

**Comment by yunjunz** [comment]
This issue seems like the same as https://github.com/insarlab/MintPy/issues/398, which has been fixed.
