### ISSUE TITLE
invert_network fails when data does not cover full area

### ISSUE THREAD

**Issue by EJFielding** [insarlab/MintPy#398]
**Description of the problem**

I  was trying to process some ARIA standard data products for an area in Nepal. It seems that the data that I was able to download does not cover the whole area that I specified. The small `smallbaselineApp.py` processing went well until the `invert_network` step. When it reached a block with no data, it quit.

**Full script that generated the error**

```
smallbaselineApp.py NepalSenD019.txt
```

**Full error message**

```
******************** step - invert_network ********************
Input data seems to be geocoded. Lookup file not needed.
ifgram_inversion.py /Users/fielding/Google Drive (fielding@jpl.caltech.edu)/Tibet-Drive/ARIA-S1/Nepal_D019/MintPy/inputs/ifgramStack.h5 -t /Users/fielding/Google Drive (fielding@jpl.caltech.edu)/Tibet-Drive/ARIA-S1/Nepal_D019/MintPy/smallbaselineApp.cfg --update
use dataset "unwrapPhase" by default
--------------------------------------------------
update mode: ON
1) NOT ALL output files found: ['timeseries.h5', 'temporalCoherence.h5', 'numInvIfgram.h5'].
run or skip: run.
reference pixel in y/x: (6, 3435) from dataset: unwrapPhase
-------------------------------------------------------------------------------
least-squares solution with L2 min-norm on: deformation velocity
minimum redundancy: 1.0
weight function: no
mask: no
***WARNING: the network is NOT fully connected.
	Inversion result can be biased!
	Continue to use SVD to resolve the offset between different subsets.
-------------------------------------------------------------------------------
number of interferograms: 163
number of acquisitions  : 87
number of lines   : 3600
number of columns : 3600
--------------------------------------------------
create HDF5 file timeseries.h5 with w mode
create dataset: date                      of |S8                       in size of (87,)
create dataset: bperp                     of <class 'numpy.float32'>   in size of (87,)
create dataset: timeseries                of <class 'numpy.float32'>   in size of (87, 3600, 3600)
close HDF5 file timeseries.h5
--------------------------------------------------
open  HDF5 file timeseries.h5 in a mode
writing dataset /date                      block: [0, 87]
close HDF5 file timeseries.h5.
--------------------------------------------------
open  HDF5 file timeseries.h5 in a mode
writing dataset /bperp                     block: [0, 87]
close HDF5 file timeseries.h5.
--------------------------------------------------
create HDF5 file temporalCoherence.h5 with w mode
create dataset: temporalCoherence         of <class 'numpy.float32'>   in size of (3600, 3600)
close  HDF5 file temporalCoherence.h5
--------------------------------------------------
create HDF5 file numInvIfgram.h5 with w mode
create dataset: mask                      of <class 'numpy.float32'>   in size of (3600, 3600)
close  HDF5 file numInvIfgram.h5
maximum memory size: 2.0E+00 GB
split 3600 lines into 18 patches for processing
    with each patch up to 200 lines

------- processing patch 1 out of 18 --------------
box width:  3600
box length: 200
reading unwrapPhase in (0, 0, 3600, 200) * 163 ...
use input reference phase
skip pixels on water with mask from file: waterMask.h5
skip pixels with zero/nan value in all interferograms
number of pixels to invert: 614341 out of 720000 (85.3%)
inverting pixels with valid phase in all  ifgrams (5455 pixels) ...
calcualting temporal coherence in chunks of 1000 pixels: 6 chunks in total ...
chunk 1 / 6
chunk 2 / 6
chunk 3 / 6
chunk 4 / 6
chunk 5 / 6
chunk 6 / 6
inverting pixels with valid phase in some ifgrams (608886 pixels) ...
[==================================================] 608886/608886 pixels   38s /     0s
converting LOS phase unit from radian to meter
--------------------------------------------------
open  HDF5 file timeseries.h5 in a mode
writing dataset /timeseries                block: [0, 87, 0, 200, 0, 3600]
close HDF5 file timeseries.h5.
--------------------------------------------------
open  HDF5 file temporalCoherence.h5 in a mode
writing dataset /temporalCoherence         block: [0, 200, 0, 3600]
close HDF5 file temporalCoherence.h5.
--------------------------------------------------
open  HDF5 file numInvIfgram.h5 in a mode
writing dataset /mask                      block: [0, 200, 0, 3600]
close HDF5 file numInvIfgram.h5.
time used: 00 mins 43.3 secs.

...
------- processing patch 15 out of 18 --------------
box width:  3600
box length: 200
reading unwrapPhase in (0, 2800, 3600, 3000) * 163 ...
use input reference phase
skip pixels on water with mask from file: waterMask.h5
skip pixels with zero/nan value in all interferograms
number of pixels to invert: 8924 out of 720000 (1.2%)
inverting pixels with valid phase in some ifgrams (8924 pixels) ...
[==================================================] 8924/8924 pixels    0s /     0s
converting LOS phase unit from radian to meter
--------------------------------------------------
open  HDF5 file timeseries.h5 in a mode
writing dataset /timeseries                block: [0, 87, 2800, 3000, 0, 3600]
close HDF5 file timeseries.h5.
--------------------------------------------------
open  HDF5 file temporalCoherence.h5 in a mode
writing dataset /temporalCoherence         block: [2800, 3000, 0, 3600]
close HDF5 file temporalCoherence.h5.
--------------------------------------------------
open  HDF5 file numInvIfgram.h5 in a mode
writing dataset /mask                      block: [2800, 3000, 0, 3600]
close HDF5 file numInvIfgram.h5.
time used: 09 mins 12.8 secs.

------- processing patch 16 out of 18 --------------
box width:  3600
box length: 200
reading unwrapPhase in (0, 3000, 3600, 3200) * 163 ...
use input reference phase
skip pixels on water with mask from file: waterMask.h5
skip pixels with zero/nan value in all interferograms
number of pixels to invert: 0 out of 720000 (0.0%)
Traceback (most recent call last):
  File "/Users/fielding/tools/mintpy/mintpy/smallbaselineApp.py", line 1116, in <module>
    main()
  File "/Users/fielding/tools/mintpy/mintpy/smallbaselineApp.py", line 1106, in main
    app.run(steps=inps.runSteps, plot=inps.plot)
  File "/Users/fielding/tools/mintpy/mintpy/smallbaselineApp.py", line 1050, in run
    self.run_network_inversion(sname)
  File "/Users/fielding/tools/mintpy/mintpy/smallbaselineApp.py", line 580, in run_network_inversion
    mintpy.ifgram_inversion.main(iargs)
  File "/Users/fielding/tools/mintpy/mintpy/ifgram_inversion.py", line 1134, in main
    ifgram_inversion(inps)
  File "/Users/fielding/tools/mintpy/mintpy/ifgram_inversion.py", line 1052, in ifgram_inversion
    ts, temp_coh, num_inv_ifg = ifgram_inversion_patch(**data_kwargs)[:-1]
ValueError: not enough values to unpack (expected 3, got 2)

```

**System information**

* Operating system: macOS
* Python environment: conda
* Version of MintPy: MintPy release version v1.2.2-65, release date 2020-07-11
* Your custom / default template file (if the bug is related to a specific dataset): 
[NepalSenD019.txt](https://github.com/insarlab/MintPy/files/4907907/NepalSenD019.txt)

**Comment by EJFielding** [comment]
Here is the geometry plot, showing the lack of geometry in the southernmost part.
![unwrapPhase_wrap_1](https://user-images.githubusercontent.com/7253576/87237440-25d8a380-c3ab-11ea-8e92-9236664c82b7.png)

**Comment by EJFielding** [comment]
I ran the `ariaTSsetup.py` with a smaller area to avoid the region of no data. `ariaTSsetup.py -f 'products/*.nc' --bbox "26 28 83 86" -d download --mask download -w bbox26_28`. The processing failed again with a similar error.

```
******************** step - invert_network ********************
Input data seems to be geocoded. Lookup file not needed.
ifgram_inversion.py /Users/fielding/Google Drive (fielding@jpl.caltech.edu)/Tibet-Drive/ARIA-S1/Nepal_D019/bbox26_28/MintPy/inputs/ifgramStack.h5 -t /Users/fielding/Google Drive (fielding@jpl.caltech.edu)/Tibet-Drive/ARIA-S1/Nepal_D019/bbox26_28/MintPy/smallbaselineApp.cfg --update
use dataset "unwrapPhase" by default
--------------------------------------------------
update mode: ON
1) NOT ALL output files found: ['timeseries.h5', 'temporalCoherence.h5', 'numInvIfgram.h5'].
run or skip: run.
reference pixel in y/x: (6, 3438) from dataset: unwrapPhase
-------------------------------------------------------------------------------
least-squares solution with L2 min-norm on: deformation velocity
minimum redundancy: 1.0
weight function: no
mask: no
***WARNING: the network is NOT fully connected.
	Inversion result can be biased!
	Continue to use SVD to resolve the offset between different subsets.
-------------------------------------------------------------------------------
number of interferograms: 163
number of acquisitions  : 87
number of lines   : 2400
number of columns : 3600
--------------------------------------------------
create HDF5 file timeseries.h5 with w mode
create dataset: date                      of |S8                       in size of (87,)
create dataset: bperp                     of <class 'numpy.float32'>   in size of (87,)
create dataset: timeseries                of <class 'numpy.float32'>   in size of (87, 2400, 3600)
close HDF5 file timeseries.h5
--------------------------------------------------
open  HDF5 file timeseries.h5 in a mode
writing dataset /date                      block: [0, 87]
close HDF5 file timeseries.h5.
--------------------------------------------------
open  HDF5 file timeseries.h5 in a mode
writing dataset /bperp                     block: [0, 87]
close HDF5 file timeseries.h5.
--------------------------------------------------
create HDF5 file temporalCoherence.h5 with w mode
create dataset: temporalCoherence         of <class 'numpy.float32'>   in size of (2400, 3600)
close  HDF5 file temporalCoherence.h5
--------------------------------------------------
create HDF5 file numInvIfgram.h5 with w mode
create dataset: mask                      of <class 'numpy.float32'>   in size of (2400, 3600)
close  HDF5 file numInvIfgram.h5
maximum memory size: 2.0E+00 GB
split 2400 lines into 12 patches for processing
    with each patch up to 200 lines

------- processing patch 1 out of 12 --------------
box width:  3600
box length: 200
reading unwrapPhase in (0, 0, 3600, 200) * 163 ...
use input reference phase
skip pixels on water with mask from file: waterMask.h5
skip pixels with zero/nan value in all interferograms
number of pixels to invert: 6319 out of 720000 (0.9%)
inverting pixels with valid phase in all  ifgrams (5456 pixels) ...
calcualting temporal coherence in chunks of 1000 pixels: 6 chunks in total ...
chunk 1 / 6
chunk 2 / 6
chunk 3 / 6
chunk 4 / 6
chunk 5 / 6
chunk 6 / 6
inverting pixels with valid phase in some ifgrams (863 pixels) ...
[==================================================] 863/863 pixels
converting LOS phase unit from radian to meter
--------------------------------------------------
open  HDF5 file timeseries.h5 in a mode
writing dataset /timeseries                block: [0, 87, 0, 200, 0, 3600]
close HDF5 file timeseries.h5.
--------------------------------------------------
open  HDF5 file temporalCoherence.h5 in a mode
writing dataset /temporalCoherence         block: [0, 200, 0, 3600]
close HDF5 file temporalCoherence.h5.
--------------------------------------------------
open  HDF5 file numInvIfgram.h5 in a mode
writing dataset /mask                      block: [0, 200, 0, 3600]
close HDF5 file numInvIfgram.h5.
time used: 00 mins 4.0 secs.


------- processing patch 2 out of 12 --------------
box width:  3600
box length: 200
reading unwrapPhase in (0, 200, 3600, 400) * 163 ...
use input reference phase
skip pixels on water with mask from file: waterMask.h5
skip pixels with zero/nan value in all interferograms
number of pixels to invert: 0 out of 720000 (0.0%)
Traceback (most recent call last):
  File "/Users/fielding/tools/mintpy/mintpy/smallbaselineApp.py", line 1116, in <module>
    main()
  File "/Users/fielding/tools/mintpy/mintpy/smallbaselineApp.py", line 1106, in main
    app.run(steps=inps.runSteps, plot=inps.plot)
  File "/Users/fielding/tools/mintpy/mintpy/smallbaselineApp.py", line 1050, in run
    self.run_network_inversion(sname)
  File "/Users/fielding/tools/mintpy/mintpy/smallbaselineApp.py", line 580, in run_network_inversion
    mintpy.ifgram_inversion.main(iargs)
  File "/Users/fielding/tools/mintpy/mintpy/ifgram_inversion.py", line 1134, in main
    ifgram_inversion(inps)
  File "/Users/fielding/tools/mintpy/mintpy/ifgram_inversion.py", line 1052, in ifgram_inversion
    ts, temp_coh, num_inv_ifg = ifgram_inversion_patch(**data_kwargs)[:-1]
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by yunjunz** [comment]
Hi @EJFielding, it's supposed to skip those blocks if there is no pixel to process. The bug should be fixed in the PR above. Thank you for pointing it out.

**Comment by EJFielding** [comment]
Thanks @yunjunz now it correctly skips the blocks when there are zero pixels. Much better!
