### ISSUE TITLE
error when run diff.py

### ISSUE THREAD

**Issue by thorly** [insarlab/MintPy#417]
this is my code(I can run this code in laptop1, but cannot in laptop2):

`!diff.py timeseries.h5 inputs/GACOS.h5 -o timeseries_GACOS.h5`

this is the error:
> timeseries.h5 - ['inputs/GACOS.h5'] --> timeseries_GACOS.h5
> input files are: timeseries and timeseries
> delete exsited file: timeseries_GACOS.h5
> create HDF5 file: timeseries_GACOS.h5 with w mode
> create dataset /timeseries of float32    in size of (101, 1188, 1464)    with compression=None
> create dataset /bperp      of float32    in size of (101,)     with compression=None
> create dataset /date       of |S8        in size of (101,)     with compression=None
> Traceback (most recent call last):
>   File "/usr/local/MintPy/mintpy/diff.py", line 216, in <module>
>     main()
>   File "/usr/local/MintPy/mintpy/diff.py", line 207, in main
>     inps.outfile = diff_file(inps.file1, inps.file2, inps.outfile, force=inps.force)
>   File "/usr/local/MintPy/mintpy/diff.py", line 150, in diff_file
>     writefile.write(data, out_file=outFile, ref_file=file1)
>   File "/usr/local/MintPy/mintpy/utils/writefile.py", line 114, in write
>     f.attrs[key] = str(value)
> UnicodeEncodeError: 'ascii' codec can't encode characters in position 18-20: ordinal not in range(128)

I tried many methods, but cannot resolve it.

**Comment by yunjunz** [comment]
1. what's the difference between your laptop1 and 2?
2. The error message is referring to the writing of metadata, what's the metadata? A simple debug on writefile.py should do.
3. fill the template for the bug report please, it helps the diagnosis a lot.

**Comment by thorly** [comment]
1. difference between your laptop1(can run it) and laptop2(cannot run it)
- Operating system: same(ubuntu 18)
- Python environment: laptop1(python3.7.7 anaconda) lattop2(python3.6.9)
- Version of MintPy:same(v1.2.3 2020-07-14)
- template file: same
```
##-------------------------------- MintPy -----------------------------##
########## 1. Load Data (--load to exit after this step)
## load_data.py -H to check more details and example inputs.
mintpy.load.processor        = isce
##---------for ISCE only:
mintpy.load.metaFile         = ../isce_stack/master/IW*.xml
mintpy.load.baselineDir      = ../isce_stack/baselines
##---------interferogram datasets:
mintpy.load.unwFile          = ../isce_stack/merged/interferograms/*/filt_*.unw
mintpy.load.corFile          = ../isce_stack/merged/interferograms/*/filt_*.cor
mintpy.load.connCompFile     = ../isce_stack/merged/interferograms/*/filt_*.unw.conncomp
##---------geometry datasets:
mintpy.load.demFile          = ../isce_stack/merged/geom_master/hgt.rdr
mintpy.load.lookupYFile      = ../isce_stack/merged/geom_master/lat.rdr
mintpy.load.lookupXFile      = ../isce_stack/merged/geom_master/lon.rdr
mintpy.load.incAngleFile     = ../isce_stack/merged/geom_master/los.rdr
mintpy.load.azAngleFile      = ../isce_stack/merged/geom_master/los.rdr
mintpy.load.shadowMaskFile   = ../isce_stack/merged/geom_master/shadowMask.rdr
mintpy.load.waterMaskFile    = None
##---------subset (optional):
mintpy.subset.yx   = 2000:3188,1000:2464    #[1800:2000,700:800 / no], auto for no

########## 2. modify_network
mintpy.network.keepMinSpanTree 		= yes  #[yes / no], auto for yes, keep interferograms in Min Span Tree network

########## 3. reference_point

########## 4. correct_unwrap_error (optional)

########## 5. invert_network
mintpy.networkInversion.minTempCoh  	= 0.5 #[0.0-1.0], auto for 0.7, min temporal coherence for mask
```

2. metadata is gacos data.
```
timeseries.h5 - ['inputs/GACOS.h5'] --> timeseries_GACOS.h5
input files are: timeseries and timeseries
create HDF5 file: timeseries_GACOS.h5 with w mode
create dataset /timeseries of float32    in size of (101, 1188, 1464)    with compression=None
create dataset /bperp      of float32    in size of (101,)     with compression=None
create dataset /date       of |S8        in size of (101,)     with compression=None
EARTH_RADIUS : 6352358.158284446
beam_swath : 3
WIDTH : 1464
WAVELENGTH : 0.05546576
REF_Y : 560
REF_X : 231
ISCE_VERSION : Release: 2.3, svn-2531, 20190112. Current: svn-2531.
SUBSET_XMAX : 2464
PRF : 1685.817302492702
image_type : unw
mintpy.load.corFile : ../isce_stack/merged/interferograms/*/filt_*.cor
LON_REF4 : 102.06958194975272
LON_REF3 : 102.91847710759568
LON_REF2 : 102.28509231783896
LON_REF1 : 103.15725583457447
POLARIZATION : VV
STARTING_RANGE : 924622.299938
FILE_PATH : /media/ly/文件/sc2/mintpy6/timeseries.h5
mintpy.load.incAngleFile : ../isce_stack/merged/geom_master/los.rdr
SUBSET_YMIN : 2000
ALOOKS : 3
beam_mode : IW
name : unwimage_name
mintpy.networkInversion.weightFunc : var
mintpy.load.shadowMaskFile : ../isce_stack/merged/geom_master/shadowMask.rdr
mintpy.load.connCompFile : ../isce_stack/merged/interferograms/*/filt_*.unw.conncomp
P_BASELINE_TOP_HDR : -108.204232426
LENGTH : 1188
first_frame : 494
xmax : 2464
ANTENNA_SIDE : -1
DATA_TYPE : float32
lastFrameNumber : 497
FILE_TYPE : timeseries
azimuthResolution : 22.6
stopUTC : 2017-01-20 23:04:14.616733
END_DATE : 20200709
rangeResolution : 3.5
mintpy.load.processor : isce
HEADING : -170.10993194580078
azimuthPixelSize : 46.8409834458499
passDirection : DESCENDING
mintpy.load.demFile : ../isce_stack/merged/geom_master/hgt.rdr
data_type : float
SUBSET_XMIN : 1000
mintpy.load.unwFile : ../isce_stack/merged/interferograms/*/filt_*.unw
mintpy.network.keepMinSpanTree : yes
DATE12 : 170120-170213
UNIT : m
rangePixelSize : 23.29562114715323
number_bands : 2
mintpy.troposphericDelay.method : height_correlation
length : 3188
orbitNumber : 3938
mintpy.load.azAngleFile : ../isce_stack/merged/geom_master/los.rdr
family : unwimage
mintpy.load.metaFile : ../isce_stack/master/IW*.xml
mintpy.networkInversion.minTempCoh : 0.5
LAT_REF3 : 29.266536776924305
LAT_REF2 : 30.579447272159925
LAT_REF1 : 30.449390054307468
LAT_REF4 : 29.39568237988509
mintpy.deramp : linear
P_BASELINE_BOTTOM_HDR : -108.204232426
altitude : 698980.3915473437
last_frame : 497
width : 2464
XMAX : 1463
trackNumber : 62
access_mode : read
byte_order : l
startingRange : 901326.6787910945
relative_orbit : 62
mintpy.subset.yx : 2000:3188,1000:2464
mintpy.networkInversion.minNormVelocity : True
mintpy.load.lookupYFile : ../isce_stack/merged/geom_master/lat.rdr
START_DATE : 20170120
ORBIT_DIRECTION : DESCENDING
mintpy.networkInversion.maskThreshold : 0.4
scheme : BIL
firstFrameNumber : 494
NCORRLOOKS : 13.795067060867199
RLOOKS : 10
AZIMUTH_PIXEL_SIZE : 46.8409834458499
prf : 1685.817302492702
Traceback (most recent call last):
  File "/usr/local/MintPy/mintpy/diff.py", line 216, in <module>
    main()
  File "/usr/local/MintPy/mintpy/diff.py", line 207, in main
    inps.outfile = diff_file(inps.file1, inps.file2, inps.outfile, force=inps.force)
  File "/usr/local/MintPy/mintpy/diff.py", line 150, in diff_file
    writefile.write(data, out_file=outFile, ref_file=file1)
  File "/usr/local/MintPy/mintpy/utils/writefile.py", line 114, in write
    print('{} : {}'.format(key, value))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 18-20: ordinal not in range(128)
```

**Comment by yunjunz** [comment]
Seems like an issue related to this one: https://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20. 

It should be the key and value right after "prf : 1685.817302492702" caused the error. Could you print out that one? Or since you have the data file, it will be easier for you to debug the script yourself. Here is the simple instruction in case you are not familiar with debugging in python: https://pythonconquerstheuniverse.wordpress.com/2009/09/10/debugging-in-python/

**Comment by thorly** [comment]
Thanks, I will try it.

**Comment by yunjunz** [comment]
Hi @thorly, I am curious have you been able to identify the cause of the issue and solved it?

**Comment by thorly** [comment]
Yes, I solved it in an imperfect method.
### Method 1
When I run `!diff.py timeseries.h5 inputs/GACOS.h5 -o timeseries_GACOS.h5` , I found the type of value (File "/usr/local/MintPy/mintpy/utils/writefile.py", line 114, f.attrs[key] = str(value)) were `unicode` `str` and `numpy.float64`, so I encode the `unicode`. 
I modified the code of `writefile.py`.
```Python
# 3. metadata
for key, value in meta.items():
    if isinstance(value, unicode):
        f.attrs[key] = str(value.encode('utf-8'))
    else:
        f.attrs[key] = str(value)
print('finished writing to {}'.format(out_file))
```
But this is only suitable for `diff.py`, if other scripts call the modified `writefile.py`, it will raise an error.

### Method 2
I copied `diff.py` into other directory and modified it (I didn't use `argparse`).
```Python
if __name__ == '__main__':
    file1 = "timeseries.h5"
    file2 = ["inputs/GACOS.h5"]
    out_file = "timeseries_GACOS.h5"
    diff_file(file1, file2, out_file)
```
I also print the type of value, and the type of value are `str` and `numpy.float64`, no type of `unicode` .

**Comment by yunjunz** [comment]
Hi @thorly, your method 1 sounds reasonable to me. I recommend you to change [utils/writefile.py#L115](https://github.com/insarlab/MintPy/blob/main/mintpy/utils/writefile.py#L115) to:

```python
try:
    f.attrs[key] = str(value)
except:
    f.attrs[key] = str(value.encode('utf-8'))
```

This should solve the issue and do not break the code. Could you confirm it? If it works, it will be useful if you issue a pull request to commit it.

Again what's the value that has the unicode type? I am curious to see.

**Comment by thorly** [comment]
Thanks.
I test all steps of smallbaselineApp.py, it worked, no error.
Here are type and value.
```Python
(<type 'unicode'>, u'6352358.158284446')
(<type 'unicode'>, u'3')
(<type 'unicode'>, u'1000')
(<type 'unicode'>, u'0.05546576')
(<type 'unicode'>, u'894')
(<type 'unicode'>, u'474')
(<type 'unicode'>, u'Release: 2.3, svn-2531, 20190112. Current: svn-2531.')
(<type 'unicode'>, u'1000')
(<type 'unicode'>, u'1685.817302492702')
(<type 'unicode'>, u'unw')
(<type 'unicode'>, u'../isce_stack/merged/interferograms/*/filt_*.cor')
(<type 'unicode'>, u'102.06958194975272')
(<type 'unicode'>, u'102.91847710759568')
(<type 'unicode'>, u'102.28509231783896')
(<type 'unicode'>, u'103.15725583457447')
(<type 'unicode'>, u'VV')
(<type 'numpy.float64'>, 901326.6787910945)
(<type 'str'>, '/media/ly/file/sc2/test/timeseries.h5')
(<type 'unicode'>, u'../isce_stack/merged/geom_master/los.rdr')
(<type 'unicode'>, u'0')
(<type 'unicode'>, u'3')
(<type 'unicode'>, u'IW')
(<type 'unicode'>, u'unwimage_name')
(<type 'unicode'>, u'var')
(<type 'unicode'>, u'../isce_stack/merged/geom_master/shadowMask.rdr')
(<type 'unicode'>, u'../isce_stack/merged/interferograms/*/filt_*.unw.conncomp')
(<type 'unicode'>, u'-108.204232426')
(<type 'unicode'>, u'1000')
(<type 'unicode'>, u'494')
(<type 'unicode'>, u'2464')
(<type 'unicode'>, u'-1')
(<type 'str'>, 'float32')
(<type 'unicode'>, u'497')
(<type 'str'>, 'timeseries')
(<type 'unicode'>, u'22.6')
(<type 'unicode'>, u'2017-01-20 23:04:14.616733')
(<type 'unicode'>, u'20200709')
(<type 'unicode'>, u'3.5')
(<type 'unicode'>, u'isce')
(<type 'unicode'>, u'-170.10993194580078')
(<type 'unicode'>, u'46.8409834458499')
(<type 'unicode'>, u'DESCENDING')
(<type 'unicode'>, u'../isce_stack/merged/geom_master/hgt.rdr')
(<type 'unicode'>, u'float')
(<type 'unicode'>, u'0')
(<type 'unicode'>, u'../isce_stack/merged/interferograms/*/filt_*.unw')
(<type 'unicode'>, u'yes')
(<type 'unicode'>, u'170120-170213')
(<type 'unicode'>, u'm')
(<type 'unicode'>, u'23.29562114715323')
(<type 'unicode'>, u'2')
(<type 'unicode'>, u'height_correlation')
(<type 'unicode'>, u'3188')
(<type 'unicode'>, u'3938')
(<type 'unicode'>, u'../isce_stack/merged/geom_master/los.rdr')
(<type 'unicode'>, u'unwimage')
(<type 'unicode'>, u'../isce_stack/master/IW*.xml')
(<type 'unicode'>, u'0.5')
(<type 'unicode'>, u'29.266536776924305')
(<type 'unicode'>, u'30.579447272159925')
(<type 'unicode'>, u'30.449390054307468')
(<type 'unicode'>, u'29.39568237988509')
(<type 'unicode'>, u'linear')
(<type 'unicode'>, u'-108.204232426')
(<type 'unicode'>, u'698980.3915473437')
(<type 'unicode'>, u'497')
(<type 'unicode'>, u'2464')
(<type 'unicode'>, u'999')
(<type 'unicode'>, u'62')
(<type 'unicode'>, u'read')
(<type 'unicode'>, u'l')
(<type 'unicode'>, u'901326.6787910945')
(<type 'unicode'>, u'62')
(<type 'unicode'>, u'0:1000,0:1000')
(<type 'unicode'>, u'True')
(<type 'unicode'>, u'../isce_stack/merged/geom_master/lat.rdr')
(<type 'unicode'>, u'20170120')
(<type 'unicode'>, u'DESCENDING')
(<type 'unicode'>, u'0.4')
(<type 'unicode'>, u'BIL')
(<type 'unicode'>, u'494')
(<type 'unicode'>, u'13.795067060867199')
(<type 'unicode'>, u'10')
(<type 'unicode'>, u'46.8409834458499')
(<type 'unicode'>, u'1685.817302492702')
(<type 'unicode'>, u'/media/chenjiajun/\u65b0\u52a0\u5377/Des_sc2/merged/interferograms/20170120_20170213/filt_fine.unw')
(<type 'unicode'>, u'../isce_stack/merged/geom_master/lon.rdr')
(<type 'unicode'>, u'83037.0')
(<type 'unicode'>, u'23.29562114715323')
(<type 'unicode'>, u'../isce_stack/baselines')
(<type 'unicode'>, u'0.05546576')
(<type 'unicode'>, u'3')
(<type 'unicode'>, u'0')
(<type 'unicode'>, u'stack')
(<type 'unicode'>, u'VV')
(<type 'unicode'>, u'None')
(<type 'unicode'>, u'2017-01-20 23:03:57.168990')
(<type 'unicode'>, u'1000')
(<type 'unicode'>, u'698980.3915473437')
(<type 'unicode'>, u'390')
(<type 'unicode'>, u'20170120')
(<type 'unicode'>, u'3188')
(<type 'unicode'>, u'isce')
(<type 'unicode'>, u'False')
(<type 'unicode'>, u'unwrapPhase')
(<type 'unicode'>, u'999')
(<type 'unicode'>, u'1.0')
(<type 'unicode'>, u'6352358.158284446')
```

**Comment by yunjunz** [comment]
Great! Could you commit it?

**Comment by thorly** [comment]
I will try it, because I am not very familiar with GitHub.

**Comment by yunjunz** [comment]
Here is a guideline: https://github.com/insarlab/MintPy/blob/main/docs/CONTRIBUTING.md
