### ISSUE TITLE
spacecraft name

### ISSUE THREAD

**Issue by mirzaees** [insarlab/MintPy#429]
**Description of the problem**

spacecraftname is not found in metadata

**Full script that generated the error**

Recently, after processing the data with ISCE, some information seem to be missing from '.xml' files
working with TopsStack data, the first step of mintpy is loading data in which it reads metadata from this file: 'reference/IW*.xml' 

the information about 'spacecraftname'  is not found and this line does not get the value:

https://github.com/insarlab/MintPy/blob/a9808514bcb901286d8afb43a384260253867fe3/mintpy/utils/isce_utils.py#L220

The problem does not seem to be happening in all datasets which is weird, 
for example I processed Galapagos test data  (GalapagosSenDT128) with no problem but other areas like Cerro Negro Chiles (EcuadorSenDT142) or Taal volcanoes (TaalSenDT32), it does not find that information and will produce error afterwards

I have processed these before with no problem, not sure what happened recently
@yunjunz and @hfattahi  Could you please take a look at this? 
I don't know if it is better to modify in mintpy or fix in ISCE

Here is the error that is caused by not reading metadata:

```

******************** step - load_data ********************
load_data.py --template /scratch1/06736/sxm1611/EcuadorSenDT142/mintpy/smallbaselineApp.cfg /scratch1/06736/sxm1611/EcuadorSenDT142/EcuadorSenDT142.template --project EcuadorSenDT142
processor : isce
SAR platform/sensor : Sen
use auto path defined in mintpy.defaults.auto_path for options in auto
    mintpy.load.metaFile       : auto --> ../reference/IW*.xml
    mintpy.load.baselineDir    : auto --> ../baselines
    mintpy.load.unwFile        : auto --> ../merged/interferograms/*/filt*.unw
    mintpy.load.corFile        : auto --> ../merged/interferograms/*/filt*.cor
    mintpy.load.connCompFile   : auto --> ../merged/interferograms/*/filt*.unw.conncomp
    mintpy.load.demFile        : auto --> ../merged/geom_reference/hgt.rdr
    mintpy.load.lookupYFile    : auto --> ../merged/geom_reference/lat.rdr
    mintpy.load.lookupXFile    : auto --> ../merged/geom_reference/lon.rdr
    mintpy.load.incAngleFile   : auto --> ../merged/geom_reference/los.rdr
    mintpy.load.azAngleFile    : auto --> ../merged/geom_reference/los.rdr
    mintpy.load.shadowMaskFile : auto --> ../merged/geom_reference/shadowMask.rdr
    mintpy.load.waterMaskFile  : auto --> ../merged/geom_reference/waterMask.rdr
--------------------------------------------------
prepare metadata files for isce products
prep_isce.py -m ../reference/IW2.xml -g ../merged/geom_reference -b ../baselines -d ../merged/interferograms -f filt*.unw
extract metadata from ISCE/topsStack xml file: ../reference/IW2.xml
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
--------------------------------------------------
searching interferometric pairs info
input data files:
unwrapPhase     : ../merged/interferograms/*/filt*.unw
coherence       : ../merged/interferograms/*/filt*.cor
connectComponent: ../merged/interferograms/*/filt*.unw.conncomp
number of unwrapPhase     : 485
number of coherence       : 486
number of connectComponent: 485
WARNING: NOT all types of dataset have the same number of files. -> skip interferograms with missing files and continue.
Traceback (most recent call last):
  File "/work/06736/sxm1611/stampede2/development/rsmas_insar/sources/MintPy/mintpy/smallbaselineApp.py", line 1116, in <module>
    main()
  File "/work/06736/sxm1611/stampede2/development/rsmas_insar/sources/MintPy/mintpy/smallbaselineApp.py", line 1106, in main
    app.run(steps=inps.runSteps, plot=inps.plot)
  File "/work/06736/sxm1611/stampede2/development/rsmas_insar/sources/MintPy/mintpy/smallbaselineApp.py", line 1035, in run
    self.run_load_data(sname)
  File "/work/06736/sxm1611/stampede2/development/rsmas_insar/sources/MintPy/mintpy/smallbaselineApp.py", line 363, in run_load_data
    mintpy.load_data.main(iargs)
  File "/work/06736/sxm1611/stampede2/development/rsmas_insar/sources/MintPy/mintpy/load_data.py", line 655, in main
    stackObj = read_inps_dict2ifgram_stack_dict_object(inpsDict)
  File "/work/06736/sxm1611/stampede2/development/rsmas_insar/sources/MintPy/mintpy/load_data.py", line 400, in read_inps_dict2ifgram_stack_dict_object
    date12 = readfile.read_attribute(dsPath)['DATE12'].replace('_','-')
KeyError: 'DATE12'


```

**Comment by yunjunz** [comment]
Hi @mirzaees, this extra line was added recently https://github.com/insarlab/MintPy/pull/422. I agree that the KeyError `DATE12` is caused by the improper read metadata. I have 3 suggestions:

1. Will the processing go through without issue if that one line is commented out?
2. Why those datasets do not have the spacecraft metadata in the XML file?
3. The "WARNING: NOT all types of dataset have the same number of files. -> skip interferograms with missing files and continue." seem unusual also, any idea why?

**Comment by mirzaees** [comment]
Hi @yunjunz, 

1. Yes it will go through without this line (testing only load_data)
2. I don't really know, I tried to find the reason in ISCE but could not, I am guessing it is missing from data metafiles
3. That warning is Ok, one of my interferograms is not unwrapped

Thank you

**Comment by yunjunz** [comment]
Hardwired this line in mintpy to `Sen` sounds good to me, please feel free to go ahead.

**Comment by mirzaees** [comment]
Ok Thank you!
