### ISSUE TITLE
view.py coastline with single panel fails

### ISSUE THREAD

**Issue by EJFielding** [insarlab/MintPy#437]
**Description of the problem**

I tried to use the coastline option to add to a view of the `velocity` layer only from `geo_velocity.h5` and it fails. Running without specifying the `velocity` layer completes, but does not plot the coastline.

**Full script that generated the error**

```
view.py geo_velocity.h5 velocity --ref-lalo 18.0 -67.0 --coastline 110m -v -20 5
```

**Full error message**

```
run view.py in MintPy release version v1.2.3-30, release date 2020-09-03
input file is velocity file: /Users/fielding/Google Drive (fielding@jpl.caltech.edu)/Earthquakes/PuertoRico-EQ2020/S1AB/A135/stack/MintPy_v6/geo/geo_velocity.h5 in float32 format
file size in y/x: (800, 1200)
input dataset: "['velocity']"
turning glob search OFF for velocity file
num of datasets in file geo_velocity.h5: 2
datasets to exclude (0):
[]
datasets to display (1):
['velocity']
data   coverage in y/x: (0, 0, 1200, 800)
subset coverage in y/x: (0, 0, 1200, 800)
data   coverage in lat/lon: (-67.33490138813492, 18.61347689885222, -66.41580814555647, 17.775536391553057)
subset coverage in lat/lon: (-67.33490138813492, 18.61347689885222, -66.41580814555647, 17.775536391553057)
------------------------------------------------------------------------
colormap: jet
input reference point in lat/lon: [18.0, -67.0]
input reference point in y  /x  : [585, 437]
figure title: geo_velocity
figure size : [8.23, 6.00]
read mask from file: geo_maskTempCoh.h5
reading data ...
masking data
set reference pixel to: [585, 437]
data    range: [-21.987125, 6.576535] cm/year
display range: [-20.0, 5.0] cm/year
display data in transparency: 1.0
plot in Lat/Lon coordinate
map projection: PlateCarree
draw coast line with resolution: 110m
Traceback (most recent call last):
  File "/Users/fielding/tools/mintpy/mintpy/view.py", line 1478, in <module>
    main(sys.argv[1:])
  File "/Users/fielding/tools/mintpy/mintpy/view.py", line 1472, in main
    obj.plot()
  File "/Users/fielding/tools/mintpy/mintpy/view.py", line 1434, in plot
    ax, self, im, cbar = plot_slice(ax, data, self.atr, self)
  File "/Users/fielding/tools/mintpy/mintpy/view.py", line 440, in plot_slice
    ax.coastlines(resolution=inps.coastline)
AttributeError: 'AxesSubplot' object has no attribute 'coastlines'
```

**System information**

* Operating system: macOS 
* Python environment: conda 
* Version of MintPy: MintPy release version v1.2.3-30, release date 2020-09-03 
* Your custom / default template file (if the bug is related to a specific dataset):

**Comment by EJFielding** [comment]
I also tried this on a Linux machine (kamb.gps.caltech.edu) and got the same error.

**Comment by yunjunz** [comment]
Thank you @EJFielding for identifying this. It should be working now.

```
view.py velocity.h5 velocity --coastline 10m
```

<img width="862" alt="Screen Shot 2020-09-06 at 4 38 34 PM" src="https://user-images.githubusercontent.com/13143710/92338057-78100b00-f062-11ea-8341-8c02c55ae8d9.png">

**Comment by EJFielding** [comment]
Thanks @yunjunz! It works great now.
![geo_velocity](https://user-images.githubusercontent.com/7253576/92357962-8cbdc480-f09d-11ea-96bd-c4c1021d75e2.png)
