### ISSUE TITLE
Invert network

### ISSUE THREAD

**Issue by alejobeap** [insarlab/MintPy#448]
Dear
I have this error in the invert network part:

create HDF5 file numInvIfgram.h5 with w mode
create dataset: mask                      of <class 'numpy.float32'>   in size of (922, 1208)
close  HDF5 file numInvIfgram.h5
calculating weight from spatial coherence ...
reading coherence in (0, 0, 1208, 922) * 45 ...
Traceback (most recent call last):
  File "/home/isce/tools/MintPy/mintpy/smallbaselineApp.py", line 1119, in <module>
    main()
  File "/home/isce/tools/MintPy/mintpy/smallbaselineApp.py", line 1109, in main
    app.run(steps=inps.runSteps, plot=inps.plot)
  File "/home/isce/tools/MintPy/mintpy/smallbaselineApp.py", line 1053, in run
    self.run_network_inversion(sname)
  File "/home/isce/tools/MintPy/mintpy/smallbaselineApp.py", line 580, in run_network_inversion
    mintpy.ifgram_inversion.main(iargs)
  File "/home/isce/tools/MintPy/mintpy/ifgram_inversion.py", line 1142, in main
    ifgram_inversion(inps)
  File "/home/isce/tools/MintPy/mintpy/ifgram_inversion.py", line 1060, in ifgram_inversion
    ts, temp_coh, num_inv_ifg = ifgram_inversion_patch(**data_kwargs)[:-1]
  File "/home/isce/tools/MintPy/mintpy/ifgram_inversion.py", line 766, in ifgram_inversion_patch
    chunk_size=100000)
  File "/home/isce/tools/MintPy/mintpy/ifgram_inversion.py", line 658, in calc_weight
    L = int(stack_obj.metadata['ALOOKS']) * int(stack_obj.metadata['RLOOKS'])
KeyError: 'ALOOKS'

Can you help me.

Thanks

Pedro

**Comment by yunjunz** [comment]
Please follow the [bug report template](https://github.com/insarlab/MintPy/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) to provide more information for diagnosing.

**Comment by yunjunz** [comment]
The similar issue and suggestions have been reported in the user forum before, you should check it there.

**Comment by alejobeap** [comment]
Thanks
