### ISSUE TITLE
KeyError: 'LAT_REF1'  when using ERA5 to correct troposphere

### ISSUE THREAD

**Issue by thorly** [insarlab/MintPy#458]
**Description of the problem**
I process ALOS-2 data using gamma for MintPy timeseries, when I using ERA5 for correcting troposphere, it raised an error (`KeyError: 'LAT_REF1'`). I checked the data named `geometryRadar.h5`, no keys named `LAT_REF*`.
This is the data struct of `geometryRadar.h5`:
```
Attributes in / level:
  ALOOKS                                1
  FILE_LENGTH                           3120
  FILE_PATH                             /media/ly/文件/sc_prj/ALOS/590/stacking_for_mintpy/geom_master/sim_20180126_9rlks.rdc.dem
  FILE_TYPE                             geometry
  LENGTH                                3120
  PLATFORM                              Alos
  PROCESSOR                             gamma
  PROJECT_NAME                          scAlos590
  RLOOKS                                1
  WIDTH                                 2512
  az_pixel_spacing_1                    22.136090
  az_pixel_spacing_2                    22.136090
  az_samp_1                             3120
  az_samp_2                             3120
  azimuth_looks                         1
  azimuth_offset_polynomial             21.87707
  diff_phase_fit                        -7.03588
  first_map_range_pixel                 0
  first_nonzero_range_pixel_1           0
  first_nonzero_range_pixel_2           0
  initial_azimuth_offset                22
  map_azimuth_lines                     3120
  map_width                             2512
  mintpy.deramp                         linear
  mintpy.load.corFile                   ./../stacking_for_mintpy/interferograms/*/filt_*rlks.cor
  mintpy.load.demFile                   ./../stacking_for_mintpy/geom_master/sim_*.rdc.dem
  mintpy.load.lookupXFile               ./../stacking_for_mintpy/geom_master/sim_*.UTM_TO_RDC
  mintpy.load.lookupYFile               ./../stacking_for_mintpy/geom_master/sim_*.UTM_TO_RDC
  mintpy.load.processor                 gamma
  mintpy.load.unwFile                   ./../stacking_for_mintpy/interferograms/*/diff_*rlks.unw
  mintpy.network.coherenceBased         yes
  mintpy.network.keepMinSpanTree        no
  mintpy.network.minCoherence           0.6
  mintpy.networkInversion.minTempCoh    0.5
  mintpy.troposphericDelay.method       pyaps
  number_map_range_pixels               2512
  number_of_nonzero_range_pixels_1      2512
  number_of_nonzero_range_pixels_2      2512
  offset_estimation_azimuth_samples     300
  offset_estimation_azimuth_spacing     9
  offset_estimation_ending_azimuth      3120
  offset_estimation_ending_range        2512
  offset_estimation_patch_height        64
  offset_estimation_patch_width         64
  offset_estimation_range_samples       300
  offset_estimation_range_spacing       7
  offset_estimation_starting_azimuth    128
  offset_estimation_starting_range      128
  offset_estimation_threshhold          9.00
  range_looks                           1
  range_offset_polynomial               -1.77934
  range_pixel_spacing_1                 14.304220
  range_pixel_spacing_2                 14.304220
  range_samp_1                          2512
  range_samp_2                          2512
  starting_azimuth_line                 0

```

**Full script that generated the error**

```
tropo_pyaps3.py -f timeseries.h5 --model ERA5 -g /media/ly/文件/sc_prj/ALOS/590/mintpy_era5/inputs/geometryRadar.h5 -w ${WEATHER_DIR}
```

**Full error message**

```
MintPy release version v1.2.3-51, release date 2020-10-07
--RUN-at-2020-10-09 15:53:10.961019--
Current directory: /media/ly/文件/sc_prj/ALOS/590/mintpy_era5
Run routine processing with smallbaselineApp.py on steps: ['correct_troposphere']
Remaining steps: ['deramp', 'correct_topography', 'residual_RMS', 'reference_date', 'velocity', 'geocode', 'google_earth', 'hdfeos5']
--------------------------------------------------
Project name: scAlos590
Go to work directory: /media/ly/文件/sc_prj/ALOS/590/mintpy_era5
read custom template file: /media/ly/文件/sc_prj/ALOS/590/mintpy_era5/scAlos590.txt
update default template based on input custom template
No new option value found, skip updating /media/ly/文件/sc_prj/ALOS/590/mintpy_era5/smallbaselineApp.cfg
read default template file: /media/ly/文件/sc_prj/ALOS/590/mintpy_era5/smallbaselineApp.cfg


******************** step - correct_troposphere ********************
Atmospheric correction using Weather Re-analysis dataset (PyAPS, Jolivet et al., 2011)
Weather Re-analysis dataset: ERA5
tropo_pyaps3.py -f timeseries.h5 --model ERA5 -g /media/ly/文件/sc_prj/ALOS/590/mintpy_era5/inputs/geometryRadar.h5 -w ${WEATHER_DIR}
weather model: ERA5 - dry (hydrostatic) and wet delay
weather directory: /media/ly/文件/sc_prj/ALOS/590/mintpy_era5
output tropospheric delay file: /media/ly/文件/sc_prj/ALOS/590/mintpy_era5/inputs/ERA5.h5
output corrected time-series file: timeseries_ERA5.h5
read dates/time info from file: timeseries.h5
time of cloest available product: 17:00 UTC

------------------------------------------------------------------------------
downloading weather model data using PyAPS ...
common file size: 759240 bytes
number of grib files existed    : 7
number of grib files to download: 0
------------------------------------------------------------------------------

open geometry file: geometryRadar.h5
reading incidenceAngle  data from file: /media/ly/文件/sc_prj/ALOS/590/mintpy_era5/inputs/geometryRadar.h5 ...
reading height          data from file: /media/ly/文件/sc_prj/ALOS/590/mintpy_era5/inputs/geometryRadar.h5 ...
Traceback (most recent call last):
  File "/home/ly/tools/MintPy/mintpy/smallbaselineApp.py", line 1123, in <module>
    main()
  File "/home/ly/tools/MintPy/mintpy/smallbaselineApp.py", line 1113, in main
    app.run(steps=inps.runSteps, plot=inps.plot)
  File "/home/ly/tools/MintPy/mintpy/smallbaselineApp.py", line 1063, in run
    self.run_tropospheric_delay_correction(sname)
  File "/home/ly/tools/MintPy/mintpy/smallbaselineApp.py", line 795, in run_tropospheric_delay_correction
    tropo_pyaps3.main(iargs)
  File "/home/ly/tools/MintPy/mintpy/tropo_pyaps3.py", line 709, in main
    calculate_delay_timeseries(inps)
  File "/home/ly/tools/MintPy/mintpy/tropo_pyaps3.py", line 625, in calculate_delay_timeseries
    inps.lat, inps.lon = ut.get_lat_lon_rdc(geom_obj.metadata)
  File "/home/ly/tools/MintPy/mintpy/utils/utils0.py", line 351, in get_lat_lon_rdc
    lats = [float(meta['LAT_REF{}'.format(i)]) for i in [1,2,3,4]]
  File "/home/ly/tools/MintPy/mintpy/utils/utils0.py", line 351, in <listcomp>
    lats = [float(meta['LAT_REF{}'.format(i)]) for i in [1,2,3,4]]
KeyError: 'LAT_REF1'
```

**System information**

* Operating system: Ubuntu 18.04
* Python environment: conda
* Version of MintPy:MintPy release version v1.2.3-51, release date 2020-10-07 
* Your custom / default template file (if the bug is related to a specific dataset):
```
##-------------------------------- MintPy -----------------------------##
########## 1. Load Data (--load to exit after this step)
## load_data.py -H to check more details and example inputs.
mintpy.load.processor      = gamma
mintpy.load.unwFile        = ./../stacking_for_mintpy/interferograms/*/diff_*rlks.unw
mintpy.load.corFile        = ./../stacking_for_mintpy/interferograms/*/filt_*rlks.cor
mintpy.load.connCompFile   = None
mintpy.load.intFile        = None

mintpy.load.demFile        = ./../stacking_for_mintpy/geom_master/sim_*.rdc.dem
mintpy.load.lookupYFile    = ./../stacking_for_mintpy/geom_master/sim_*.UTM_TO_RDC
mintpy.load.lookupXFile    = ./../stacking_for_mintpy/geom_master/sim_*.UTM_TO_RDC
mintpy.load.incAngleFile   = None
mintpy.load.azAngleFile    = None
mintpy.load.shadowMaskFile = None
mintpy.load.waterMaskFile  = None
##---------subset (optional):
# mintpy.subset.yx   = 2000:3188,1000:2464    #[1800:2000,700:800 / no], auto for no

########## 2. modify_network
mintpy.network.coherenceBased  = yes  #[yes / no], auto for no, exclude interferograms with coherence < minCoherence
mintpy.network.keepMinSpanTree = no  #[yes / no], auto for yes, keep interferograms in Min Span Tree network
mintpy.network.minCoherence    = 0.6  #[0.0-1.0], auto for 0.7

########## 3. reference_point

########## 4. correct_unwrap_error (optional)

########## 5. invert_network
mintpy.networkInversion.minTempCoh  	= 0.5 #[0.0-1.0], auto for 0.7, min temporal coherence for mask

########## 6. correct_troposphere (optional and recommended)
mintpy.troposphericDelay.method         = pyaps   #[pyaps / height_correlation / no], auto for pyaps

########## 7. deramp (optional)
mintpy.deramp                           = linear<!-- It helps the diagnose a lot if you could post the configurations you used. You can drag-and-drop them here directly. -->
```

**Comment by yunjunz** [comment]
`LAT/LON_REF1/2/3/4` are extracted in [prep_gamma.get_lalo_ref()](https://github.com/insarlab/MintPy/blob/main/mintpy/prep_gamma.py#L177), which calls gamma command `SLC_corners` on the SLC par file. You could check deeper there why these metadata are missing.

Alternatively, you could calculate these values using `X/Y_FIRST/STEP` and `LENGTH/WIDTH` from `inputs/geometryGeo.h5` file and add them to the `inputs/geometryRadar.h5` file using `add_attribute.py`.

**Comment by thorly** [comment]
Thanks, I solved this problem.
It seems your code does not support `$PATH/interferograms/m_data-s_date`, so I changed it to `$PATH/interferograms/m_date_s_date`, then it works.

**Comment by yunjunz** [comment]
I cannot make a connection between mdate_sdate format and LAT/LON_REF on top of my head, but I glad to hear your problem is solved.

**Comment by thorly** [comment]
I use the following code to debug:
```
    # search existing par file
    geom_dir = os.path.dirname(fname)              #PROJECT_DIR/geom_reference
    ifg_dir = os.path.join(geom_dir, '../*/{}_*'.format(m_date))  #PROJECT_DIR/interferograms/{m_date}_20141225
    m_par_files = [os.path.join(geom_dir, '*{}*{}'.format(m_date, ext)) for ext in PAR_EXT_LIST]
    m_par_files += [os.path.join(ifg_dir, '*{}*{}'.format(m_date, ext)) for ext in PAR_EXT_LIST]
    print('m_par_files:', m_par_files)
    m_par_files = ut.get_file_list(m_par_files)
    print('m_par_files:', m_par_files)
```
and here is output:
```
m_par_files: ['/media/ly/文件/sc_prj/ALOS/590/stacking_for_mintpy/geom_master/*20180126*.amp.par', '/media/ly/文件/sc_prj/ALOS/590/stacking_for_mintpy/geom_master/*20180126*.ramp.par', '/media/ly/文件/sc_prj/ALOS/590/stacking_for_mintpy/geom_master/*20180126*.mli.par', '/media/ly/文件/sc_prj/ALOS/590/stacking_for_mintpy/geom_master/../*/20180126_*/*20180126*.amp.par', '/media/ly/文件/sc_prj/ALOS/590/stacking_for_mintpy/geom_master/../*/20180126_*/*20180126*.ramp.par', '/media/ly/文件/sc_prj/ALOS/590/stacking_for_mintpy/geom_master/../*/20180126_*/*20180126*.mli.par']
m_par_files: []
grab LAT/LON_REF1/2/3/4 from par file:  no par file found with date: 20180126
```
my par file of 20180126 is `/media/ly/文件/sc_prj/ALOS/590/stacking_for_mintpy/interferograms/20180126-20180309/20180126_9rlks.amp.par`, so it cannot find it.
if my par file of 20180126 is `/media/ly/文件/sc_prj/ALOS/590/stacking_for_mintpy/interferograms/20180126_20180309/20180126_9rlks.amp.par`,  it can find it.
and here is output:
```
m_par_files: ['/media/ly/文件/sc_prj/ALOS/590/stacking_for_mintpy/geom_master/*20180126*.amp.par', '/media/ly/文件/sc_prj/ALOS/590/stacking_for_mintpy/geom_master/*20180126*.ramp.par', '/media/ly/文件/sc_prj/ALOS/590/stacking_for_mintpy/geom_master/*20180126*.mli.par', '/media/ly/文件/sc_prj/ALOS/590/stacking_for_mintpy/geom_master/../*/20180126_*/*20180126*.amp.par', '/media/ly/文件/sc_prj/ALOS/590/stacking_for_mintpy/geom_master/../*/20180126_*/*20180126*.ramp.par', '/media/ly/文件/sc_prj/ALOS/590/stacking_for_mintpy/geom_master/../*/20180126_*/*20180126*.mli.par']
m_par_files: ['/media/ly/文件/sc_prj/ALOS/590/stacking_for_mintpy/geom_master/../interferograms/20180126_20180309/20180126_9rlks.amp.par']
grab LAT/LON_REF1/2/3/4 from par file: /media/ly/文件/sc_prj/ALOS/590/stacking_for_mintpy/geom_master/../interferograms/20180126_20180309/20180126_9rlks.amp.par
```
I think this is the connection between mdate_sdate format and LAT/LON_REF.

**Comment by yunjunz** [comment]
Thank you @thorly, with your description, I add the change above in prep_gamma.py, which should now be able to detect both cases. Cheers.
