### ISSUE TITLE
save_hdfeos5.py can't recognize platform

### ISSUE THREAD

**Issue by mohseniaref-InSAR** [insarlab/MintPy#492]
**save_hdfeos5.py Issue**
Dear all,

I appreciate if you guide me to solve the following issue 

Best,
MM

**Full script that generated the error**

```
save_hdfeos5.py geo/geo_timeseries_ERA5_ramp_demErr.h5 --tc geo/geo_temporalCoherence.h5 --asc geo/geo_avgSpatialCoh.h5 -m geo/geo_maskTempCoh.h5 -g geo/geo_geometryRadar.h5
Un-recognized PLATFORM attribute: none
return None
## UNAVCO Metadata:
-----------------------------------------
  atmos_correct_method      None
  beam_mode                 IW
  beam_swath                23
  data_footprint            POLYGON((-66.3874407414305 -23.6901892392968,-64.15110295974138 -23.6901892392968,-64.15110295974138 -25.610366943564532,-66.3874407414305 -25.610366943564532,-66.3874407414305 -23.6901892392968))
  first_date                2014-10-18
  flight_direction          D
  frame                     673
  history                   2020-12-18
  last_date                 2019-04-25
  look_direction            R
  mission                   None
  polarization              VV
  post_processing_method    MintPy
  prf                       1451.62711219399
  processing_dem            Unknown
  processing_type           LOS_TIMESERIES
  relative_orbit            10
  scene_footprint           POLYGON((-64.22278288196397 -24.14059667769328,-64.61325843946649 -25.59144877637518,-66.33053787418807 -25.178023612550046,-65.91179422846174 -23.735064334860155,-64.22278288196397 -24.14059667769328))
  unwrap_method             Unknown
  wavelength                0.05546576

-----------------------------------------
Traceback (most recent call last):
  File "/raid-manaslu/maref/Software/python/MintPy/mintpy/save_hdfeos5.py", line 454, in <module>
    main()
  File "/raid-manaslu/maref/Software/python/MintPy/mintpy/save_hdfeos5.py", line 437, in main
    outName = get_output_filename(metadata=meta_dict,
  File "/raid-manaslu/maref/Software/python/MintPy/mintpy/save_hdfeos5.py", line 214, in get_output_filename
    outName = SAT+'_'+SW+'_'+RELORB+'_'+FRAME+'_'+DATE1+'_'+DATE2+'.he5'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
(mintpy) maref@manaslu:/raid-manaslu/maref/InSAR/S1/desc_tr10_f/stackc/INSAR_20150814/SMALL_BASELINES/var$ save_hdfeos5.py timeseries_ERA5_ramp_demErr.h5     --tc temporalCoherence.h5     --asc avgSpatialCoh.h5     -m maskTempCoh.h5     -g inputs/geometryGeo.h5
Un-recognized PLATFORM attribute: none
return None
Input file is not geocoded, no data_footprint without X/Y_FIRST/STEP info.
## UNAVCO Metadata:
-----------------------------------------
  atmos_correct_method      None
  beam_mode                 IW
  beam_swath                23
  first_date                2014-10-18
  flight_direction          D
  frame                     673
  history                   2020-12-18
  last_date                 2019-04-25
  look_direction            R
  mission                   None
  polarization              VV
  post_processing_method    MintPy
  prf                       1451.62711219399
  processing_dem            Unknown
  processing_type           LOS_TIMESERIES
  relative_orbit            10
  scene_footprint           POLYGON((-64.22278288196397 -24.14059667769328,-64.61325843946649 -25.59144877637518,-66.33053787418807 -25.178023612550046,-65.91179422846174 -23.735064334860155,-64.22278288196397 -24.14059667769328))
  unwrap_method             Unknown
  wavelength                0.05546576

-----------------------------------------
Traceback (most recent call last):
  File "/raid-manaslu/maref/Software/python/MintPy/mintpy/save_hdfeos5.py", line 454, in <module>
    main()
  File "/raid-manaslu/maref/Software/python/MintPy/mintpy/save_hdfeos5.py", line 437, in main
    outName = get_output_filename(metadata=meta_dict,
  File "/raid-manaslu/maref/Software/python/MintPy/mintpy/save_hdfeos5.py", line 214, in get_output_filename
    outName = SAT+'_'+SW+'_'+RELORB+'_'+FRAME+'_'+DATE1+'_'+DATE2+'.he5'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

```

**Full error message**

```
PASTE ERROR MESSAGE HERE
```

**System information**

* Operating system: < Linux-Ubuntu->
* Python environment: <conda->
* Version of MintPy: 
* Your custom / default template file (if the bug is related to a specific dataset):

**Comment by yunjunz** [comment]
Your `mission` metadata is missing, which is required for HDF-EOS5 format. More about metadata description can be found here: https://mintpy.readthedocs.io/en/latest/hdfeos5/#metadata.

**Comment by mohseniaref-InSAR** [comment]
Thanks so much for the valuable information and your detailed explanation.
@yunjunz ,My data was processed by ISCE. So my next question might be What has happened?
Is it possible to produce hdfeos5 with save_hdfeos5.py and somehow insert Platform? information.
My final goal is having a similar data structure for NetCDF4 so it is an intermediate step for me before converting data to NetCDF. I was wondering if you have a better solution to have a NetCDF file with a similar structure?
save_hdfeos5.py geo/geo_timeseries_ERA5_ramp_demErr.h5 --tc geo/geo_temporalCoherence.h5 --asc geo/geo_avgSpatialCoh.h5 -m geo/geo_maskTempCoh.h5 -g geo/geo_geometryRadar.h5

**Comment by yunjunz** [comment]
Grab missing attributes from template file during save_hdfeos5.py is supported via #516. Close the issue.
