### ISSUE TITLE
Occasional ifgram_inversion.py failure when using too many cores with dask

### ISSUE THREAD

**Issue by falkamelung** [insarlab/MintPy#556]
**Description of the problem**
I run MIntPy on TACC's Stampede2 which has 48 cores per node.   It never worked for me using all cores, so I use `mintpy.compute.numWorker = 40`.  I now see occasionally  errors with this number of `numWorkers` as well. Does the error error message below provides any clues?  For this case the solution is to further reduce the number or workers, in this case to `32`.  I would suggest to use as default ⅔ of the cores available, taking into account https://github.com/insarlab/MintPy/issues/518

**Full script that generated the error**

```
ifgram_inversion.py /scratch/05861/tg851601/ref1_KokoxiliBigChunk34SenAT143/mintpy/inputs/ifgramStack.h5 -t /scratch/05861/tg851601/ref1_KokoxiliBigChunk34SenAT143/mintpy/smallbaselineApp.cfg --update > q 2>qe
```
compute options in smallbaselineApp.cfg:
```
mintpy.compute.maxMemory = auto #[float > 0.0], auto for 4, max memory to allocate in GB
mintpy.compute.cluster   = local #[local / slurm / pbs / lsf / none], auto for none, cluster type
mintpy.compute.numWorker = 40 #[int > 1 / all], auto for 4 (local) or 40 (non-local), num of workers
mintpy.compute.config    = auto #[none / slurm / pbs / lsf ], auto for none (same as cluster), config name
```

**Full error message**
```
distributed.worker - WARNING -  Compute Failed
Function:  ifgram_inversion_patch
args:      ()
kwargs:    {'ifgram_file': '/scratch/05861/tg851601/ref1_KokoxiliBigChunk34SenAT143/mintpy/inputs/ifgramStack.h5', 'ref_phase': array([ -7.92037   ,  -1.7360182 ,   4.298844  ,   5.8353987 ,
        11.98461   ,   5.677715  ,   6.2993903 ,  -0.21512586,
        -0.71629095,  -6.536488  ,  -6.9658046 , -16.458952  ,
        -0.42373115, -16.120197  ,  -2.988855  , -15.668289  ,
        -2.3673625 ,  -0.2796244 ,  13.241903  ,  15.173871  ,
        19.804531  ,   2.548349  ,   6.8418107 ,   8.843829  ,
         5.3165255 ,   6.7578416 ,   3.950899  ,   1.5562356 ,
        -1.1136081 ,  -3.3727527 ,  -2.6232302 ,   1.419769  ,
        -1.8182877 ,  -2.241352  ,   0.7664133 ,  -1.310072  ,
        -3.2633429 ,   0.88221025,   3.533897  ,   4.1683283 ,
         6.783082  ,  -2.349379  ,   2.6321976 ,  -0.18120557,
         3.4797752 ,  -2.8508239 ,   0.8451205 ,  -8.9011965 ,
         3.6865058 ,   0.20398574,  -1.9371088 ,  -3.4827151 ,
        -5.544328  ,  -0.6531817 ,  -2.2008953 ,   2.8286705 ,
 
Exception: ValueError('negative dimensions are not allowed')

distributed.worker - WARNING -  Compute Failed
Function:  ifgram_inversion_patch
args:      ()
kwargs:    {'ifgram_file': '/scratch/05861/tg851601/ref1_KokoxiliBigChunk34SenAT143/mintpy/inputs/ifgramStack.h5', 'ref_phase': array([ -7.92037   ,  -1.7360182 ,   4.298844  ,   5.8353987 ,
        11.98461   ,   5.677715  ,   6.2993903 ,  -0.21512586,
        -0.71629095,  -6.536488  ,  -6.9658046 , -16.458952  ,
        -0.42373115, -16.120197  ,  -2.988855  , -15.668289  ,
        -2.3673625 ,  -0.2796244 ,  13.241903  ,  15.173871  ,
        19.804531  ,   2.548349  ,   6.8418107 ,   8.843829  ,
         5.3165255 ,   6.7578416 ,   3.950899  ,   1.5562356 ,
        -1.1136081 ,  -3.3727527 ,  -2.6232302 ,   1.419769  ,
        -1.8182877 ,  -2.241352  ,   0.7664133 ,  -1.310072  ,
        -3.2633429 ,   0.88221025,   3.533897  ,   4.1683283 ,
         6.783082  ,  -2.349379  ,   2.6321976 ,  -0.18120557,
         3.4797752 ,  -2.8508239 ,   0.8451205 ,  -8.9011965 ,
         3.6865058 ,   0.20398574,  -1.9371088 ,  -3.4827151 ,
        -5.544328  ,  -0.6531817 ,  -2.2008953 ,   2.8286705 ,
 
Exception: ValueError('negative dimensions are not allowed')

distributed.worker - WARNING -  Compute Failed
Function:  ifgram_inversion_patch
args:      ()
kwargs:    {'ifgram_file': '/scratch/05861/tg851601/ref1_KokoxiliBigChunk34SenAT143/mintpy/inputs/ifgramStack.h5', 'ref_phase': array([ -7.92037   ,  -1.7360182 ,   4.298844  ,   5.8353987 ,
        11.98461   ,   5.677715  ,   6.2993903 ,  -0.21512586,
        -0.71629095,  -6.536488  ,  -6.9658046 , -16.458952  ,
        -0.42373115, -16.120197  ,  -2.988855  , -15.668289  ,
        -2.3673625 ,  -0.2796244 ,  13.241903  ,  15.173871  ,
        19.804531  ,   2.548349  ,   6.8418107 ,   8.843829  ,
         5.3165255 ,   6.7578416 ,   3.950899  ,   1.5562356 ,
        -1.1136081 ,  -3.3727527 ,  -2.6232302 ,   1.419769  ,
        -1.8182877 ,  -2.241352  ,   0.7664133 ,  -1.310072  ,
        -3.2633429 ,   0.88221025,   3.533897  ,   4.1683283 ,
         6.783082  ,  -2.349379  ,   2.6321976 ,  -0.18120557,
         3.4797752 ,  -2.8508239 ,   0.8451205 ,  -8.9011965 ,
         3.6865058 ,   0.20398574,  -1.9371088 ,  -3.4827151 ,
        -5.544328  ,  -0.6531817 ,  -2.2008953 ,   2.8286705 ,
 
Exception: ValueError('negative dimensions are not allowed')

distributed.worker - WARNING -  Compute Failed
Function:  ifgram_inversion_patch
args:      ()
kwargs:    {'ifgram_file': '/scratch/05861/tg851601/ref1_KokoxiliBigChunk34SenAT143/mintpy/inputs/ifgramStack.h5', 'ref_phase': array([ -7.92037   ,  -1.7360182 ,   4.298844  ,   5.8353987 ,
        11.98461   ,   5.677715  ,   6.2993903 ,  -0.21512586,
        -0.71629095,  -6.536488  ,  -6.9658046 , -16.458952  ,
        -0.42373115, -16.120197  ,  -2.988855  , -15.668289  ,
        -2.3673625 ,  -0.2796244 ,  13.241903  ,  15.173871  ,
        19.804531  ,   2.548349  ,   6.8418107 ,   8.843829  ,
         5.3165255 ,   6.7578416 ,   3.950899  ,   1.5562356 ,
        -1.1136081 ,  -3.3727527 ,  -2.6232302 ,   1.419769  ,
        -1.8182877 ,  -2.241352  ,   0.7664133 ,  -1.310072  ,
        -3.2633429 ,   0.88221025,   3.533897  ,   4.1683283 ,
         6.783082  ,  -2.349379  ,   2.6321976 ,  -0.18120557,
         3.4797752 ,  -2.8508239 ,   0.8451205 ,  -8.9011965 ,
         3.6865058 ,   0.20398574,  -1.9371088 ,  -3.4827151 ,
        -5.544328  ,  -0.6531817 ,  -2.2008953 ,   2.8286705 ,
 
Exception: ValueError('negative dimensions are not allowed')

Traceback (most recent call last):
  File "/tmp/rsmas_insar/sources/MintPy/mintpy/ifgram_inversion.py", line 1204, in <module>
    main(sys.argv[1:])
  File "/tmp/rsmas_insar/sources/MintPy/mintpy/ifgram_inversion.py", line 1193, in main
    ifgram_inversion(inps)
  File "/tmp/rsmas_insar/sources/MintPy/mintpy/ifgram_inversion.py", line 1126, in ifgram_inversion
    ts, inv_quality, num_inv_ifg = cluster_obj.run(func=ifgram_inversion_patch,
  File "/tmp/rsmas_insar/sources/MintPy/mintpy/objects/cluster.py", line 198, in run
    return self.collect_result(futures, results, box, submission_time)
  File "/tmp/rsmas_insar/sources/MintPy/mintpy/objects/cluster.py", line 245, in collect_result
    for future, sub_results in as_completed(futures, with_results=True):
  File "/tmp/rsmas_insar/3rdparty/miniconda3/lib/python3.8/site-packages/distributed/client.py", line 4332, in __next__
    return self._get_and_raise()
  File "/tmp/rsmas_insar/3rdparty/miniconda3/lib/python3.8/site-packages/distributed/client.py", line 4323, in _get_and_raise
    raise exc.with_traceback(tb)
  File "/tmp/rsmas_insar/sources/MintPy/mintpy/ifgram_inversion.py", line 821, in ifgram_inversion_patch
    mask = np.ones(num_pixel, np.bool_)
  File "/tmp/rsmas_insar/3rdparty/miniconda3/lib/python3.8/site-packages/numpy/core/numeric.py", line 203, in ones
    a = empty(shape, dtype, order)
ValueError: negative dimensions are not allowed
```

**System information**
smallbaselineApp.py --version
MintPy release version v1.3.0-14, release date 2021-04-08

* Operating system: 
* Python environment: 
* Version of MintPy: 
* Your custom / default template file (if the bug is related to a specific dataset):

**Comment by yunjunz** [comment]
I am not sure about the exact cause of this error. Setting the translation of `numWorker = all` to 2/3 of total CPUs or as #518 sounds good to me.

**Comment by yunjunz** [comment]
A fine-tuning on this default value translation makes more sense to do on the user side rather than the maintainer side because the latter does not have the access to test it.

**Comment by falkamelung** [comment]
In most cases I used ⅔ of the CPUs but in some cases this still gives an error and I have to use less. I suspect this is a fixable bug in the way we have implemented dask.  I should document the cases when it occurs.
