### ISSUE TITLE
ImportError for save_gdal.py save_qgis.py

### ISSUE THREAD

**Issue by jldz9** [insarlab/MintPy#583]
**Description of the problem**

Try to convert the result to raster and issue pop-up while testing the script
```
save_gdal.py
save_qgis.py
```

**Full script that generated the error**

```
(mintpy) jldz9@r10smithryang:~/InSAR_Sentinel_1/Quetta17_21/mintpy$ save_gdal.py velocity.h5 -g inputs/geometryRadar.h5
```
**Full error message**
```
Traceback (most recent call last):
  File "/usr/local/home/jldz9/tools/MintPy/mintpy/save_gdal.py", line 14, in <module>
    from mintpy.utils import readfile, plot as pp
  File "/usr/local/home/jldz9/tools/MintPy/mintpy/utils/plot.py", line 28, in <module>
    import pyproj
  File "/usr/local/home/jldz9/anaconda3/envs/mintpy/lib/python3.8/site-packages/pyproj/__init__.py", line 49, in <module>
    import pyproj.network
  File "/usr/local/home/jldz9/anaconda3/envs/mintpy/lib/python3.8/site-packages/pyproj/network.py", line 10, in <module>
    from pyproj._network import (  # noqa: F401
ImportError: /usr/local/home/jldz9/anaconda3/envs/mintpy/lib/python3.8/site-packages/pyproj/_network.cpython-38-x86_64-linux-gnu.so: undefined symbol: proj_context_set_ca_bundle_path

```
```
(mintpy) jldz9@r10smithryang:~/InSAR_Sentinel_1/Quetta17_21/mintpy$ save_gdal.py
```
```
Traceback (most recent call last):
  File "/usr/local/home/jldz9/tools/MintPy/mintpy/save_gdal.py", line 14, in <module>
    from mintpy.utils import readfile, plot as pp
  File "/usr/local/home/jldz9/tools/MintPy/mintpy/utils/plot.py", line 28, in <module>
    import pyproj
  File "/usr/local/home/jldz9/anaconda3/envs/mintpy/lib/python3.8/site-packages/pyproj/__init__.py", line 49, in <module>
    import pyproj.network
  File "/usr/local/home/jldz9/anaconda3/envs/mintpy/lib/python3.8/site-packages/pyproj/network.py", line 10, in <module>
    from pyproj._network import (  # noqa: F401
ImportError: /usr/local/home/jldz9/anaconda3/envs/mintpy/lib/python3.8/site-packages/pyproj/_network.cpython-38-x86_64-linux-gnu.so: undefined symbol: proj_context_set_ca_bundle_path
```
```
(mintpy) jldz9@r10smithryang:~/InSAR_Sentinel_1/Quetta17_21/mintpy$ save_qgis.py
```
```
Traceback (most recent call last):
  File "/usr/local/home/jldz9/tools/MintPy/mintpy/save_qgis.py", line 17, in <module>
    from mintpy.utils import ptime, readfile, utils as ut
  File "/usr/local/home/jldz9/tools/MintPy/mintpy/utils/utils.py", line 24, in <module>
    from mintpy.utils.utils0 import *
  File "/usr/local/home/jldz9/tools/MintPy/mintpy/utils/utils0.py", line 23, in <module>
    from pyproj import Proj, Transformer
  File "/usr/local/home/jldz9/anaconda3/envs/mintpy/lib/python3.8/site-packages/pyproj/__init__.py", line 49, in <module>
    import pyproj.network
  File "/usr/local/home/jldz9/anaconda3/envs/mintpy/lib/python3.8/site-packages/pyproj/network.py", line 10, in <module>
    from pyproj._network import (  # noqa: F401
ImportError: /usr/local/home/jldz9/anaconda3/envs/mintpy/lib/python3.8/site-packages/pyproj/_network.cpython-38-x86_64-linux-gnu.so: undefined symbol: proj_context_set_ca_bundle_path
```
```
pyproj info:
    pyproj: 3.0.1
      PROJ: 7.2.0
  data dir: /usr/local/home/jldz9/anaconda3/envs/mintpy/share/proj
user_data_dir: /usr/local/home/jldz9/.local/share/proj

System:
    python: 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05)  [GCC 9.3.0]
executable: /usr/local/home/jldz9/anaconda3/envs/mintpy/bin/python
   machine: Linux-5.4.0-73-generic-x86_64-with-glibc2.10

Python deps:
       pip: 21.1.1
setuptools: 52.0.0.post20210125
    Cython: None
```
**System information**

* Operating system:  Linux-Ubuntu20.04.2 LTS
* Python environment: Conda
* Version of MintPy: MintPy release version v1.3.0-42, release date 2021-06-03
* Your custom / default template file (if the bug is related to a specific dataset):

**Comment by yunjunz** [comment]
@jldz9 this seems like a generic conda dependencies installation issue, not a mintpy bug, you might want to try a clean conda installation process.
