### ISSUE TITLE
Prep_fringe.py list index out of range

### ISSUE THREAD

**Issue by stoormgeo** [insarlab/MintPy#595]
**Description of the problem**

Try to start the Prep_fringe.py after Fringe output

**Full script that generated the error**

```
prep_fringe.py -u '/data/insar/data/1/proc/merged/fringe/PS_DS/unwrap/*.unw' -c /data/insar/Proc/1/proc/merged/fringe/PS_DS/tcorr_ds_ps.bin -g /data/insar/Proc/1/proc/merged/fringe/geometry -m /data/insar/Proc/1/proc/reference/IW*.xml -b /data/insar/Proc/1/proc/baselines -o /data/insar/Proc/1/proc/merged/mintpy
```

**Full error message**

```
read bounding box from VRT file: /data/insar/Proc/1/proc/merged/fringe/geometry/lat.vrt as (x0, y0, x1, y1): (1194, 896, 10423, 4315)
--------------------------------------------------
extract metadata from ISCE/topsStack xml file: /data/insar/Proc/1/proc/reference/IW1.xml
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
extract metadata from geometry files: ['hgt.rdr.full', 'lat.rdr.full', 'lon.rdr.full', 'los.rdr.full']
update metadata due to subset with bounding box
update LENGTH, WIDTH, Y/XMAX
update/add SUBSET_XMIN/YMIN/XMAX/YMAX: 1194/896/10423/4315
update STARTING_RANGE
input subset in y/x: (0, 0, 9229, 3419)
update LENGTH, WIDTH, Y/XMAX
update/add SUBSET_XMIN/YMIN/XMAX/YMAX: 1194/896/10423/4315
update STARTING_RANGE
input subset in y/x with respect to the VRT file: (1194, 896, 10423, 4315)
--------------------------------------------------
preparing timeseries file: /data/insar/Proc/1/proc/merged/mintpy/timeseries.h5
number of unwrapped interferograms: 0
Traceback (most recent call last):
  File "/insar/MintPy/mintpy/prep_fringe.py", line 393, in <module>
    main(sys.argv[1:])
  File "/insar/MintPy/mintpy/prep_fringe.py", line 360, in main
    prepare_timeseries(
  File "/insar/MintPy/mintpy/prep_fringe.py", line 177, in prepare_timeseries
    ref_date = date12_list[0].split('_')[0]
IndexError: list index out of range
```

**System information**

* Operating system: Linux-Ubuntu 20.04 LTS
* Python environment: conda 
* Version of MintPy: MintPy release version v1.3.0-63, release date 2021-07-04 
* Your custom / default template file (if the bug is related to a specific dataset):

**Comment by rbiessel** [comment]
I get the same exact error if I purposely make a typo in my `-u` unwrapped glob path.

**Comment by stoormgeo** [comment]
It's really a typo. Thanks!
