### ISSUE TITLE
Issue in running MintPy example

### ISSUE THREAD

**Issue by vbrancat** [insarlab/MintPy#603]
**Description of the problem**

I am running the WellsEnvD2T399 example in MintPy. I get an error when trying to compute the temporal average of the unwrapped phase. The error seems to be related to a non-correct indexing when accessing a HDF5 file. I suspect that the file the script is trying to access avgPhaseVelocity.h5, it does not exist locally

**Full script that generated the error**

```
temporal_average.py /home/vbrancat/WellsEnvD2T399/mintpy/inputs/ifgramStack.h5 --dataset unwrapPhase -o /home/vbrancat/WellsEnvD2T399/mintpy/avgPhaseVelocity.h5 --update
```

**Full error message**

```
temporal_average.py /home/vbrancat/WellsEnvD2T399/mintpy/inputs/ifgramStack.h5 --dataset unwrapPhase -o /home/vbrancat/WellsEnvD2T399/mintpy/avgPhaseVelocity.h5
output file: /home/vbrancat/WellsEnvD2T399/mintpy/avgPhaseVelocity.h5
calculate the temporal average of unwrapPhase in file /home/vbrancat/WellsEnvD2T399/mintpy/inputs/ifgramStack.h5 ...
Traceback (most recent call last):
  File "/home/vbrancat/MintPy/mintpy/temporal_average.py", line 111, in <module>
    main(sys.argv[1:])
  File "/home/vbrancat/MintPy/mintpy/temporal_average.py", line 102, in main
    ut.temporal_average(inps.file, datasetName=inps.datasetName, outFile=inps.outfile)
  File "/home/vbrancat/MintPy/mintpy/utils/utils1.py", line 342, in temporal_average
    dataMean = ifgramStack(File).temporal_average(datasetName=datasetName)
  File "/home/vbrancat/MintPy/mintpy/objects/stack.py", line 1150, in temporal_average
    ref_val = dset[ifgram_flag, self.refY, self.refX]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/vbrancat/isce3/python/miniconda3/envs/mintpy/lib/python3.9/site-packages/h5py/_hl/dataset.py", line 752, in __getitem__
    selection = sel.select(self.shape, args, dataset=self)
  File "/home/vbrancat/isce3/python/miniconda3/envs/mintpy/lib/python3.9/site-packages/h5py/_hl/selections.py", line 82, in select
    return selector.make_selection(args)
  File "h5py/_selector.pyx", line 272, in h5py._selector.Selector.make_selection
  File "h5py/_selector.pyx", line 183, in h5py._selector.Selector.apply_args
TypeError: Indexing arrays must have integer dtypes
```

**System information**

* Operating system: Linux
* Python environment: conda, python 3.9
* Version of MintPy: MintPy release version v1.3.0-59, release date 2021-06-27
* Dataset used: WellsEnvD2T399

**Comment by yunjunz** [comment]
This is a known bug due to the lost support of fancy indexing in `h5py version 3.x`, it should be gone if you install h5py version 2.x, as noted on the installation page with the `MintPy/docs/conda.txt` file.

I tested mintpy with python 3.9 once and failed, forgot about the causes. You might want to stick to the older version for now as well. This constraint is in the conda.txt file too.

**Comment by vbrancat** [comment]
It would be nice to update the `conda` requirements https://github.com/insarlab/MintPy/blob/d58acf512e6fe7e3a0856d0e1995605e36a49a43/docs/requirements.txt#L10
and force the user to download a `h5py` lower than 3.x

**Comment by yunjunz** [comment]
I agree, will add it in the next commit.

**Comment by vbrancat** [comment]
Thanks. Reverting to h5py 2.10 solved the issue. Closing the issue :D
