### ISSUE TITLE
ts_data, meta = readfile.read('timeseries_ERA5_ramp_demErr.h5')  is not working?

### ISSUE THREAD

**Issue by mohseniaref-InSAR** [insarlab/MintPy#632]
**import 3D time series data**

**Full script that generated the error**

```

ts_data, meta = readfile.read('timeseries_ERA5_ramp_demErr.h5')
```

**Full error message**

```
Traceback (most recent call last):

  File "/tmp/ipykernel_31604/1694889393.py", line 1, in <module>
    ts_data, meta = readfile.read('timeseries_ERA5_ramp_demErr.h5')

  File "/raid-manaslu/maref/Software/python/MintPy/mintpy/utils/readfile.py", line 223, in read
    data = read_hdf5_file(fname,

  File "/raid-manaslu/maref/Software/python/MintPy/mintpy/utils/readfile.py", line 327, in read_hdf5_file
    data = ds[slice_flag,

  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "/raid-manaslu/maref/Software/anaconda3/envs/mintpyc/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 752, in __getitem__
    selection = sel.select(self.shape, args, dataset=self)

  File "/raid-manaslu/maref/Software/anaconda3/envs/mintpyc/lib/python3.8/site-packages/h5py/_hl/selections.py", line 82, in select
    return selector.make_selection(args)

  File "h5py/_selector.pyx", line 272, in h5py._selector.Selector.make_selection

  File "h5py/_selector.pyx", line 183, in h5py._selector.Selector.apply_args

TypeError: Indexing arrays must have integer dtypes
```

**Comment by yunjunz** [comment]
Hi @mohseniaref-InSAR, this is a duplicated issue related to the `h5py` version constraint. Please use `h5py<3` during installation and refer to the existing issues for more explanations.
