### ISSUE TITLE
Un-recognized ISCE processor for metadata file: auto

### ISSUE THREAD

**Issue by 764702025** [insarlab/MintPy#675]
Hello, I have processed ALOS-PALSAR data by stripmapStack.py before. I am trying to load these into MintPy using the following specifications in a template file named 484.template :

load_data.py -H to check more details and example inputs.
```cfg
mintpy.load.processor        = isce
##---------for ISCE only:
mintpy.load.metaFile         = $/media/lichengye/C14D581BDA18EBFA/data/ALOS_PALSAR/project/484/merged/SLC/20070102/referenceShelve/data.dat
mintpy.load.baselineDir      = $/media/lichengye/C14D581BDA18EBFA/data/ALOS_PALSAR/project/484/baselines
##---------interferogram datasets:
mintpy.load.unwFile          = $/media/lichengye/C14D581BDA18EBFA/data/ALOS_PALSAR/project/484/Igrams/*/filt_*.unw
mintpy.load.corFile          = $/media/lichengye/C14D581BDA18EBFA/data/ALOS_PALSAR/project/484/Igrams/*/filt_*.cor
mintpy.load.connCompFile     = $/media/lichengye/C14D581BDA18EBFA/data/ALOS_PALSAR/project/484/Igrams/*/filt_*.unw.conncomp
##---------geometry datasets:
mintpy.load.demFile          = $/media/lichengye/C14D581BDA18EBFA/data/ALOS_PALSAR/project/484/merged/geom_reference/hgt.rdr
mintpy.load.lookupYFile      = $/media/lichengye/C14D581BDA18EBFA/data/ALOS_PALSAR/project/484/merged/geom_reference/lat.rdr
mintpy.load.lookupXFile      = $/media/lichengye/C14D581BDA18EBFA/data/ALOS_PALSAR/project/484/merged/geom_reference/lon.rdr
mintpy.load.incAngleFile     = $/media/lichengye/C14D581BDA18EBFA/data/ALOS_PALSAR/project/484/merged/geom_reference/los.rdr
mintpy.load.azAngleFile      = $/media/lichengye/C14D581BDA18EBFA/data/ALOS_PALSAR/project/484/merged/geom_reference/los.rdr
mintpy.load.shadowMaskFile   = $/media/lichengye/C14D581BDA18EBFA/data/ALOS_PALSAR/project/484/merged/geom_reference/shadowMask.rdr
mintpy.load.waterMaskFile    = $/media/lichengye/C14D581BDA18EBFA/data/ALOS_PALSAR/project/484/merged/geom_reference/waterMask.rdr
mintpy.load.bperpFile        = None
```

When I run `smallbaseline.py 484.template :`
```
> load_data.py --template /media/lichengye/C14D581BDA18EBFA/data/ALOS_PALSAR/project/484/mintpy/smallbaselineApp.cfg /media/lichengye/C14D581BDA18EBFA/data/ALOS_PALSAR/project/484/mintpy/484.template --project 484
processor : isce
SAR platform/sensor : unknown from project name "484"
prepare metadata files for isce products
/home/lichengye/tools/MintPy/mintpy/load_data.py:668: UserWarning: No input metadata file found: $/media/lichengye/C14D581BDA18EBFA/data/ALOS_PALSAR/project/484/merged/SLC/20070102/referenceShelve/data.dat
  warnings.warn('No input metadata file found: {}'.format(iDict['mintpy.load.metaFile']))
Traceback (most recent call last):
  File "/home/lichengye/tools/MintPy/mintpy/smallbaselineApp.py", line 1279, in <module>
    main(sys.argv[1:])
  File "/home/lichengye/tools/MintPy/mintpy/smallbaselineApp.py", line 1261, in main
    app.run(steps=inps.runSteps)
  File "/home/lichengye/tools/MintPy/mintpy/smallbaselineApp.py", line 1030, in run
    self.run_load_data(sname)
  File "/home/lichengye/tools/MintPy/mintpy/smallbaselineApp.py", line 344, in run_load_data
    mintpy.load_data.main(iargs)
  File "/home/lichengye/tools/MintPy/mintpy/load_data.py", line 828, in main
    prepare_metadata(iDict)
  File "/home/lichengye/tools/MintPy/mintpy/load_data.py", line 680, in prepare_metadata
    processor = get_processor(meta_file)
  File "/home/lichengye/tools/MintPy/mintpy/utils/isce_utils.py", line 65, in get_processor
    raise ValueError('Un-recognized ISCE processor for metadata file: {}'.format(meta_file))
ValueError: Un-recognized ISCE processor for metadata file: auto
```

What caused such a mistake ValueError: Un-recognized ISCE processor for metadata file: auto

**Comment by yunjunz** [comment]
This is a straightforward issue, please follow the `No input metadata file found:` error msg and re-check. In addition, you should multilooked geometry files under `project/484/geom_reference`, not `project/484/merged/geom_reference`, as described in the example.

**Comment by zhuhaxixiong** [comment]
thanks for your guide that i have sucessfully solve this issue,but when i use isce 2.5.3 there are no .dir .dat .bak file in the merged/SLC/reference date/refernceShelve dir, but only a data.db file.
