### ISSUE TITLE
subset using Lat/Lon for hyp3 product fails with loading gdal

### ISSUE THREAD

**Issue by amitgajurel** [insarlab/MintPy#678]
When specifying the Lat/Lon in configuration file "mintpy.subset.lalo" (i.e. in case of hyp3 product is the UTM), the reference document has the values specified as UTM co-ordinates but will fail in subsequent step (when loading gdal). 

I did find a workaround i.e. after running this script, the radar co-ordinate is displayed in the prompt. One can use that as the subset and run the whole thing. But I am opening this issue to let all of you that there exists a small bug which I believe should be simple fix ( I am still new to this thing but would like to contribute). I would really appreciate any response from @yunjunz or @forrestfwilliams  regarding this. I really appreciate any help. 

```
!smallbaselineApp.py denison.txt --dostep load_data

```

```
MintPy release version v1.3.1, release date 2021-08-02
--RUN-at-2021-10-10 21:22:30.635949--
Current directory: /home/jovyan/denisonsar/hyp3processing/mintpy2
Run routine processing with smallbaselineApp.py on steps: ['load_data']
Remaining steps: ['modify_network', 'reference_point', 'quick_overview', 'correct_unwrap_error', 'invert_network', 'correct_LOD', 'correct_SET', 'correct_troposphere', 'deramp', 'correct_topography', 'residual_RMS', 'reference_date', 'velocity', 'geocode', 'google_earth', 'hdfeos5']
--------------------------------------------------
Project name: denison
Go to work directory: /home/jovyan/denisonsar/hyp3processing/mintpy2
copy default template file /home/jovyan/.local/MintPy/mintpy/defaults/smallbaselineApp.cfg to work directory
read custom template file: /home/jovyan/denisonsar/hyp3processing/mintpy2/denison.txt
update default template based on input custom template
    mintpy.compute.maxMemory: auto --> 25
    mintpy.compute.cluster: auto --> local
    mintpy.load.processor: auto --> hyp3
    mintpy.load.unwFile: auto --> ../hyp3/*/*unw_phase_clip.tif
    mintpy.load.corFile: auto --> ../hyp3/*/*corr_clip.tif
    mintpy.load.demFile: auto --> ../hyp3/*/*dem_clip.tif
    mintpy.load.incAngleFile: auto --> ../hyp3/*/*lv_theta_clip.tif
    mintpy.load.waterMaskFile: auto --> ../hyp3/*/*water_mask_clip.tif
    mintpy.subset.lalo: auto --> 3740.482e3:3742.352e3,724.157e3:725.746e3
    mintpy.networkInversion.weightFunc: auto --> var
    mintpy.troposphericDelay.method: auto --> pyaps
    mintpy.topographicResidual: auto --> yes
    mintpy.topographicResidual.pixelwiseGeometry: auto --> yes
copy denison.txt to inputs   directory for backup.
copy smallbaselineApp.cfg to inputs   directory for backup.
copy denison.txt to pic      directory for backup.
copy smallbaselineApp.cfg to pic      directory for backup.
read default template file: /home/jovyan/denisonsar/hyp3processing/mintpy2/smallbaselineApp.cfg


******************** step - load_data ********************

load_data.py --template /home/jovyan/denisonsar/hyp3processing/mintpy2/smallbaselineApp.cfg /home/jovyan/denisonsar/hyp3processing/mintpy2/denison.txt --project denison
processor : hyp3
SAR platform/sensor : unknown from project name "denison"
--------------------------------------------------
prepare metadata files for hyp3 products
prep_hyp3.py ../hyp3/*/*unw_phase_clip.tif
prep_hyp3.py ../hyp3/*/*corr_clip.tif
prep_hyp3.py ../hyp3/*/*dem_clip.tif
prep_hyp3.py ../hyp3/*/*lv_theta_clip.tif
prep_hyp3.py ../hyp3/*/*water_mask_clip.tif
input bounding box of interest in lalo: (724157.0, 3742352.0, 725746.0, 3740482.0)
box to read for datasets in y/x: (3835, 1165, 3875, 1211)
--------------------------------------------------
searching interferometric pairs info
input data files:
unwrapPhase     : ../hyp3/*/*unw_phase_clip.tif
coherence       : ../hyp3/*/*corr_clip.tif
number of unwrapPhase     : 744
number of coherence       : 744
--------------------------------------------------
searching geometry files info
input data files:
height          : ../hyp3/S1AA_20150524T002722_20150605T002723_VVP012_INT40_G_ueF_3F14/S1AA_20150524T002722_20150605T002723_VVP012_INT40_G_ueF_3F14_dem_clip.tif
incidenceAngle  : ../hyp3/S1AA_20150524T002722_20150605T002723_VVP012_INT40_G_ueF_3F14/S1AA_20150524T002722_20150605T002723_VVP012_INT40_G_ueF_3F14_lv_theta_clip.tif
waterMask       : ../hyp3/S1AA_20150524T002722_20150605T002723_VVP012_INT40_G_ueF_3F14/S1AA_20150524T002722_20150605T002723_VVP012_INT40_G_ueF_3F14_water_mask_clip.tif
--------------------------------------------------
updateMode : True
compression: None
x/ystep: 1/1
--------------------------------------------------
create HDF5 file /home/jovyan/denisonsar/hyp3processing/mintpy2/inputs/ifgramStack.h5 with w mode
create dataset /unwrapPhase of <class 'numpy.float32'>   in size of (742, 46, 40) with compression = None
Traceback (most recent call last):
  File "/home/jovyan/.local/MintPy/mintpy/smallbaselineApp.py", line 1268, in <module>
    main(sys.argv[1:])
  File "/home/jovyan/.local/MintPy/mintpy/smallbaselineApp.py", line 1250, in main
    app.run(steps=inps.runSteps)
  File "/home/jovyan/.local/MintPy/mintpy/smallbaselineApp.py", line 1030, in run
    self.run_load_data(sname)
  File "/home/jovyan/.local/MintPy/mintpy/smallbaselineApp.py", line 344, in run_load_data
    mintpy.load_data.main(iargs)
  File "/home/jovyan/.local/MintPy/mintpy/load_data.py", line 847, in main
    stackObj.write2hdf5(outputFile=inps.outfile[0],
  File "/home/jovyan/.local/MintPy/mintpy/objects/stackDict.py", line 148, in write2hdf5
    data = ifgramObj.read(dsName,
  File "/home/jovyan/.local/MintPy/mintpy/objects/stackDict.py", line 255, in read
    data, metadata = readfile.read(self.file,
  File "/home/jovyan/.local/MintPy/mintpy/utils/readfile.py", line 244, in read
    data, atr = read_binary_file(fname,
  File "/home/jovyan/.local/MintPy/mintpy/utils/readfile.py", line 543, in read_binary_file
    data = read_gdal(
  File "/home/jovyan/.local/MintPy/mintpy/utils/readfile.py", line 1542, in read_gdal
    data = bnd.ReadAsArray(**kwargs)
  File "/home/jovyan/.local/envs/unavco/lib/python3.8/site-packages/osgeo/gdal.py", line 3834, in ReadAsArray
    return gdalnumeric.BandReadAsArray(self, xoff, yoff,
  File "/home/jovyan/.local/envs/unavco/lib/python3.8/site-packages/osgeo/gdal_array.py", line 406, in BandReadAsArray
    if BandRasterIONumPy(band, 0, xoff, yoff, win_xsize, win_ysize,
  File "/home/jovyan/.local/envs/unavco/lib/python3.8/site-packages/osgeo/gdal_array.py", line 154, in BandRasterIONumPy
    return _gdal_array.BandRasterIONumPy(band, bWrite, xoff, yoff, xsize, ysize, psArray, buf_type, resample_alg, callback, callback_data)
TypeError: in method 'BandRasterIONumPy', argument 3 of type 'double'
```

```
TypeError: in method 'BandRasterIONumPy', argument 3 of type 'double'
```

**System information**
UNAVCO2021 Docker Image

[denison.txt](https://github.com/insarlab/MintPy/files/7318282/denison.txt)

**Comment by yunjunz** [comment]
Close this issue as it is confirmed to be resolved.
