### ISSUE TITLE
geocode.py on swbdLat_*.wbd fails

### ISSUE THREAD

**Issue by EJFielding** [insarlab/MintPy#681]
**Description of the problem**

I ran the ISCE2 stackSentinel workflow to generate a stack of interferograms in radar coordinates, and I loaded it successfully into MintPy. Now I would like to generate a water mask with the command recommended in the tutorial that runs `geocode.py` on the SRTM swbdLat_*.wbd file to project that into the stack radar coordinates, but it fails to write the output file.

**Full script that generated the error**

```
geocode.py /u/sar-r0/fielding/Mexico/topo/wbd_1_arcsec/swbdLat_N15_N20_Lon_W102_W093.wbd -l inputs/geometryRadar.h5 -o waterBody.h5 --geo2radar
```

**Full error message**

```
number of processor to be used: 1
resampling software: pyresample
read latitude / longitude from lookup table file: inputs/geometryRadar.h5
input pixel size in (lat, lon) in degree: [-0.0002777777777777778, 0.0002777777777777778]
input area extent in (S, N, W, E) in degree: (15.000138888888888, 20.000138888888888, -102.00013888888888, -93.00013888888888)
--------------------------------------------------
resampling file: /u/sar-r0/fielding/Mexico/topo/wbd_1_arcsec/swbdLat_N15_N20_Lon_W102_W093.wbd
--------------------------------------------------
Traceback (most recent call last):
  File "/home/fielding/tools/MintPy/mintpy/geocode.py", line 376, in <module>
    main(sys.argv[1:])
  File "/home/fielding/tools/MintPy/mintpy/geocode.py", line 369, in main
    run_geocode(inps)
  File "/home/fielding/tools/MintPy/mintpy/geocode.py", line 298, in run_geocode
    writefile.layout_hdf5(outfile, metadata=atr, ref_file=infile, compression=compression)
  File "/home/fielding/tools/MintPy/mintpy/utils/writefile.py", line 313, in layout_hdf5
    raise ValueError('No ds_name_dict or ref_file found.')
ValueError: No ds_name_dict or ref_file found.
```

**System information**

* Operating system:  Linux-CentOS
* Python environment:  conda 
* Version of MintPy:  MintPy release version v1.2.3-290, release date 2021-10-16
* Your custom / default template file (if the bug is related to a specific dataset): 
[AcapulcoSenD041.txt](https://github.com/insarlab/MintPy/files/7361143/AcapulcoSenD041.txt)

**Comment by EJFielding** [comment]
Thank you @yunjunz for the fast bug fix! 
It works great again now.
