### ISSUE TITLE
Indexing arrays must have integer dtypes

### ISSUE THREAD

**Issue by EJFielding** [insarlab/MintPy#741]
**Description of the problem**

Network inversion step of smallbaselineApp fails.

**Full script that generated the error**

```
smallbaselineApp.py --dostep invert_network
```

**Full error message**

```
MintPy version v1.3.2, date 2021-11-21
--RUN-at-2022-02-09 00:04:16.013738--
Current directory: /home/jovyan/SES/calval/central_valley/MintPy
Run routine processing with smallbaselineApp.py on steps: ['invert_network']
Remaining steps: ['correct_LOD', 'correct_SET', 'correct_troposphere', 'deramp', 'correct_topography', 'residual_RMS', 'reference_date', 'velocity', 'geocode', 'google_earth', 'hdfeos5']
--------------------------------------------------
Project name: central_valley_Sen
Go to work directory: /home/jovyan/SES/calval/central_valley/MintPy
read custom template file: /home/jovyan/SES/calval/central_valley/MintPy/central_valley_Sen.cfg
update default template based on input custom template
No new option value found, skip updating /home/jovyan/SES/calval/central_valley/MintPy/smallbaselineApp.cfg
read default template file: /home/jovyan/SES/calval/central_valley/MintPy/smallbaselineApp.cfg


******************** step - invert_network ********************
Input data seems to be geocoded. Lookup file not needed.

ifgram_inversion.py /home/jovyan/SES/calval/central_valley/MintPy/inputs/ifgramStack.h5 -t /home/jovyan/SES/calval/central_valley/MintPy/smallbaselineApp.cfg --update
use dataset "unwrapPhase" by default
--------------------------------------------------
update mode: ON
1) NOT ALL output files found: ['timeseries.h5', 'temporalCoherence.h5', 'numInvIfgram.h5'].
run or skip: run.
save the original settings of ['OMP_NUM_THREADS', 'OPENBLAS_NUM_THREADS', 'MKL_NUM_THREADS', 'NUMEXPR_NUM_THREADS', 'VECLIB_MAXIMUM_THREADS']
set OMP_NUM_THREADS = 1
set OPENBLAS_NUM_THREADS = 1
set MKL_NUM_THREADS = 1
set NUMEXPR_NUM_THREADS = 1
set VECLIB_MAXIMUM_THREADS = 1
reference pixel in y/x: (803, 231) from dataset: unwrapPhase
Traceback (most recent call last):
  File "/home/jovyan/.local/envs/mintpy/bin/smallbaselineApp.py", line 8, in <module>
    sys.exit(main())
  File "/home/jovyan/.local/envs/mintpy/lib/python3.9/site-packages/mintpy/smallbaselineApp.py", line 1275, in main
    app.run(steps=inps.runSteps)
  File "/home/jovyan/.local/envs/mintpy/lib/python3.9/site-packages/mintpy/smallbaselineApp.py", line 1055, in run
    self.run_network_inversion(sname)
  File "/home/jovyan/.local/envs/mintpy/lib/python3.9/site-packages/mintpy/smallbaselineApp.py", line 561, in run_network_inversion
    mintpy.ifgram_inversion.main(iargs)
  File "/home/jovyan/.local/envs/mintpy/lib/python3.9/site-packages/mintpy/ifgram_inversion.py", line 1425, in main
    ifgram_inversion(inps)
  File "/home/jovyan/.local/envs/mintpy/lib/python3.9/site-packages/mintpy/ifgram_inversion.py", line 1197, in ifgram_inversion
    inps.refPhase = stack_obj.get_reference_phase(unwDatasetName=inps.obsDatasetName,
  File "/home/jovyan/.local/envs/mintpy/lib/python3.9/site-packages/mintpy/objects/stack.py", line 870, in get_reference_phase
    ref_phase = self.read(datasetName=unwDatasetName,
  File "/home/jovyan/.local/envs/mintpy/lib/python3.9/site-packages/mintpy/objects/stack.py", line 763, in read
    data = ds[dateFlag,
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/jovyan/.local/envs/mintpy/lib/python3.9/site-packages/h5py/_hl/dataset.py", line 783, in __getitem__
    selection = sel.select(self.shape, args, dataset=self)
  File "/home/jovyan/.local/envs/mintpy/lib/python3.9/site-packages/h5py/_hl/selections.py", line 82, in select
    return selector.make_selection(args)
  File "h5py/_selector.pyx", line 272, in h5py._selector.Selector.make_selection
  File "h5py/_selector.pyx", line 183, in h5py._selector.Selector.apply_args
TypeError: Indexing arrays must have integer dtypes
```

**System information**

* Operating system:  Linux (NISAR On-demand instance)
* Python environment:  Conda
* Version of MintPy:  MintPy version v1.3.2, date 2021-11-21
* Your custom / default template file (if the bug is related to a specific dataset): 
[central_valley_Sen.txt](https://github.com/insarlab/MintPy/files/8028502/central_valley_Sen.txt)

**Comment by bbuzz31** [comment]
Hi @EJFielding I recently encountered this as well (https://github.com/insarlab/MintPy/pull/735#issuecomment-1028629796). Believe you should be able to get around it by downgrading h5py `h5py<3`

**Comment by EJFielding** [comment]
Thanks @bbuzz31 for the hint. I tried `conda install "h5py<3" and it found a huge number of conflicts. We have been using a conda_env.yml file with:
```
  - pip:
    - ansiwrap
    - appdirs
    - git+https://github.com/aria-tools/ARIA-tools.git
    - git+https://github.com/insarlab/MintPy.git
    - git+https://github.com/yunjunz/pyaps3.git
```

**Comment by scottstanie** [comment]
Since it's becoming more and more difficult for everyone to keep the correct version as other libraries use version 3.0, does it make sense to just add the fix where you convert the indexes to integers? Or would that definitely mess something else up? Changing it in a couple places in my fork worked for me (but I didn't extensively test it)

**Comment by yunjunz** [comment]
Yes, we should use the fix. Most of the occurrences, if not all, has been marked here (https://github.com/insarlab/MintPy/pull/470). 

From:

```python
data = ds[flag, y0:y1, x0:x1]
```

To:

```python
data = ds[:, y0:y1, x0:x1][flag]
```

I did not use the recommend `ds[flag.nonzero()[0], y0:y1, x0:x1]` because `flag.nonzero()[0]` gives a list of index, which can be very slow when the list is long, if I remember it right. 

Pull requests are welcomed!

**Comment by EJFielding** [comment]
Thanks @bbuzz31 for the fast fix and @yunjunz for the review and merge.

They already changed the conda installation on the NISAR On-demand system to install MintPy a different way that also installs an older `h5py`. It also finishes the conda environment installation in about 5 minutes instead of three hours, so I don't want to try re-running the old installation and I can't test this new version of MintPy right away.
