### ISSUE TITLE
Python3.9 support

### ISSUE THREAD

**Issue by yunjunz** [insarlab/MintPy#747]
I am testing mintpy in python 3.9. After [relaxing python version constraint in the requirements.txt](https://github.com/yunjunz/MintPy/commit/d88bac1), I installed mintpy development version as below, similar to what we have in `.circleci/config.yml`:

```bash
mamba install --file tools/MintPy/docs/requirements.txt gdal">=3" python"=3.9"
```

Local testings of `$MINTPY_HOME/tests/test_smallbaselineApp.py` on macOS and Linux passed without error, but somehow the [circle CI test](https://app.circleci.com/pipelines/github/yunjunz/MintPy/988/workflows/34c31473-36c2-4807-b80d-2e6b0280aa9f/jobs/986?invite=true#step-106-112) failed with the following error:

```
prepare metadata files for aria products
Traceback (most recent call last):
  File "/root/tools/miniconda3/lib/python3.9/site-packages/osgeo/__init__.py", line 29, in swig_import_helper
    return importlib.import_module(mname)
  File "/root/tools/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1173, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: /root/tools/miniconda3/lib/python3.9/site-packages/osgeo/../../../libgdal.so.30: undefined symbol: _ZN21GfxICCBasedColorSpace15buildTransformsEP8GfxState

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/tools/miniconda3/lib/python3.9/site-packages/mintpy/prep_aria.py", line 18, in <module>
    from osgeo import gdal
  File "/root/tools/miniconda3/lib/python3.9/site-packages/osgeo/__init__.py", line 45, in <module>
    _gdal = swig_import_helper()
  File "/root/tools/miniconda3/lib/python3.9/site-packages/osgeo/__init__.py", line 42, in swig_import_helper
    return importlib.import_module('_gdal')
  File "/root/tools/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_gdal'
```

This seems to be related to the GDAL Python binding, as described here: https://stackoverflow.com/questions/44005694/no-module-named-gdal.

**Comment by piyushrpt** [comment]
Check `poppler` version in the environment that gets created.

**Comment by yunjunz** [comment]
After activating the strict channel priority as below, circle CI starts to install poppler version 22 from conda-forge channel, and [testing passed](https://app.circleci.com/pipelines/github/yunjunz/MintPy/989)! Thank you @piyushrpt for the insight!

```bash
conda config --set channel_priority strict
```
