### ISSUE TITLE
GPS query timeout

### ISSUE THREAD

**Issue by sssangha** [insarlab/MintPy#776]
**Description of the problem**

Whenever I attempt to query GPS stations for a given area and time to replicate some previous efforts, I encounter a timeout error.

Not sure if this is transient, but this has been going on throughout the day and others that ran it before me today went through just fine.

**Full script that generated the error**

```
from mintpy.objects import gps
site_names, site_lats, site_lons = gps.search_gps(SNWE=(34.660417043, 35.60125, -116.620416667, -114.389584226), start_date='20180105', end_date='20181231')
```

**Full error message**

```
downloading site list from UNR Geod Lab: http://geodesy.unr.edu/NGLStationPages/DataHoldings.txt
Traceback (most recent call last):
  File "/Users/ssangha/Downloads/snap_setup/stable_oct5_2021/envs/mintpy/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Users/ssangha/Downloads/snap_setup/stable_oct5_2021/envs/mintpy/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/ssangha/Downloads/snap_setup/stable_oct5_2021/envs/mintpy/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/ssangha/Downloads/snap_setup/stable_oct5_2021/envs/mintpy/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/ssangha/Downloads/snap_setup/stable_oct5_2021/envs/mintpy/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/Users/ssangha/Downloads/snap_setup/stable_oct5_2021/envs/mintpy/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/Users/ssangha/Downloads/snap_setup/stable_oct5_2021/envs/mintpy/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/Users/ssangha/Downloads/snap_setup/stable_oct5_2021/envs/mintpy/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/Users/ssangha/Downloads/snap_setup/stable_oct5_2021/envs/mintpy/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ssangha/Downloads/snap_setup/stable_oct5_2021/MintPy/mintpy/objects/gps.py", line 53, in search_gps
    dload_site_list(site_list_file, print_msg=print_msg)
  File "/Users/ssangha/Downloads/snap_setup/stable_oct5_2021/MintPy/mintpy/objects/gps.py", line 33, in dload_site_list
    urlretrieve(url, out_file)
  File "/Users/ssangha/Downloads/snap_setup/stable_oct5_2021/envs/mintpy/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Users/ssangha/Downloads/snap_setup/stable_oct5_2021/envs/mintpy/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/ssangha/Downloads/snap_setup/stable_oct5_2021/envs/mintpy/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Users/ssangha/Downloads/snap_setup/stable_oct5_2021/envs/mintpy/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Users/ssangha/Downloads/snap_setup/stable_oct5_2021/envs/mintpy/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Users/ssangha/Downloads/snap_setup/stable_oct5_2021/envs/mintpy/lib/python3.8/urllib/request.py", line 1383, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/Users/ssangha/Downloads/snap_setup/stable_oct5_2021/envs/mintpy/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 60] Operation timed out>
```

**System information**

* Operating system: replicated on both macOS and Linux-CentOS
* Python environment: conda
* Version of MintPy: MintPy version v1.3.3-10, date 2022-05-22

**Comment by yunjunz** [comment]
Thank you for reporting this issue @sssangha. It seems that the UNR GNSS website (http://geodesy.unr.edu/NGLStationPages/gpsnetmap/GPSNetMap.html) is down. I just tried and could not open it. Maybe sending them an email?

**Comment by sssangha** [comment]
@yunjunz as an update, I just received the following response from the UNR team:
"Our web server is down, apparently damaged by a power outage event.

We have managed to port the web server to a different machine, but we are waiting for IT to have it respond to [geodesy.unr.edu](http://geodesy.unr.edu/) and have the http port open through the campus firewall.   

Unfortunately it is a holiday weekend, so its possible this will not happen until next week."
