### ISSUE TITLE
SNAP and MintPy "WARNING unwrapPhase/coherence file missing for pair"

### ISSUE THREAD

**Issue by periglacial** [insarlab/MintPy#782]
**Description of the problem**

Hello,
I'm trying to load a stack of geocoded interferograms into MintPy that I prepared using SNAP (snappy). However, the 'load_data' step in 'smallbaselineApp.py' returns a 'file missing for pair' warning for the entire stack. I have checked the size of every coherence and unwrapped phase images, including the DEM and they all have the same size (according to SNAP). I have followed the recipe for preparing a stack of geocoded interferograms https://github.com/insarlab/MintPy/wiki/SNAP-input-data and https://mintpy.readthedocs.io/en/latest/dir_structure/#snap. 

Here is the data and configuration file I used (in the recommended data structure): 
[mintpy_chexinlun.zip](https://github.com/insarlab/MintPy/files/8769874/mintpy_chexinlun.zip)

The configuration file:
 [chexinlun.txt](https://github.com/insarlab/MintPy/files/8769861/chexinlun.txt)

I'm aware that the 'file missing for pair' warning has been raised before https://github.com/insarlab/MintPy/issues/296 but unfortunately the issue was closed with no solution.

To add, when I use the example dataset ('Sentinel-1 on Western Cape, South Africa with SNAP') https://mintpy.readthedocs.io/en/latest/demo_dataset/ the 'load_data' step runs successfully with no 'file missing for pair' warning.

Thank you in advance for your help!

**Full script that generated the error**

```
import os
import numpy as np
import matplotlib.pyplot as plt
from mintpy.objects import ifgramStack
from mintpy.utils import plot as pp, utils as ut
from mintpy import view, plot_network
from mintpy.unwrap_error_phase_closure import plot_num_triplet_with_nonzero_integer_ambiguity

# define work directory
work_dir = os.path.expanduser('/home/huw/Documents/mintpy_chexinlun/mintpy')
os.makedirs(work_dir, exist_ok=True)
os.chdir(work_dir)
print('Go to work directory: {}'.format(work_dir))

# run load_data
!smallbaselineApp.py chexinlun.txt --dostep load_data
```

**Full error message**

```
MintPy version v1.3.3, date 2022-04-14
--RUN-at-2022-05-25 14:34:42.782494--
Current directory: /home/huw/Documents/mintpy_chexinlun/mintpy
Run routine processing with smallbaselineApp.py on steps: ['load_data']
Remaining steps: ['modify_network', 'reference_point', 'quick_overview', 'correct_unwrap_error', 'invert_network', 'correct_LOD', 'correct_SET', 'correct_troposphere', 'deramp', 'correct_topography', 'residual_RMS', 'reference_date', 'velocity', 'geocode', 'google_earth', 'hdfeos5']
--------------------------------------------------
Project name: chexinlun
Go to work directory: /home/huw/Documents/mintpy_chexinlun/mintpy
read custom template file: /home/huw/Documents/mintpy_chexinlun/mintpy/chexinlun.txt
update default template based on input custom template
No new option value found, skip updating /home/huw/Documents/mintpy_chexinlun/mintpy/smallbaselineApp.cfg
read default template file: /home/huw/Documents/mintpy_chexinlun/mintpy/smallbaselineApp.cfg


******************** step - load_data ********************

load_data.py --template /home/huw/Documents/mintpy_chexinlun/mintpy/smallbaselineApp.cfg /home/huw/Documents/mintpy_chexinlun/mintpy/chexinlun.txt --project chexinlun
processor : snap
SAR platform/sensor : unknown from project name "chexinlun"
--------------------------------------------------
prepare metadata files for snap products
prep_snap.py ../interferograms/*/*/Unw_*.img
prep_snap.py ../interferograms/*/*/coh_*.img
prep_snap.py ../dem*/elevation*.img

********************************************************************************
WARNING: NOT all input unwrapped interferograms have the same row/column number!
Minimum size is: (166, 226)
------------------------------
The following dates have different size:
------------------------------
Assuming the interferograms above have:
	extra line(s) at the bottom OR
	extra column(s) at the right
Continue to load data using subset of the minimum size.
********************************************************************************

box to read for datasets in y/x: (0, 0, 226, 166)
--------------------------------------------------
searching interferometric pairs info
input data files:
unwrapPhase     : ../interferograms/*/*/Unw_*.img
coherence       : ../interferograms/*/*/coh_*.img
number of unwrapPhase     : 3
number of coherence       : 3
WARNING:        unwrapPhase file missing for pair ['190105', '190210']
WARNING:          coherence file missing for pair ['190105', '190210']
WARNING:        unwrapPhase file missing for pair ['190105', '190117']
WARNING:          coherence file missing for pair ['190105', '190117']
WARNING:        unwrapPhase file missing for pair ['190105', '190129']
WARNING:          coherence file missing for pair ['190105', '190129']
--------------------------------------------------
searching geometry files info
input data files:
height          : ../dem_tc.data/elevation.img
--------------------------------------------------
updateMode : True
compression: None
x/ystep: 1/1
--------------------------------------------------
Traceback (most recent call last):
  File "/home/huw/miniconda3/envs/py39/bin/smallbaselineApp.py", line 10, in <module>
    sys.exit(main())
  File "/home/huw/miniconda3/envs/py39/lib/python3.9/site-packages/mintpy/smallbaselineApp.py", line 1275, in main
    app.run(steps=inps.runSteps)
  File "/home/huw/miniconda3/envs/py39/lib/python3.9/site-packages/mintpy/smallbaselineApp.py", line 1040, in run
    self.run_load_data(sname)
  File "/home/huw/miniconda3/envs/py39/lib/python3.9/site-packages/mintpy/smallbaselineApp.py", line 349, in run_load_data
    mintpy.load_data.main(iargs)
  File "/home/huw/miniconda3/envs/py39/lib/python3.9/site-packages/mintpy/load_data.py", line 853, in main
    stackObj.write2hdf5(outputFile=inps.outfile[0],
  File "/home/huw/miniconda3/envs/py39/lib/python3.9/site-packages/mintpy/objects/stackDict.py", line 112, in write2hdf5
    maxDigit = max([len(i) for i in self.dsNames])
ValueError: max() arg is an empty sequence

```

**System information**

* Operating system: Linux-Ubuntu 20.04.4 LTS
* Python environment: conda 4.10.3 python 3.9.12
* Version of MintPy: v1.3.3, date 2022-04-14
* Version of snappy: 1.1.9

**Comment by yunjunz** [comment]
@periglacial I was able to reproduce the error you have with your attached dataset. The issue is because the date12 format of the interferogram folders are in DDMMYYYY; after changing it to YYYYMMDD, it works. Cheers.

**Comment by periglacial** [comment]
@yunjunz Thank you for looking into this. Your solution works, I can't believe it was something so simple!
