### ISSUE TITLE
Error : "PyAPS: Mask array size mismatch" 

### ISSUE THREAD

**Issue by zNevermind** [insarlab/MintPy#830]
I'm trying to run Mintpy with GMTSAR processor. When I finish downloading the ERA files and run **tropo_pyaps3.py**, it print the error.

Error:

calculating absolute delay for each date using PyAPS (Jolivet et al., 2011; 2014) ...
number of grib files used: 30
Traceback (most recent call last):
  File "/home/zzd/.conda/envs/mintpy/bin/tropo_pyaps3.py", line 8, in <module>
    sys.exit(main())
  File "/home/zzd/.conda/envs/mintpy/lib/python3.8/site-packages/mintpy/tropo_pyaps3.py", line 846, in main
    calc_delay_timeseries(inps)
  File "/home/zzd/.conda/envs/mintpy/lib/python3.8/site-packages/mintpy/tropo_pyaps3.py", line 764, in calc_delay_timeseries
    tropo_data = get_delay(grib_file,
  File "/home/zzd/.conda/envs/mintpy/lib/python3.8/site-packages/mintpy/tropo_pyaps3.py", line 631, in get_delay
    aps_obj = pa.PyAPS(grib_file,
  File "/home/zzd/.conda/envs/mintpy/lib/python3.8/site-packages/pyaps3/objects.py", line 84, in __init__
    assert self.mask.shape == (self.ny, self.nx), 'PyAPS: Mask array size mismatch'
AssertionError: PyAPS: **Mask array size mismatch**

How to solve this problem?
Thanks.

**Comment by yunjunz** [comment]
This seems likely to be caused by different sizes between the loaded interferograms and loaded geometry datasets. Please make sure they are all in the same grid, i.e. same spatial extent/coverage, same spatial resolution, and same row/column number.

**Comment by zNevermind** [comment]
> This seems likely to be caused by different sizes between the loaded interferograms and loaded geometry datasets. Please make sure they are all in the same grid before loading into mintpy, i.e. same spatial extent/coverage, same spatial resolution, and same row/column number.

Thank you for your help. I will try it.
