### ISSUE TITLE
Bug report when processing hyp3 with bridging method in correct_unwrap_error

### ISSUE THREAD

**Issue by Arctic-Ambrun** [insarlab/MintPy#832]
**Description of the problem**

Seems there`s no [ connectComponent ] when using bridging method with data build with hyp3 products.
https://github.com/insarlab/MintPy/blob/36a083521b39d9fb557741f9c5d703b7e42448c3/mintpy/unwrap_error_bridging.py#L243

the ccName need to be transfered as 'unwrapPhase' above the Line 243

My suggestion is to add the judgment of hyp3  product, or maybe the issue due to the generation of ifgram.h5

Code:

correct unwrapping error in /mnt/Disk2/0_ASF_SBAS_WOLF/asc_whole_mintpy/inputs/ifgramStack.h5 with bridging ...
read water mask from file: waterMask.h5
open /mnt/Disk2/0_ASF_SBAS_WOLF/asc_whole_mintpy/inputs/ifgramStack.h5 with r+ mode
input  dataset: unwrapPhase
output dataset: unwrapPhase_bridging
create /unwrapPhase_bridging of np.float32 in size of (1026, 2080, 1941)
Traceback (most recent call last):
  File "/home/wjg/anaconda3/envs/AM_manual/bin/smallbaselineApp.py", line 33, in <module>
    sys.exit(load_entry_point('mintpy==1.3.3', 'console_scripts', 'smallbaselineApp.py')())
  File "/home/wjg/anaconda3/envs/AM_manual/lib/python3.8/site-packages/mintpy-1.3.3-py3.8.egg/mintpy/smallbaselineApp.py", line 1275, in main
    app.run(steps=inps.runSteps)
  File "/home/wjg/anaconda3/envs/AM_manual/lib/python3.8/site-packages/mintpy-1.3.3-py3.8.egg/mintpy/smallbaselineApp.py", line 1052, in run
    self.run_unwrap_error_correction(sname)
  File "/home/wjg/anaconda3/envs/AM_manual/lib/python3.8/site-packages/mintpy-1.3.3-py3.8.egg/mintpy/smallbaselineApp.py", line 528, in run_unwrap_error_correction
    mintpy.unwrap_error_bridging.main(iargs_bridge)
  File "/home/wjg/anaconda3/envs/AM_manual/lib/python3.8/site-packages/mintpy-1.3.3-py3.8.egg/mintpy/unwrap_error_bridging.py", line 300, in main
    run_unwrap_error_bridge(inps.ifgram_file,
  File "/home/wjg/anaconda3/envs/AM_manual/lib/python3.8/site-packages/mintpy-1.3.3-py3.8.egg/mintpy/unwrap_error_bridging.py", line 244, in run_unwrap_error_bridge
    cc = np.squeeze(f[ccName][i, :, :])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/wjg/anaconda3/envs/AM_manual/lib/python3.8/site-packages/h5py/_hl/group.py", line 328, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'connectComponent' doesn't exist)"

```
PASTE CODE HERE
```

**Full error message**

```
PASTE ERROR MESSAGE HERE
```

**System information**

* Operating system: 
* Python environment: 
* Version of MintPy: <!1.3.3 -->
* Your custom / default template file (if the bug is related to a specific dataset):

**Comment by Arctic-Ambrun** [comment]
After changing the dataset name from 'connectComponent' to 'unwrapPhase'

**Comment by Arctic-Ambrun** [comment]
@yunjunz Dear Yunjun, May I ask a question? Does hyp3 product contains  conn comp file? It is werid that some of the bridging file is written but some were failed. An image was uploaded named unwrapPhase_bridging_1.pn
![unwrapPhase_bridging_1](https://user-images.githubusercontent.com/81725312/185743553-f6a3c7d8-816a-4d20-bab8-f3e0133b6b5d.png)
g

**Comment by Arctic-Ambrun** [comment]
maybe I`m wrong, the hyp3 product does not contains connectComponent data, so for HYP3 The process is stoped??

**Comment by yunjunz** [comment]
HyP3 InSAR products are generated using Gamma, which does not provide connected components info. Thus, the phase unwrapping error correction methods can not be used. 

The same constraint applies to Gamma, GMTSAR also, as far as I am aware. https://mintpy.readthedocs.io/en/latest/dir_structure/#asf_hyp3

**Comment by Arctic-Ambrun** [comment]
Thank you for your kindhearted help, Mr.Yunjun
