### ISSUE TITLE
`mintpy.geocode.SNWE = []` typo induced error

### ISSUE THREAD

**Issue by javjrg** [insarlab/MintPy#872]
**I try to run the model using geocode following the configuration:**

```
########## 11.1 geocode (post-processing)
# for input dataset in radar coordinates only
# commonly used resolution in meters and in degrees (on equator)
# 100,         60,          50,          30,          20,          10
# 0.000925926, 0.000555556, 0.000462963, 0.000277778, 0.000185185, 0.000092593
mintpy.geocode              = auto  #[yes / no], auto for yes
mintpy.geocode.SNWE         = [-27.48,-27.45,-70.29,-70.26] #[-1.2,0.5,-92,-91 / none ], auto for none, output extent in degree
mintpy.geocode.laloStep     = auto  #[-0.000555556,0.000555556 / None], auto for None, output resolution in degree
mintpy.geocode.interpMethod = auto  #[nearest], auto for nearest, interpolation method
mintpy.geocode.fillValue    = auto  #[np.nan, 0, ...], auto for np.nan, fill value for outliers.
```

**But I have the following error:**

```
******************** step - geocode ********************

geocode.py /Users/javjrg/Desktop/socavon/mintpy/inputs/geometryRadar.h5 temporalCoherence.h5 avgSpatialCoh.h5 /Users/javjrg/Desktop/socavon/mintpy/timeseries_demErr.h5 velocity.h5 -l /Users/javjrg/Desktop/socavon/mintpy/inputs/geometryRadar.h5 -t /Users/javjrg/Desktop/socavon/mintpy/smallbaselineApp.cfg --outdir /Users/javjrg/Desktop/socavon/mintpy/geo --update
read input option from template file: /Users/javjrg/Desktop/socavon/mintpy/smallbaselineApp.cfg
Traceback (most recent call last):
  File "/Users/javjrg/opt/anaconda3/envs/mintpy/bin/smallbaselineApp.py", line 8, in <module>
    sys.exit(main())
  File "/Users/javjrg/tools/MintPy/mintpy/cli/smallbaselineApp.py", line 208, in main
    run_smallbaselineApp(inps)
  File "/Users/javjrg/tools/MintPy/mintpy/smallbaselineApp.py", line 1115, in run_smallbaselineApp
    app.run(steps=inps.runSteps)
  File "/Users/javjrg/tools/MintPy/mintpy/smallbaselineApp.py", line 915, in run
    self.run_geocode(sname)
  File "/Users/javjrg/tools/MintPy/mintpy/smallbaselineApp.py", line 767, in run_geocode
    mintpy.cli.geocode.main(iargs)
  File "/Users/javjrg/tools/MintPy/mintpy/cli/geocode.py", line 237, in main
    inps = cmd_line_parse(iargs)
  File "/Users/javjrg/tools/MintPy/mintpy/cli/geocode.py", line 114, in cmd_line_parse
    inps = read_template2inps(inps.templateFile, inps)
  File "/Users/javjrg/tools/MintPy/mintpy/cli/geocode.py", line 191, in read_template2inps
    iDict[key] = [float(i) for i in value.split(',')]
  File "/Users/javjrg/tools/MintPy/mintpy/cli/geocode.py", line 191, in <listcomp>
    iDict[key] = [float(i) for i in value.split(',')]
ValueError: could not convert string to float: '[-27.48'
```

**Do you have any idea what could be going on?**

**Thanks a lot**

**System information**

* Operating system: macOS
* Python environment: manual,
* MintPy version: 1.4.1-16, date 2022-10-09
* Your custom / default template file (if the bug is related to a specific dataset): 
[socavon.txt](https://github.com/insarlab/MintPy/files/9806410/socavon.txt)

**Comment by yunjunz** [comment]
Using `mintpy.geocode.SNWE         = -27.48,-27.45,-70.29,-70.26` without the `[]` should fix the issue. 

I will issue a PR to tolerate (auto fix) this common typo in the future.

**Comment by yunjunz** [comment]
> Thanks a lot, I got confused when entering that information. Now I can run without problems.

This is a common typo, due to our specific doc style. Let's keep this issue open to remind me of issuing the PR.
