### ISSUE TITLE
ISCE2 StripmapStack load_data looking for ionUnwFile

### ISSUE THREAD

**Issue by EJFielding** [insarlab/MintPy#891]
**Description of the problem**

I am trying to load the data from a UAVSAR stack that was processed with ISCE2 stripmapStack workflow. It seems to require `mintpy.load.ionUnwFile` that is never generated for UAVSAR processing.

**Full script that generated the error**

```
load_data.py -t Haywrd_15302_03-s2-UAVSAR.txt --project Uavsar_Haywrd_15302_03-s2
```

**Full error message**

```
processor : isce
SAR platform/sensor : Uav
--------------------------------------------------
prepare metadata files for isce products
Traceback (most recent call last):
  File "/u/vento-r0/ericf/packages/Anaconda/anaconda3/envs/mintpy141/bin/load_data.py", line 10, in <module>
    sys.exit(main())
  File "/u/vento-r0/ericf/packages/Anaconda/anaconda3/envs/mintpy141/lib/python3.10/site-packages/mintpy/load_data.py", line 898, in main
    prepare_metadata(iDict)
  File "/u/vento-r0/ericf/packages/Anaconda/anaconda3/envs/mintpy141/lib/python3.10/site-packages/mintpy/load_data.py", line 762, in prepare_metadata
    obs_paths = [iDict[key] for key in obs_keys if iDict[key].lower() != 'auto']
  File "/u/vento-r0/ericf/packages/Anaconda/anaconda3/envs/mintpy141/lib/python3.10/site-packages/mintpy/load_data.py", line 762, in <listcomp>
    obs_paths = [iDict[key] for key in obs_keys if iDict[key].lower() != 'auto']
KeyError: 'mintpy.load.ionUnwFile'
```

**System information**

* Operating system:  Linux-CentOS
* Python environment:  conda
* MintPy version: MintPy version 1.4.1, date 2022-08-15
* Your custom / default template file (if the bug is related to a specific dataset): 
[Haywrd_15302_03-s2-UAVSAR.txt](https://github.com/insarlab/MintPy/files/9945263/Haywrd_15302_03-s2-UAVSAR.txt)

**Comment by yunjunz** [comment]
The default template fie `smallbaselineApp.cfg` is required in the input, while the custom template file, `Haywrd_15302_03-s2-UAVSAR.txt` in your case, is optional.

This is shown in the `load_data.py -h` examples. Let's keep this issue open to remind me to add a checking and show this msg directly in the future PR.

**Comment by EJFielding** [comment]
Thanks for the clarification. I tried doing the load with the full configuration file and get a different error:
```
load_data.py -t smallbaselineApp.cfg  --project Uavsar_Haywrd_15302_03-s2
processor : isce
SAR platform/sensor : Uav
--------------------------------------------------
prepare metadata files for isce products
prep_isce.py -m /u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s2/Igrams/20100301_20100423/referenceShelve/data.dat -g /u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s2/geom_reference -b /u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s2/baselines -f "/u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s2/Igrams/*/filt_*.unw" --geom-files hgt.rdr lat.rdr lon.rdr los.rdr los.rdr shadowMask.rdr waterMask.rdr
extract metadata from ISCE/stripmapStack shelve file: /u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s2/Igrams/20100301_20100423/referenceShelve/data.dat
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
/u/vento-r0/ericf/packages/Anaconda/anaconda3/envs/mintpy141/lib/python3.10/site-packages/mintpy/load_data.py:785: UserWarning: prep_isce.py failed. Assuming its result exists and continue...
  warnings.warn('prep_isce.py failed. Assuming its result exists and continue...')
--------------------------------------------------
updateMode : True
compression: None
multilook x/ystep: 1/1
multilook method : nearest
--------------------------------------------------
searching geometry files info
input data files:
height          : /u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s2/geom_reference/hgt.rdr
latitude        : /u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s2/geom_reference/lat.rdr
longitude       : /u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s2/geom_reference/lon.rdr
incidenceAngle  : /u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s2/geom_reference/los.rdr
azimuthAngle    : /u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s2/geom_reference/los.rdr
shadowMask      : /u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s2/geom_reference/shadowMask.rdr
waterMask       : /u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s2/geom_reference/waterMask.rdr
/u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s2/MintPy_v2/inputs/geometryRadar.h5 exists, but can not read, remove it.
--------------------------------------------------
create HDF5 file /u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s2/MintPy_v2/inputs/geometryRadar.h5 with w mode
create dataset /height             of <class 'numpy.float32'>   in size of (8333, 4950) with compression = lzf
create dataset /latitude           of <class 'numpy.float32'>   in size of (8333, 4950) with compression = lzf
create dataset /longitude          of <class 'numpy.float32'>   in size of (8333, 4950) with compression = lzf
create dataset /incidenceAngle     of <class 'numpy.float32'>   in size of (8333, 4950) with compression = lzf
create dataset /azimuthAngle       of <class 'numpy.float32'>   in size of (8333, 4950) with compression = lzf
create dataset /shadowMask         of <class 'numpy.bool_'>     in size of (8333, 4950) with compression = lzf
create dataset /waterMask          of <class 'numpy.bool_'>     in size of (8333, 4950) with compression = lzf
prepare slantRangeDistance ...
Traceback (most recent call last):
  File "/u/vento-r0/ericf/packages/Anaconda/anaconda3/envs/mintpy141/bin/load_data.py", line 10, in <module>
    sys.exit(main())
  File "/u/vento-r0/ericf/packages/Anaconda/anaconda3/envs/mintpy141/lib/python3.10/site-packages/mintpy/load_data.py", line 936, in main
    geom_radar_obj.write2hdf5(
  File "/u/vento-r0/ericf/packages/Anaconda/anaconda3/envs/mintpy141/lib/python3.10/site-packages/mintpy/objects/stackDict.py", line 748, in write2hdf5
    data = self.get_slant_range_distance(box=box, xstep=xstep, ystep=ystep)
  File "/u/vento-r0/ericf/packages/Anaconda/anaconda3/envs/mintpy141/lib/python3.10/site-packages/mintpy/objects/stackDict.py", line 504, in get_slant_range_distance
    data = ut.range_distance(self.extraMetadata,
  File "/u/vento-r0/ericf/packages/Anaconda/anaconda3/envs/mintpy141/lib/python3.10/site-packages/mintpy/utils/utils0.py", line 53, in range_distance
    range_n, dR = float(atr['STARTING_RANGE']), float(atr['RANGE_PIXEL_SIZE'])
KeyError: 'STARTING_RANGE'
```

**Comment by EJFielding** [comment]
I see it says the `prep_isce.py` failed, so I ran that directly and see an error:
```
(mintpy141) [fielding@sar MintPy_v2]$ prep_isce.py -m /u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s2/Igrams/20100301_20100423/referenceShelve/data.dat -g /u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s2/geom_reference -b /u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s2/baselines -f "/u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s2/Igrams/*/filt_*.unw" --geom-files hgt.rdr lat.rdr lon.rdr los.rdr los.rdr shadowMask.rdr waterMask.rdr
extract metadata from ISCE/stripmapStack shelve file: /u/sar-r0/fielding/Calif/SF_Bay/UAVSAR/Stacks/Haywrd_15302_03/s2/Igrams/20100301_20100423/referenceShelve/data.dat
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
Traceback (most recent call last):
  File "/u/vento-r0/ericf/packages/Anaconda/anaconda3/envs/mintpy141/lib/python3.10/shelve.py", line 111, in __getitem__
    value = self.cache[key]
KeyError: 'frame'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/u/vento-r0/ericf/packages/Anaconda/anaconda3/envs/mintpy141/bin/prep_isce.py", line 10, in <module>
    sys.exit(main())
  File "/u/vento-r0/ericf/packages/Anaconda/anaconda3/envs/mintpy141/lib/python3.10/site-packages/mintpy/prep_isce.py", line 271, in main
    metadata = isce_utils.extract_isce_metadata(
  File "/u/vento-r0/ericf/packages/Anaconda/anaconda3/envs/mintpy141/lib/python3.10/site-packages/mintpy/utils/isce_utils.py", line 112, in extract_isce_metadata
    meta, frame = extract_stripmap_metadata(meta_file)
  File "/u/vento-r0/ericf/packages/Anaconda/anaconda3/envs/mintpy141/lib/python3.10/site-packages/mintpy/utils/isce_utils.py", line 226, in extract_stripmap_metadata
    frame = mdb['frame']
  File "/u/vento-r0/ericf/packages/Anaconda/anaconda3/envs/mintpy141/lib/python3.10/shelve.py", line 114, in __getitem__
    value = Unpickler(f).load()
  File "/u/pez0/fielding/tools/ISCE2_test/install/isce/components/iscesys/Component/TraitSeq.py", line 33, in <module>
    from collections import MutableSequence
ImportError: cannot import name 'MutableSequence' from 'collections' (/u/vento-r0/ericf/packages/Anaconda/anaconda3/envs/mintpy141/lib/python3.10/collections/__init__.py)
```

**Comment by yunjunz** [comment]
I guess this is a similar issue I had before with `shelve` (https://github.com/insarlab/MintPy/pull/384). Using `shelve` is a bad choice in isce2. The easy way out should be running `prep_isce.py` in the same python env where you ran the UAVSAR stack.

**Comment by EJFielding** [comment]
Thanks for the suggestion. I am trying to install MintPy in the same environment as the ISCE2 environment that I used. It is taking a long time to "solve". I have a conda environment with both ISCE2 and MintPy installed, but it is about a year old so not likely to work with the newly processed data.

**Comment by EJFielding** [comment]
I see that my `isce2` environment that I use to run ISCE2 programs is using Python 3.7, so the newer Python versions changed something in the way that "shelve" is implemented. Now I have to see if I can get MintPy installed into that older environment.

**Comment by falkamelung** [comment]
I am installing ISCE with mamba as it did not work for me with conda (it was solving things forever). For MintPy conda works fine for me.

**Comment by EJFielding** [comment]
I created a new Anaconda environment and installed both `isce2` and `mintpy` from `'conda-forge`. This worked well. I reran the UAVSAR processing in this environment and had no trouble loading it into MintPy in the same environment.
