### ISSUE TITLE
Error after load_data

### ISSUE THREAD

**Issue by InSAR2023** [insarlab/MintPy#961]
updateMode : True
compression: None
multilook x/ystep: 1/1
multilook method : nearest
/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/numpy/core/_methods.py:182: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
Traceback (most recent call last):
  File "/home/ahmed/anaconda3/envs/InSARenv/bin/smallbaselineApp.py", line 10, in <module>
    sys.exit(main())
  File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/cli/smallbaselineApp.py", line 208, in main
    run_smallbaselineApp(inps)
  File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/smallbaselineApp.py", line 1117, in run_smallbaselineApp
    app.run(steps=inps.runSteps)
  File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/smallbaselineApp.py", line 874, in run
    self.run_load_data(sname)
  File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/smallbaselineApp.py", line 176, in run_load_data
    mintpy.cli.load_data.main(iargs)
  File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/cli/load_data.py", line 123, in main
    load_data(inps)
  File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/load_data.py", line 800, in load_data
    iDict = read_subset_box(iDict)
  File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/load_data.py", line 200, in read_subset_box
    pix_box = coord.bbox_geo2radar(geo_box)
  File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/objects/coord.py", line 450, in bbox_geo2radar
    y, x, y_res, x_res = self.geo2radar(lat, lon, print_msg=print_msg)
  File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/objects/coord.py", line 314, in geo2radar
    az[i], rg[i] = self._get_lookup_row_col(
  File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/objects/coord.py", line 187, in _get_lookup_row_col
    raise RuntimeError(f'No coresponding coordinate found for y/x: {y}/{x}')
RuntimeError: No coresponding coordinate found for y/x: 30.2994/-91.3913
>>

**Comment by yunjunz** [comment]
Please follow the [bug report template](https://github.com/insarlab/MintPy/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) to provide more details for diagnosis.

**Comment by InSAR2023** [comment]
******************** step - load_data ********************
load_data.py --template /media/ahmed/easythree/EZ-InSAR/stackmintpy/smallbaselineApp.cfg /media/ahmed/easythree/EZ-InSAR/stackmintpy/mintpyfullparametersSenAT165.cfg --project mintpyfullparametersSenAT165
processor : isce
SAR platform/sensor : Sen

prepare metadata files for isce products
prep_isce.py -m /media/ahmed/easythree/EZ-InSAR/reference/IW1.xml -g /media/ahmed/easythree/EZ-InSAR/merged/geom_reference -b /media/ahmed/easythree/EZ-InSAR/baselines -f "/media/ahmed/easythree/EZ-InSAR/merged/interferograms//filt.unw" --geom-files hgt.rdr lat.rdr lon.rdr los.rdr los.rdr shadowMask.rdr waterMask.rdr
['/media/ahmed/easythree/EZ-InSAR/reference/data.rsc'] exists and is newer than ['/media/ahmed/easythree/EZ-InSAR/reference/IW1.xml'] --> skip.
preparing RSC file for geometry files
read perp baseline time-series from /media/ahmed/easythree/EZ-InSAR/baselines
preparing RSC file for: /media/ahmed/easythree/EZ-InSAR/merged/interferograms//filt.unw
[==> 6% ] 20200107_20200119 1/18 0s / 0s
[=====> 11% ] 20200107_20200131 2/18 0s / 0s
[=======> 17% ] 20200107_20200212 3/18 0s / 0s
[==========> 22% ] 20200119_20200131 4/18 0s / 0s
[=============> 28% ] 20200119_20200212 5/18 0s / 0s
[===============> 33% ] 20200119_20200224 6/18 0s / 0s
[===================> 39% ] 20200131_20200212 7/18 0s / 0s
[=====================> 44% ] 20200131_20200224 8/18 0s / 0s
[======================= 50% ] 20200131_20200307 9/18 0s / 0s
[======================= 56% ] 20200212_20200224 10/18 0s / 0s
[======================= 61% => ] 20200212_20200307 11/18 0s / 0s
[======================= 67% =====> ] 20200212_20200319 12/18 0s / 0s
[======================= 72% =======> ] 20200224_20200307 13/18 0s / 0s
[======================= 78% ==========> ] 20200224_20200319 14/18 0s / 0s
[======================= 83% =============> ] 20200224_20200331 15/18 0s / 0s
[======================= 89% ===============> ] 20200307_20200319 16/18 0s / 0s
[======================= 94% ==================> ] 20200307_20200331 17/18 0s / 0s
[==================================================] 20200319_20200331 18/18
Done.

updateMode : True
compression: None
multilook x/ystep: 1/1
multilook method : nearest
/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
return _methods._mean(a, axis=axis, dtype=dtype,
/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/numpy/core/_methods.py:182: RuntimeWarning: invalid value encountered in divide
ret = um.true_divide(
Traceback (most recent call last):
File "/home/ahmed/anaconda3/envs/InSARenv/bin/smallbaselineApp.py", line 10, in
sys.exit(main())
File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/cli/smallbaselineApp.py", line 208, in main
run_smallbaselineApp(inps)
File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/smallbaselineApp.py", line 1117, in run_smallbaselineApp
app.run(steps=inps.runSteps)
File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/smallbaselineApp.py", line 874, in run
self.run_load_data(sname)
File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/smallbaselineApp.py", line 176, in run_load_data
mintpy.cli.load_data.main(iargs)
File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/cli/load_data.py", line 123, in main
load_data(inps)
File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/load_data.py", line 800, in load_data
iDict = read_subset_box(iDict)
File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/load_data.py", line 200, in read_subset_box
pix_box = coord.bbox_geo2radar(geo_box)
File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/objects/coord.py", line 450, in bbox_geo2radar
y, x, y_res, x_res = self.geo2radar(lat, lon, print_msg=print_msg)
File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/objects/coord.py", line 314, in geo2radar
az[i], rg[i] = self._get_lookup_row_col(
File "/home/ahmed/anaconda3/envs/InSARenv/lib/python3.8/site-packages/mintpy/objects/coord.py", line 187, in _get_lookup_row_col
raise RuntimeError(f'No coresponding coordinate found for y/x: {y}/{x}')
RuntimeError: No coresponding coordinate found for y/x: 30.2994/-91.3913

**System information**

* Operating system: Linux-Ubuntu (20.04)
* Python environment: conda (anaconda3)
* MintPy version: 1.5.1

**Comment by InSAR2023** [comment]
This problem was due to numpy version.  It's solved by numpy 1.24 and setting for ISCE new version.

**Comment by yunjunz** [comment]
Glad you find out the cause and solution. Close the issue.
