### ISSUE TITLE
Error in correct_topography

### ISSUE THREAD

**Issue by InSAR2023** [insarlab/MintPy#965]
Hello everyone,

In step 10 (correct_topography) I got an error. Since it was an optional step, I rejected it and did the rest of the steps. How do I fix this error? This error is due to parallel processing in MintPy.

```bash
FUTURE #4 complete. Time used: 121 seconds
close dask client
2023-02-22 23:51:43,612 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home/ahmed/mconda/miniconda3/envs/InSARenv/lib/python3.8/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ahmed/mconda/miniconda3/envs/InSARenv/lib/python3.8/site-packages/distributed/worker.py", line 1216, in heartbeat
    response = await retry_operation(
  File "/home/ahmed/mconda/miniconda3/envs/InSARenv/lib/python3.8/site-packages/distributed/utils_comm.py", line 419, in retry_operation
    return await retry(
  File "/home/ahmed/mconda/miniconda3/envs/InSARenv/lib/python3.8/site-packages/distributed/utils_comm.py", line 404, in retry
    return await coro()
  File "/home/ahmed/mconda/miniconda3/envs/InSARenv/lib/python3.8/site-packages/distributed/core.py", line 1221, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/home/ahmed/mconda/miniconda3/envs/InSARenv/lib/python3.8/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/home/ahmed/mconda/miniconda3/envs/InSARenv/lib/python3.8/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/home/ahmed/mconda/miniconda3/envs/InSARenv/lib/python3.8/site-packages/distributed/comm/tcp.py", line 144, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://127.0.0.1:39176 remote=tcp://127.0.0.1:45899>: Stream is closed
close dask cluster
------- finished parallel processing -------
```

Operating system: Linux-Ubuntu (20.04)
Python environment: conda (miniconda) - python3.8
MintPy version: 1.5.1

**Comment by yunjunz** [comment]
I suggest turning off the dask parallelization and trying this step again, to see if this issue is due to dask or other reasons.
